'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine.js');let passed=0;
const fresh=(cls='paladin',mode='normal',opts={})=>new C(mode,cls,()=>.9,opts);
const boss=c=>c.zone().enemies.find(e=>e.type==='boss');
const kill=(c,e)=>{e.heroParticipated=true;e.hp=0;c.kill(e);};
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){process.exitCode=1;console.error('FAIL '+name+' '+e.stack);}}
test('F01 normal-normal-TRUE cycle uses the five-second remote transition and leaves one normal field boss',()=>{const c=fresh(),e=boss(c);c.zone().enemies=[e];kill(c,e);c.updateEnemies(121);kill(c,e);c.updateElites(4.9);assert(!c.zone().enemies.some(x=>x.form==='true'&&x.hp>0));c.updateElites(.2);const t=c.zone().enemies.find(x=>x.form==='true'&&x.hp>0);assert(t);kill(c,t);c.updateEnemies(121);assert.equal(c.zone().enemies.filter(x=>x.hp>0&&!x.summon).length,1);});
test('F02 sealed boss resets and no attack shape damages through terrain',()=>{const c=fresh(),e=boss(c);c.s.party=[];c.zone().enemies=[e];Object.assign(e,{x:1100,y:1000,home:{x:1100,y:1000}});Object.assign(c.hero,{x:1300,y:1000});c.zone().props.push({x:1100,y:930,r:45},{x:1100,y:1070,r:45},{x:1030,y:1000,r:45});c.engage(e);const hp=c.hero.hp;for(const kind of ['circle','line','cone','sector'])c.resolveArea(e,{kind,x:1300,y:1000,fromX:1100,fromY:1000,angle:0,radius:400,coefficient:1});assert.equal(c.hero.hp,hp);const original=c.follow;c.follow=()=>false;for(let i=0;i<140;i++)c.updateEnemies(.1);c.follow=original;assert(c.s.statistics.events.some(x=>x.type==='reset'));assert(!e.aggro);});
test('F03 TRUE crypt volleys stagger and family follow-ups retain full warnings',()=>{for(const [id,index]of [['crypt',1],['archive',1],['mine',1],['abyss',0]]){const c=fresh();c.enter(id);const e=c.bossEnemy(c.boss(id),'true',{x:1050,y:1100});c.zone().enemies=[e];Object.assign(c.hero,{x:1200,y:1100});e.attackIndex=0;c.startAttack(e,c.hero,index);if(id==='crypt'){c.resolveAttack(e);assert.deepEqual(c.s.projectiles.map(x=>x.delay),[0,.35,.7]);assert.equal(c.s.hazards.length,0);}else{assert(e.sequence.length);assert(e.sequence.every(a=>a.timer>=1.5));if(id==='abyss')assert(e.sequence.some(a=>a.kind==='circle'&&a.persistent));}}});
test('F04 rejects fractional equipment and missing Nightmare victory records before restore',()=>{const c=fresh('mage','nightmare');for(const mutate of [s=>s.hero.weapon=.5,s=>delete s.victories,s=>delete s.pending]){const s=c.snapshot();mutate(s);assert.throws(()=>C.restore(s));}C.restore(c.snapshot());});
test('F06 class effects retain ice, double shot, haste, distinct burst and final protection',()=>{for(const cls of ['mage','ranger','paladin']){const c=fresh(cls),e=c.makeEnemy({name:'fixture',species:'goblin',level:1,hp:10000,damage:1,gold:0,xp:0},{x:350,y:350});c.zone().enemies=[e];c.hero.skills=Array(8).fill(1);c.hero.maxMp=c.hero.mp=1000;c.cast(2,e.id);assert.equal(c.s.projectiles.length,cls==='ranger'?2:cls==='mage'?1:0);for(let i=0;i<10;i++)c.updateProjectiles(.1);if(cls==='mage')assert.equal(e.slow,4);c.cast(6,e.id);if(cls==='ranger')assert(c.hero.haste>0);c.hero.hp=1;c.cast(8,e.id);assert(c.hero.hp>1);assert(c.hero.immune>=3);}});
test('F07 fortress objective requires both Crown specialists and night observation needs its site',()=>{const c=fresh();c.enter('crown');c.accept('quest-29');c.discover('port');assert(!c.s.quests['quest-29'].done);c.discover('fortress-gate');assert(!c.s.quests['quest-29'].done,'fortress gate alone does not bypass the two Crown specialist rescues');c.s.keys.cindermaw=true;assert(c.rescue('cindermaw'));assert(!c.s.quests['quest-29'].done,'Vera alone is not enough');c.s.keys.citadel=true;assert(c.rescue('citadel'));assert(c.s.quests['quest-29'].done,'both Crown specialists plus the fortress gate complete the approach');c.enter('march');c.accept('quest-10');c.s.clock=500;c.updateNight();c.s.quests['quest-10'].count=2;c.checkQuests();assert(!c.s.quests['quest-10'].done);c.discover('night-site');assert(c.s.quests['quest-10'].done);});
test('F08 barracks queues create reserves beyond the active cap without losing paid recruits',()=>{const c=fresh();c.hero.gold=10000;c.s.rescued.thorn=true;c.trainExpedition('thorn');c.zone().buildings.push({id:'test',x:300,y:350,progress:4,queue:0,queueType:null,full:false,upgradeProgress:0,upgradePaid:false});for(let i=0;i<5;i++){assert(c.train('test'));c.updateParty(4.1);}assert.equal(c.rosterCount(),7);assert.equal(c.activeParty().length,3);assert.equal(c.s.party.filter(u=>u.active===false).length,4);c.s.party[0].hp=0;const g=c.hero.gold;assert(c.recover());assert.equal(c.hero.gold,g-40);assert.equal(c.rosterCount(),7);});
test('F09 companion presence prevents patrol respawn',()=>{const c=fresh(),e=c.zone().enemies.find(e=>e.pack),members=c.zone().enemies.filter(x=>x.pack===e.pack);members.forEach(x=>kill(c,x));Object.assign(c.s.party[0],e.home);Object.assign(c.hero,{x:300,y:350});c.updatePacks(61);assert(members.every(x=>x.hp===0));});
test('F10 minor refuge survives death and reload',()=>{const c=fresh();Object.assign(c.hero,{x:900,y:700});c.rest();const r=C.restore(c.snapshot());r.die();assert.deepEqual([r.hero.x,r.hero.y],[900,700]);});
test('F11 Succession preserves a recovery crossing after paid outward travel',()=>{const c=fresh('paladin','normal',{succession:true});c.hero.gold=25;assert(c.travel(1));c.die();c.successor('mage');assert(c.travel(1));assert.equal(c.hero.gold,0);});
test('F12 ranged basics aim and fire faster while remaining dodgeable and terrain-blocked',()=>{const c=fresh();c.enter('frontier');const e=c.zone().enemies.find(e=>e.species==='archer');c.s.party=[];c.zone().enemies=[e];Object.assign(e,{x:1600,y:750,home:{x:1600,y:750}});Object.assign(c.hero,{x:1760,y:750});c.engage(e);const hp=c.hero.hp;c.updateEnemies(.1);assert(e.rangedAim);assert.equal(e.rangedAim.timer,C.rules.rangedEnemyCombat.aimTime);for(let i=0;i<4;i++)c.updateEnemies(.1);assert(c.s.projectiles.length);assert.equal(c.hero.hp,hp);const p=c.s.projectiles[0];assert.equal(p.speed,e.shotSpeed*C.rules.rangedEnemyCombat.projectileMultiplier);assert.equal(e.cd,C.rules.rangedEnemyCombat.cooldown);c.zone().props.push({x:p.x+p.dx*35,y:p.y+p.dy*35,r:24});c.updateProjectiles(.3);assert.equal(c.s.projectiles.length,0);assert.equal(c.hero.hp,hp);const b=c.bossEnemy(c.boss('crypt'),'normal',{x:1000,y:1000});b.attackIndex=0;c.zone().enemies=[b];Object.assign(c.hero,{x:1200,y:1000});c.startAttack(b,c.hero,1);c.resolveAttack(b);assert.equal(c.s.projectiles[0].speed,260*C.rules.enemyProjectileMultiplier);});
test('F13 boss specials chain rapidly while warnings stay authored and every fourth special yields one fast basic',()=>{const c=fresh(),e=boss(c);c.s.party=[];c.zone().enemies=[e];Object.assign(c.hero,{x:e.x+60,y:e.y,maxHp:100000,hp:100000});c.engage(e);e.attackIndex=2;c.startAttack(e,c.hero,2);const warning=e.telegraph.total,hp=c.hero.hp;c.resolveAttack(e);assert(Math.abs(hp-c.hero.hp-7.2)<1e-8);assert.equal(warning,1.2);e.telegraph.timer=0;c.updateEnemies(.1);assert.equal(e.cd,.25);assert.equal(e.basicDue,false);e.cd=0;c.updateEnemies(.1);assert(e.telegraph,'boss immediately begins another warned special');e.telegraph=null;e.motion=null;e.sequence=[];e.attackIndex=3;e.cd=0;e.basicDue=false;c.startAttack(e,c.hero,3);e.telegraph.timer=0;c.updateEnemies(.1);assert(e.basicDue,'fourth special schedules one basic');e.cd=0;c.updateEnemies(.1);assert.equal(e.telegraph,null);assert.equal(e.basicDue,false);assert.equal(e.cd,.75);assert.equal(C.rules.bossCadence.specialRange,600);});
test('F14 pounce moves to its mark, mine openings increase output, and Dark Lord Crown phase becomes weighted rather than scripted',()=>{const c=fresh(),e=boss(c);c.zone().props=[];c.s.party=[];c.zone().enemies=[e];Object.assign(c.hero,{x:e.x+150,y:e.y});e.attackIndex=0;c.startAttack(e,c.hero,1);const mark={x:e.telegraph.x,y:e.telegraph.y};c.resolveAttack(e);for(let i=0;i<10&&e.motion;i++)c.advanceMotion(e,.1);assert(Math.hypot(e.x-mark.x,e.y-mark.y)<20);c.enter('mine');const m=boss(c);Object.assign(c.hero,c.safe(m.x-60,m.y));m.open=0;const h=m.hp;c.damage(m,100);const closed=h-m.hp;m.open=3;const h2=m.hp;c.damage(m,100);assert(m.hp<h2-closed);c.enter('crown');const d=c.bossEnemy(c.boss('darklord'),'normal',{x:3250,y:3200});c.zone().enemies=[d];const crownRangeTarget={x:d.x+210,y:d.y};d.hp=d.maxHp*.8;assert.equal(c.bossAttackWeights(d,crownRangeTarget)[3],0);d.hp=d.maxHp*.4;const low=c.bossAttackWeights(d,crownRangeTarget);assert(low[3]>0);d.lastAttackIndex=3;assert.equal(c.bossAttackWeights(d,c.hero)[3],0,'Crown phase cannot immediately repeat itself');});
test('F16 arrival failure rolls back fare, ticket and destination even after mutation',()=>{const c=fresh();c.hero.gold=25;const before=c.snapshot();c.enter=()=>{c.s.zone='march';c.hero.gold=0;throw Error('arrival');};assert(!c.travel(1));assert.deepEqual(c.snapshot(),before);});
test('F17 idle night health preserves fraction; F19 full barracks are valid resource deposits',()=>{const c=fresh(),e=c.zone().enemies.find(x=>x.type==='mob');c.zone().enemies=[e];e.hp=e.baseHp/2;c.s.clock=500;c.updateEnemies(.1);assert(Math.abs(e.hp/e.maxHp-.5)<1e-9);assert(e.maxHp>e.baseHp);c.s.rescued.ridge=true;while(c.s.expeditionRank<4)c.trainExpedition('ridge');c.hero.gold=1000;assert(c.build());const b=c.zone().buildings.at(-1);for(let i=0;i<50;i++)c.updateParty(.1);assert.equal(b.full,false,'Rank 4 build still starts Basic');assert(c.upgradeBarracks(b.id));for(let i=0;i<50;i++)c.updateParty(.1);assert(b.full,'deposit behavior requires the optional Full upgrade');const u=c.activeLivingParty()[0];Object.assign(u,{x:b.x+10,y:b.y+10,carry:35,order:{type:'deposit'}});const g=c.hero.gold;c.updateParty(.1);assert.equal(c.hero.gold,g+35);});
test('F20 legacy region and regional buildings survive while retired potion stock is safely discarded',()=>{const legacy={version:2,activeRegion:'world',player:{heroClass:'mage',level:7,gold:500,wx:3200,maxHp:500,hp:10,maxMp:500,mp:10},inventory:['Arma de las Cumbres','Tónico de las Cumbres','Éter de las Cumbres','Poción de Maná Grande'],squad:{buildings:[{wx:2250,wy:1000,progress:4,queue:0}],units:[],nodes:[]}};const c=C.migrate(legacy);assert.equal(c.zoneId,'crown');assert.equal(c.s.zones.frontier.buildings.length,1);assert(c.equipLegacy('Arma de las Cumbres'));assert.equal(c.power(),c.hero.power+70);assert(!c.equipLegacy('unknown'));assert.deepEqual(c.hero.potions,{health:0,mana:0,greater_health:0,greater_mana:0});assert.deepEqual(c.hero.legacyPotions,[],'legacy potion inventory is retired without affecting the rest of the save');assert(Math.abs(c.hero.mp-2.6)<1e-9,'legacy MP percentage is normalized to the new curve');const restored=C.restore(c.snapshot());assert.equal(restored.zoneId,'crown');assert.equal(restored.s.zones.frontier.buildings.length,1);});
test('F21 area kill sequence is independent of enemy array order',()=>{const outcomes=[];for(const reverse of [false,true]){const c=fresh();c.hero.skills[4]=1;const a=['goblin','goblin','skeleton'].map((species,i)=>c.makeEnemy({species,name:species,level:1,hp:1,damage:1,gold:0,xp:0},{x:350+i*10,y:350}));c.zone().enemies=reverse?a.reverse():a;c.cast(5);outcomes.push({streak:c.s.streak,pending:Object.keys(c.s.pending)});}assert.deepEqual(outcomes[0],outcomes[1]);});
test('F23 every authored landmark is reachable, towns have solid structures and dungeon walls differ',()=>{const wallSignatures=[];for(const r of C.data.regions){const c=fresh();c.enter(r.id);const z=c.zone();assert(z.props.some(p=>p.roadBlocker),'regional settlement keeps solid street-defining structures');assert(z.props.some(p=>String(p.id).startsWith('settlement-')&&p.roadBlocker&&!/(?:fence|wall|boardwalk|palisade)$/.test(String(p.structure))),'regional settlement keeps inhabited region-specific buildings');for(const n of z.npcs.filter(n=>n.kind==='landmark')){assert(!c.blocked(n.x,n.y));assert(c.route(c.hero,n).length,r.id+' '+n.name);}}for(const id of C.dungeonIds){const c=fresh();c.enter(id);wallSignatures.push(Array.from({length:100},(_,i)=>c.blocked(600+(i%10)*35,250+Math.floor(i/10)*110,c.zoneId,0)).join());assert(c.route(c.hero,boss(c)).length);}assert(new Set(wallSignatures).size>=3);});
test('F24 tactical foundation stays disabled and level safeguards are explicit',()=>{const c=fresh(),e=boss(c),cfg=C.rules.tacticalFoundation;assert.equal(cfg.enabled,false);c.zone().enemies=[e];c.s.party=[];c.hero.level=e.level-3;assert.equal(c.tacticalRogueEligibility(e,6),false);c.hero.level=e.level+1;assert.equal(c.tacticalRogueEligibility(e,0),true);c.hero.level=e.level;assert.equal(c.tacticalRogueEligibility(e,2),false);e.summonCd=3;assert.equal(c.tacticalRogueEligibility(e,2),true);assert.equal(c.tacticalProtectionTier(e),'boss');});
test('F25 tactical telemetry and extended awareness do not trigger aggro',()=>{const c=fresh(),e=boss(c);const ally=c.makeEnemy({species:'wolf',name:'ally',level:2,hp:100,damage:1,gold:0,xp:0},{x:e.x+620,y:e.y});const distant=c.makeEnemy({species:'wolf',name:'distant',level:2,hp:100,damage:1,gold:0,xp:0},{x:e.x+900,y:e.y});c.zone().enemies=[e,ally,distant];assert(c.tacticalRegroupCandidates(e).includes(ally));assert(!c.tacticalRegroupCandidates(e).includes(distant));assert.equal(ally.aggro,false);c.tacticalRecordHit(e,'hero',12);assert.equal(c.tacticalThreatSnapshot(e)[0].damage,12);assert.equal(e.aggro,false);c.s.time+=7;assert.equal(c.tacticalThreatSnapshot(e).length,0);});
test('F26 threat records expire old hits independently and never carry through travel',()=>{
const c=fresh(),e=boss(c);c.zone().enemies=[e];c.s.party=[];c.s.time=0;c.tacticalRecordHit(e,'hero',100);c.s.time=5;c.tacticalRecordHit(e,'hero',10);assert.equal(c.tacticalThreatSnapshot(e)[0].damage,110);c.s.time=7;assert.equal(c.tacticalThreatSnapshot(e)[0].damage,10,'old damage must expire even after a fresh hit');c.tacticalRecordHit(e,'hero',5);assert.equal(c.tacticalThreatSnapshot(e)[0].damage,15);c.enter('march');assert.deepEqual(c.tacticalThreatSnapshot(e),[],'zone transitions purge cached threat');assert(!Object.hasOwn(c.snapshot(),'_tacticalThreat'),'telemetry is not persisted');
});
test('F27 threat cache cleans up on death and disengagement',()=>{
const c=fresh(),e=c.makeEnemy({species:'wolf',name:'test wolf',level:1,hp:15,damage:2,gold:0,xp:0},{x:500,y:500});c.zone().enemies=[e];c.tacticalRecordHit(e,'hero',10);assert.equal(c.tacticalThreatSnapshot(e).length,1);e.aggro=true;c.disengage(e,.1);assert.deepEqual(c.tacticalThreatSnapshot(e),[]);e.returning=0;e.deathPaid=false;e.hp=0;c.tacticalRecordHit(e,'hero',10);c.kill(e);assert.deepEqual(c.tacticalThreatSnapshot(e),[]);
});
test('F28 rogue eligibility distinguishes level boundaries and actual owned support',()=>{
const c=fresh(),e=boss(c);c.zone().enemies=[e];c.hero.level=e.level;const summon=(i)=>{const u=c.makeEnemy({species:'wolf',name:'summon',level:e.level,hp:10,damage:1,gold:0,xp:0},{x:e.x+50+i*15,y:e.y});u.summon=true;u.owner=e.id;return u;};const a=summon(0),b=summon(1);c.zone().enemies.push(a,b);e.summonCd=3;assert.equal(c.tacticalRogueEligibility(e,2),false,'two owned summons protect an equal-level boss');b.hp=0;assert.equal(c.tacticalRogueEligibility(e,2),true,'one summon plus cooldown permits pressure');e.summonCd=0;assert.equal(c.tacticalRogueEligibility(e,2),false,'ready summon does not permit this exception');e.summonCd=3;assert.equal(c.tacticalRogueEligibility(e,1),false,'one attacker cannot create numerical pressure');c.hero.level=e.level-1;assert.equal(c.tacticalRogueEligibility(e,2),true,'one level stronger enemy remains eligible when pressured');c.hero.level=e.level-2;assert.equal(c.tacticalRogueEligibility(e,2),true);c.hero.level=e.level-3;assert.equal(c.tacticalRogueEligibility(e,9),false,'three levels stronger always disables rogue');c.hero.level=e.level+1;assert.equal(c.tacticalRogueEligibility(e,0),true,'hero level advantage independently enables eligibility');
});
test('F29 regroup assessment finds larger cross-pack groups without engaging them',()=>{
const c=fresh(),e=boss(c);const add=(id,pack,x,y)=>{const u=c.makeEnemy({species:'wolf',name:id,level:1,hp:40,damage:2,gold:0,xp:0},{x,y});u.pack=pack;return u;};const packA=[add('a1','group-a',e.x+500,e.y),add('a2','group-a',e.x+530,e.y),add('a3','group-a',e.x+560,e.y)],packB=[add('b1','group-b',e.x-200,e.y),add('b2','group-b',e.x-230,e.y)],far=add('far','far',e.x+900,e.y);c.zone().enemies=[e,...packA,...packB,far];const groups=c.tacticalRegroupGroups(e);assert.equal(groups[0].key,'group-b','closer allies win over distant larger packs');assert.equal(groups[0].members.length,2);assert.equal(groups[1].key,'group-a');assert.equal(groups[1].members.length,3);assert(!groups.some(g=>g.key==='far'));assert(c.zone().enemies.every(u=>!u.aggro),'awareness must not pull additional packs');
});

test('F30 explicit rogue regroup keeps original home while approaching separate pack and its anchor',()=>{const c=fresh();c.s.party=[];const e=c.makeEnemy({species:'wolf',name:'scout',level:1,hp:100,damage:1,gold:0,xp:0},{x:1400,y:1700}),a=c.makeEnemy({species:'wolf',name:'ally',level:1,hp:100,damage:1,gold:0,xp:0},{x:1950,y:1700});e.pack='scouts';a.pack='second-pack';e.aggro=true;c.zone().enemies=[e,a];Object.assign(c.hero,{x:1400,y:1700,level:3});c.route=()=>[{x:a.x,y:a.y}];c.line=()=>true;c.follow=(unit,goal,speed,dt,stop)=>{unit.x=Math.min(goal.x,unit.x+speed*dt);return true;};const home={...e.home};assert(c.tacticalBeginRogueRegroup(e,a,0));for(let i=0;i<7;i++)c.updateEnemies(.5);assert.equal(c.tacticalRogueRegroup(e)?.phase,'anchored');assert.deepEqual(e.home,home,'regroup must not overwrite respawn home');assert.equal(e.aggro,true);assert.equal(a.aggro,false,'approach alone does not create chain aggro');Object.assign(c.hero,{x:1950,y:1700});c.updateEnemies(.1);assert.equal(e.aggro,true,'being outside original leash must not reset a valid regroup');assert(c.tacticalRogueRegroup(e));const restored=C.restore(c.snapshot());assert.equal(restored.tacticalRogueRegroup(restored.zone().enemies.find(u=>u.id===e.id)),null,'transient retreat anchor cannot survive save restore');});
test('F31 real escape or protected-town approach always ends rogue leash exception',()=>{for(const protectedTown of [false,true]){const c=fresh(),e=c.makeEnemy({species:'wolf',name:'scout',level:1,hp:100,damage:1,gold:0,xp:0},{x:1400,y:1700}),a=c.makeEnemy({species:'wolf',name:'ally',level:1,hp:100,damage:1,gold:0,xp:0},{x:1950,y:1700});c.zone().enemies=[e,a];c.s.party=[];e.aggro=true;c.hero.level=3;Object.assign(c.hero,{x:1400,y:1700});c.route=()=>[{x:a.x,y:a.y}];assert(c.tacticalBeginRogueRegroup(e,a));Object.assign(c.hero,protectedTown?{x:300,y:350}:{x:2600,y:1700});c.updateEnemies(.1);assert(e.returning>0,'escape must trigger normal disengagement');assert.equal(c.tacticalRogueRegroup(e),null);}});
test('F32 rogue regroup rejects blocked or town-crossing routes and forbids retreat chaining',()=>{const c=fresh(),e=c.makeEnemy({species:'wolf',name:'scout',level:1,hp:100,damage:1,gold:0,xp:0},{x:110,y:350}),a=c.makeEnemy({species:'wolf',name:'ally',level:1,hp:100,damage:1,gold:0,xp:0},{x:620,y:350});e.aggro=true;c.s.party=[];c.zone().enemies=[e,a];c.hero.level=3;c.route=()=>[];assert.equal(c.tacticalBeginRogueRegroup(e,a),false,'unreachable regroup cannot start');c.route=()=>[{x:a.x,y:a.y}];assert.equal(c.tacticalBeginRogueRegroup(e,a),false,'route through protected settlement is prohibited');Object.assign(e,{x:1400,y:1700,home:{x:1400,y:1700}});Object.assign(a,{x:1950,y:1700,home:{x:1950,y:1700}});assert(c.tacticalBeginRogueRegroup(e,a));c.tacticalStopRogueRegroup(e);assert.equal(c.tacticalBeginRogueRegroup(e,a),false,'one regroup per engagement prevents infinite retreat loops');c.tacticalClearRogueRegroup(e);assert(c.tacticalBeginRogueRegroup(e,a));c.tacticalClearRogueRegroup(e);assert.equal(c.tacticalRogueRegroup(e),null);});
test('F33 failed retreat safely expires without suppressing later normal leash',()=>{const c=fresh(),e=c.makeEnemy({species:'wolf',name:'scout',level:1,hp:100,damage:1,gold:0,xp:0},{x:1400,y:1700}),a=c.makeEnemy({species:'wolf',name:'ally',level:1,hp:100,damage:1,gold:0,xp:0},{x:1950,y:1700});c.zone().enemies=[e,a];c.s.party=[];e.aggro=true;Object.assign(c.hero,{x:1400,y:1700,level:3});c.route=()=>[{x:a.x,y:a.y}];c.line=()=>true;assert(c.tacticalBeginRogueRegroup(e,a));c.follow=()=>false;for(let i=0;i<5;i++)c.updateEnemies(.6);assert.equal(c.tacticalRogueRegroup(e),null,'stalled rogue retreat must expire');assert.equal(c.tacticalBeginRogueRegroup(e,a),false,'failed retreat cannot chain indefinitely');Object.assign(c.hero,{x:2600,y:1700});c.updateEnemies(.1);assert(e.returning>0,'normal leash must resume after invalidated retreat');});

test('F34 a single nearby companion is sufficient for a voluntary regroup',()=>{const c=fresh();const e=c.makeEnemy({species:'wolf',name:'solitary',level:1,hp:80,damage:1,gold:0,xp:0},{x:1400,y:1700}),near=c.makeEnemy({species:'wolf',name:'one ally',level:1,hp:80,damage:1,gold:0,xp:0},{x:1520,y:1700}),far=[0,1,2].map(i=>c.makeEnemy({species:'wolf',name:'distant wolf',level:1,hp:80,damage:1,gold:0,xp:0},{x:1950+i*25,y:1700}));for(const f of far)f.pack='distant-pack';e.aggro=true;c.s.party=[];c.hero.level=2;c.zone().enemies=[e,near,...far];c.route=()=>[{x:near.x,y:near.y}];const groups=c.tacticalRegroupGroups(e);assert.equal(groups[0].members.length,1,'nearest lone ally remains a valid group');assert.equal(groups[0].members[0],near);assert(c.tacticalBeginRogueRegroup(e,near,0),'one ally is sufficient without any 3-member minimum');assert.equal(near.aggro,false,'awareness and route setup do not recruit an ally');});

test('F35 rogue regroup travel halves incoming hero and companion damage only while in transit',()=>{const c=fresh(),e=c.makeEnemy({species:'wolf',name:'regrouper',level:1,hp:1000,damage:1,gold:0,xp:0},{x:1400,y:1700}),ally=c.makeEnemy({species:'wolf',name:'support',level:1,hp:100,damage:1,gold:0,xp:0},{x:1950,y:1700}),archer=c.unit('archer',1400,1700);c.zone().enemies=[e,ally];c.s.party=[archer];e.aggro=true;c.hero.level=3;Object.assign(c.hero,{x:1400,y:1700});c.route=()=>[{x:ally.x,y:ally.y}];c.line=()=>true;assert(c.tacticalBeginRogueRegroup(e,ally));const initial=e.hp;assert(c.damage(e,100));assert.equal(initial-e.hp,50,'hero damage is reduced by 50% during travel');const afterHero=e.hp;assert(c.damage(e,100,archer.id));assert.equal(afterHero-e.hp,50,'companion damage is reduced by 50% during travel');assert.equal(c.tacticalThreatSnapshot(e).reduce((sum,v)=>sum+v.damage,0),100,'threat records actual post-reduction damage');Object.assign(e,{x:1900,y:1700});Object.assign(archer,{x:1900,y:1700});Object.assign(c.hero,{x:1900,y:1700});const atDistance=e.hp;assert(c.damage(e,100,archer.id),'regrouper remains damageable beyond normal home distance');assert.equal(atDistance-e.hp,50,'50% reduction persists through distant portion of valid travel');c.tacticalAdvanceRogueRegroup(e,c.hero,.1);assert.equal(c.tacticalRogueRegroup(e)?.phase,'anchored');const afterArrival=e.hp;assert(c.damage(e,100));assert.equal(afterArrival-e.hp,100,'reduction ends immediately on regroup arrival');c.tacticalStopRogueRegroup(e);const afterStop=e.hp;assert(c.damage(e,100));assert.equal(afterStop-e.hp,100,'cancelled regroup grants no lingering resistance');});
test('F36 rogue damage protection is never active for normal engaged enemies',()=>{const c=fresh(),e=c.makeEnemy({species:'wolf',name:'ordinary wolf',level:1,hp:1000,damage:1,gold:0,xp:0},{x:1400,y:1700});c.zone().enemies=[e];e.aggro=true;Object.assign(c.hero,{x:1400,y:1700,level:3});c.line=()=>true;const hp=e.hp;assert(c.damage(e,120));assert.equal(hp-e.hp,120,'normal combat damage remains unchanged');});

test('F37 all normal and TRUE boss families preserve warnings while gaining modest reach',()=>{
  const R=C.rules,scale=R.bossCadence.areaRangeMultiplier;
  assert.equal(scale,1.15);assert.equal(R.bossCadence.specialRange,600);
  for(const def of C.data.bosses)for(const form of ['normal','true']){
    const c=fresh(),e=c.bossEnemy(def,form,{x:1100,y:1250});
    c.zone().enemies=[e];c.s.party=[];c.line=()=>true;
    Object.assign(c.hero,{x:e.x+160,y:e.y,maxHp:100000,hp:100000});
    for(let i=0;i<R.attacks[def.id].length;i++){
      const plan=R.attacks[def.id][i];
      assert(c.startAttack(e,c.hero,i),def.id+' '+form+' explicit move can begin');
      const a=e.telegraph;
      assert.equal(a.total,plan.warning,def.id+' '+form+' keeps warning time');
      assert.equal(a.recovery,plan.recovery,def.id+' '+form+' keeps recovery time');
      const kind=plan.kind==='sector'&&e.hp>e.maxHp*.5?'cone':plan.kind;
      if(kind==='cone')assert.equal(a.radius,165*scale,def.id+' '+form+' cone');
      if(kind==='sector')assert.equal(a.radius,280*scale,def.id+' '+form+' sector');
      if(kind==='ring'){
        c.s.hazards=[];c.resolveAttack(e);
        assert.equal(c.s.hazards.at(-1).life,R.combatGeometry.ringLife*scale,def.id+' '+form+' actual expanding ring duration');
      }
      if(a.count>1&&kind==='circle'){
        assert.equal(c.attackPatches(a)[0].radius,75*scale,def.id+' '+form+' multi-target reach');
      }
    }
  }
});
test('F38 all captains reject useless distant cones but can still threaten a ranged opponent',()=>{
  const R=C.rules,scale=R.bossCadence.areaRangeMultiplier;
  const older={'supply-vale':420,'supply-march':390,'supply-highlands':430,'supply-crown':440,'frontier-overseer':440};
  for(const [key,oldRange] of Object.entries(older)){
    const c=fresh(),zone=key==='frontier-overseer'?'frontier':key;
    c.enter(zone);c.s.party=[];c.line=()=>true;
    const e=c.zone().enemies.find(u=>u.captainProfile===key && (u.captain||u.roomCaptain));
    assert(e,key+' captain exists');
    const cfg=R.roomCaptains[key];assert(cfg.specialRange>oldRange,key+' activation increased');
    e.captainOpeningSummon=true;c.random=()=>0;
    const far={x:e.x+cfg.specialRange-8,y:e.y};
    assert(c.startCaptainAttack(e,far),key+' has a viable distant special');
    assert.notEqual(e.telegraph.kind,'cone',key+' cannot waste distant cone');
    const cone=cfg.attacks.find(p=>p.kind==='cone');
    if(cone){
      // Even a currently unused close cone gains a measurable but bounded reach.
      assert((cone.radius||145)*scale<(cfg.specialRange-8),key+' melee cone remains distinct from acquisition range');
    }
  }
});
test('F39 boss selection respects actual ring reach, anti-repeat fallbacks and Dark Lord phases',()=>{
  const c=fresh(),R=C.rules,ringReach=R.combatGeometry.ringSpeed*R.combatGeometry.ringLife*R.bossCadence.areaRangeMultiplier;
  const m=c.bossEnemy(c.boss('mine'),'normal',{x:1100,y:1200});
  c.zone().enemies=[m];c.s.party=[];c.line=()=>true;m.lastAttackIndex=-1;
  assert(ringReach>R.combatGeometry.ringSpeed*R.combatGeometry.ringLife);
  assert(c.bossAttackWeights(m,{x:m.x+320,y:m.y})[2]>0,'wave is available inside actual sweep');
  assert.equal(c.bossAttackWeights(m,{x:m.x+380,y:m.y})[2],0,'wave not selected beyond actual sweep');
  const thorn=c.bossEnemy(c.boss('thorn'),'normal',{x:1100,y:1200});
  c.zone().enemies=[thorn];thorn.summonCd=100;
  assert.equal(c.bossAttackWeights(thorn,{x:thorn.x+400,y:thorn.y})[0],0,'short bite excluded at range');
  assert.equal(c.chooseBossAttack(thorn,{x:thorn.x+620,y:thorn.y}),-1,'no imaginary long-distance melee');
  assert.equal(c.startAttack(thorn,{x:thorn.x+620,y:thorn.y}),false,'invalid selection does not start a telegraph');
  const lord=c.bossEnemy(c.boss('darklord'),'normal',{x:1100,y:1200});
  c.zone().enemies=[lord];lord.summonCd=100;lord.lastAttackIndex=1;lord.hp=lord.maxHp*.8;
  assert.equal(c.chooseBossAttack(lord,{x:lord.x+440,y:lord.y}),1,'repeat the only usable special rather than wasting a cone');
  lord.hp=lord.maxHp*.4;lord.lastAttackIndex=-1;
  assert(c.bossAttackWeights(lord,{x:lord.x+240,y:lord.y})[3]>0,'Crown sector available at low health');
});
test('F40 distant follow-up combos cannot materialize short-range arcs on backline',()=>{
  const c=fresh();c.random=()=>0;c.line=()=>true;c.s.party=[];
  const e=c.bossEnemy(c.boss('darklord'),'normal',{x:1100,y:1200});
  c.zone().enemies=[e];e.hp=e.maxHp*.8;
  Object.assign(c.hero,{x:e.x+440,y:e.y});
  assert(c.startAttack(e,c.hero,1));assert(!e.sequence.some(a=>a.kind==='cone'),'distant bombardment cannot chain ineffective cleave');
  Object.assign(c.hero,{x:e.x+140,y:e.y});
  assert(c.startAttack(e,c.hero,1));assert(e.sequence.some(a=>a.kind==='cone'),'same authored combo remains available in melee range');
});
test('F41 backline targeting preserves close-attack geometry and terrain checks',()=>{
  const c=fresh(),e=c.bossEnemy(c.boss('ridge'),'normal',{x:1100,y:1200});
  c.zone().enemies=[e];c.s.party=[];
  const front={x:e.x+100,y:e.y};
  Object.assign(c.hero,{x:e.x+420,y:e.y});
  c.line=()=>true;
  assert.equal(c.bossAttackTarget(e,front,0),front,'short-range strike does not warp to distant hero');
  assert.equal(c.bossAttackTarget(e,front,1),c.hero,'ranged circle can pressure hero behind frontline');
  c.line=()=>false;
  assert.equal(c.bossAttackTarget(e,front,1),front,'cover blocks forced hero marks');
});
console.log(passed+' audit regression scenarios passed.');
