'use strict';
const assert=require('node:assert/strict'),Campaign=require('../src/prototype/engine');
const c=new Campaign();c.zone().enemies=[];c.s.party=[];Object.assign(c.hero,{x:600,y:900});const h=c.hero;
const hp=h.maxHp,mp=h.maxMp;
h.hp=hp*.51;h.mp=mp*.36;c.tick(.1);assert.equal(h.potions.health,1,'health potion waits above 50%');assert.equal(h.potions.mana,1);
h.hp=hp*.5;h.mp=mp*.2;c.tick(.1);assert.equal(h.potions.health,0,'health has priority when both are low');assert.equal(h.potions.mana,1,'shared cooldown blocks mana use');assert(h.potionCd>9);
assert.equal(h.hp,hp*.5,'auto potion starts recovery without an instant heal');assert.equal(h.potionEffect.remaining,60);
for(let i=0;i<25;i++)c.tick(.1);assert(Math.abs(h.hp-(hp*.5+30))<.001,'half the health arrives after 2.5 seconds');
const restored=Campaign.restore(c.snapshot());restored.zone().enemies=[];restored.s.party=[];Object.assign(restored.hero,{x:600,y:900});restored.hero.hp=restored.hero.maxHp;restored.hero.mp=restored.hero.maxMp*.2;restored.tick(.1);assert.equal(restored.hero.potions.mana,1,'cooldown survives save/load');
assert(!restored.hero.potionEffect,'healing ends when full');
restored.hero.potionCd=.05;restored.tick(.1);assert.equal(restored.hero.potions.mana,0,'mana automatically uses when cooldown ends');assert(restored.hero.mp>mp*.2);
const manual=new Campaign();manual.zone().enemies=[];manual.s.party=[];manual.hero.hp=manual.hero.maxHp*.65;assert(manual.potion('health'),'manual use works above automatic threshold');assert.equal(manual.hero.potions.health,0);assert(!manual.potion('mana'),'both potions share the cooldown');
assert.equal(manual.hero.hp,manual.hero.maxHp*.65);manual.tick(.1);assert(manual.hero.hp>manual.hero.maxHp*.65);const half=manual.hero.hp;const resumed=Campaign.restore(manual.snapshot());assert(resumed.hero.potionEffect);resumed.zone().enemies=[];resumed.s.party=[];Object.assign(resumed.hero,{x:600,y:900});for(let i=0;i<50;i++)resumed.tick(.1);assert(resumed.hero.hp>half);assert(resumed.hero.hp<=resumed.hero.maxHp);assert(!resumed.hero.potionEffect);
const noHealth=new Campaign();noHealth.zone().enemies=[];noHealth.s.party=[];Object.assign(noHealth.hero,{x:600,y:900});noHealth.hero.potions.health=0;noHealth.hero.hp=noHealth.hero.maxHp*.2;noHealth.hero.mp=noHealth.hero.maxMp*.2;noHealth.tick(.1);assert.equal(noHealth.hero.potions.mana,0,'missing health stock does not block mana');
console.log('PASS 50% automatic health potions, 35% mana potions, health priority, shared saved cooldown and manual fallback');
