'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine');let n=0;
function check(name,fn){fn();n++;console.log('PASS '+name);}
const kill=(c,e,hero=false)=>{e.heroParticipated=hero;e.hp=0;c.kill(e);};
for(const [i,id]of C.dungeonIds.entries())check(id+' added guards/decor/traps preserve safe routes and readable single-hit pulses',()=>{const c=new C();c.enter(id);const z=c.zone(),traps=c.traps(),guardCount=c.dungeonGuardCount(id);assert.equal(z.enemies.filter(e=>e.guard).length,guardCount);assert.equal(z.props.filter(p=>p.decorative).length,C.rules.dungeonDecor[id].length);if(id==='citadel'){assert(C.rules.dungeonDecor[id].length<=8,'Citadel consolidates loose decor into composed military stations');assert(new Set(z.props.filter(p=>p.decorative).map(p=>p.structure)).size>=7,'Citadel keeps distinct muster, command, ritual, barracks, forge, approach and administration functions');}else{assert(C.rules.dungeonDecor[id].length>=28,id+' has expanded lived-in dungeon dressing');assert(new Set(z.props.filter(p=>p.decorative).map(p=>p.structure)).size>=7,id+' dungeon has functional visual zones rather than generic decoration');}assert.equal(traps.length,[12,16,18,18,28][i]);const tuning=C.rules.dungeonTrapTuning[id];assert(tuning.cycle<=6.8);assert(tuning.active>=.8);assert(tuning.damage>=.11);assert(traps.filter(t=>Math.hypot(t.x-1160,t.y-1110)<300).length>=2);const original=c.blocked.bind(c);c.blocked=(x,y,zone,r=15,terrain)=>original(x,y,zone,r,terrain)||traps.some(t=>c.trapContains({...t,radius:t.radius+r,length:t.length+2*r},{x,y}));assert(c.route(c.hero,z.enemies.find(e=>e.type==='boss')).length);assert(c.route(c.hero,z.npcs.find(e=>e.kind==='cage')).length);c.blocked=original;c.s.party=[];const first=c.traps()[0];Object.assign(c.hero,first);z.clock=1;let hp=c.hero.hp;c.updateTraps(.1);assert.equal(c.hero.hp,hp);z.clock=1.6;c.updateTraps(.1);assert(c.hero.hp<hp);hp=c.hero.hp;c.updateTraps(.1);assert.equal(c.hero.hp,hp);assert(c.hero.hp>0);});
check('Citadel is an irregular fortress with role formations and a trap-free mandatory path',()=>{const c=new C();c.enter('citadel');const z=c.zone(),a=C.rules.dungeonArchitecture.citadel,guards=z.enemies.filter(e=>e.guard&&e.form==='normal'),traps=c.traps();assert(a&&a.walkable.length>=6&&a.partitions.length>=4,'Citadel has authored wings and internal fortress partitions');assert(a.walkable.some(x=>x.id==='service-loop')&&a.walkable.some(x=>x.id==='inner-court'),'Citadel includes a reconnecting service loop and inner command court');assert.equal(guards.length,32);assert(guards.every(e=>e.species==='crownguard'&&e.gold===0&&e.xp===0),'Citadel defenders are rewardless Crown military guardians');assert(guards.filter(e=>e.forcedRole==='melee').length>=14);assert(guards.filter(e=>e.forcedRole==='ranged').length>=14);assert.equal(traps.length,28);const points=[[160,240],[430,370],[650,1050],[1010,610],[1160,1110],[1200,1270]];for(const [x,y]of points)assert(!c.blocked(x,y,'citadel',12),'required Citadel point remains walkable: '+x+','+y);const rawBlocked=c.blocked.bind(c);c.blocked=(x,y,zone,r=15,terrain)=>rawBlocked(x,y,zone,r,terrain)||traps.some(t=>c.trapContains({...t,radius:t.radius+r,length:t.length+2*r},{x,y}));for(const target of [z.enemies.find(e=>e.type==='boss'),z.npcs.find(e=>e.kind==='cage'),{x:650,y:1050},{x:1010,y:610}])assert(c.route({x:160,y:240},target).length,'mandatory/functional Citadel destination has a completely trap-free route');c.blocked=rawBlocked;});
check('Legacy Citadel saves migrate occupants out of new masonry without resetting progress',()=>{const c=new C();c.enter('citadel');const z=c.zone(),guard=z.enemies.find(e=>e.guard);Object.assign(c.hero,{x:720,y:210});const ally=c.unit('soldier',710,230);c.s.party=[ally];guard.home={x:715,y:245};Object.assign(guard,guard.home);const snap=c.snapshot();snap.zones.citadel.dungeonVersion=2;snap.zone='citadel';const gold=snap.hero.gold,r=C.restore(snap),rz=r.zone();assert.equal(r.hero.gold,gold);assert(!r.blocked(r.hero.x,r.hero.y,'citadel',12),'hero migrates to valid Citadel floor');assert(r.activeParty().every(u=>!r.blocked(u.x,u.y,'citadel',12)),'active companions migrate to valid Citadel floor');assert(rz.enemies.filter(e=>e.guard&&e.hp>0).every(e=>!r.blocked(e.home.x,e.home.y,'citadel',12)),'surviving guardian homes migrate into valid fortress positions');assert.equal(rz.enemies.filter(e=>e.guard&&e.form==='normal').length,32,'migration fills only the new authored Citadel guard slots');});
check('Abyss Bastion is a branching containment fortress with paired zero-reward defenders and safe hazard alternatives',()=>{
 const c=new C();c.enter('abyss');const z=c.zone(),a=C.rules.dungeonArchitecture.abyss,guards=z.enemies.filter(e=>e.guard&&e.form==='normal'),traps=c.traps(),decor=z.props.filter(p=>p.decorative&&p.dungeonDistrict);
 assert.equal(z.dungeonVersion,4);assert(a&&a.walkable.length>=6&&a.partitions.length>=4,'Abyss has authored wings and containment gates instead of the legacy divider');
 assert.equal(guards.length,26);assert.equal(C.rules.dungeonGuardFormations.abyss.length,26);assert(guards.every(e=>['orc','archer'].includes(e.species)&&e.gold===0&&e.xp===0),'Bastion defenders stay regional and rewardless');
 const packs=new Map();for(const g of guards)packs.set(g.pack,(packs.get(g.pack)||0)+1);assert.equal(packs.size,13);assert([...packs.values()].every(n=>n===2),'Bastion pressure is staged as thirteen small pairs rather than giant pulls');
 assert.equal(traps.length,18,'trap density is reduced where extra hazards would become mandatory tolls');
 const districts=new Set(decor.map(p=>p.dungeonDistrict));for(const id of ['handler-intake','containment-gallery','hatchery','feeding-service','roost-hoard'])assert(districts.has(id),id+' has functional dressing');
 const structures=new Set(decor.map(p=>p.structure));for(const kind of ['handler-station','feed-crate','containment-post','scorched-floor','egg-cradle','feeding-trough','carcass-rack','claw-scrape','dragon-perch','chain-anchor'])assert(structures.has(kind),kind+' is represented');
 assert(decor.every(p=>(p.r||0)===0),'Bastion life/containment dressing never becomes collision');
 const boss=z.enemies.find(e=>e.type==='boss'),cage=z.npcs.find(n=>n.kind==='cage');assert(!c.clearSegment(c.hero,boss),'the Dragon is reached through the fortress rather than one straight rectangular room');
 const rawBlocked=c.blocked.bind(c),inflate=(t,r=24)=>({...t,radius:t.radius+r,length:t.length+2*r,halfWidth:(t.halfWidth||28)+r});
 for(const target of [boss,cage,{x:500,y:1150},{x:1000,y:600}])assert(!traps.some(t=>c.trapContains(inflate(t),target)),'required/functional destination keeps a visible hazard margin');
 c.blocked=(x,y,zone,r=15,terrain)=>rawBlocked(x,y,zone,r,terrain)||traps.some(t=>c.trapContains(inflate(t,24+r),{x,y}));
 for(const target of [boss,cage,{x:500,y:1150},{x:1000,y:600}])assert(c.route({x:160,y:240},target).length,'required/functional Abyss destination retains a maneuver-width route with every trap treated as permanently unsafe');
 c.blocked=rawBlocked;
});
check('Legacy Abyss saves adopt the new fortress without reviving defeated guardians or trapping the party',()=>{
 const c=new C();c.enter('abyss');const z=c.zone(),ordered=z.enemies.filter(e=>e.guard&&e.form==='normal').sort((a,b)=>c.idOrder(a,b)),dead=ordered[0];kill(c,dead,true);
 const snap=c.snapshot(),rz=snap.zones.abyss;rz.dungeonVersion=2;rz.enemies=rz.enemies.filter(e=>!e.guard||ordered.slice(0,22).some(g=>g.id===e.id));snap.zone='abyss';Object.assign(snap.hero,{x:650,y:200});if(snap.party[0])Object.assign(snap.party[0],{x:1300,y:600});for(const e of rz.enemies.filter(e=>e.guard)){e.home={x:650,y:200};if(e.hp>0)Object.assign(e,e.home);}
 const gold=snap.hero.gold,r=C.restore(snap);r.enter('abyss');const next=r.zone(),guards=next.enemies.filter(e=>e.guard&&e.form==='normal'&&!e.reinforcement).sort((a,b)=>r.idOrder(a,b));
 assert.equal(r.hero.gold,gold);assert.equal(next.dungeonVersion,4);assert.equal(guards.length,26,'migration adds only the four new authored slots');assert.equal(guards.find(e=>e.id===dead.id).hp,0,'defeated legacy guardian stays defeated');
 assert(!r.blocked(r.hero.x,r.hero.y,'abyss',12));assert(r.activeParty().every(u=>!r.blocked(u.x,u.y,'abyss',12)),'active party migrates out of newly solid architecture');
 for(let j=0;j<guards.length;j++){const g=r.dungeonGuardBlueprint('abyss',j),expected=r.safe(g.x,g.y,'abyss');assert.deepEqual(guards[j].home,expected,'guardian '+j+' is restaged to the authored Bastion formation');}
 assert(guards.every(e=>e.gold===0&&e.xp===0),'migrated and newly added Bastion guardians stay rewardless');
});
check('Dungeon trap pressure escalates while keeping readable warnings and safe alternatives',()=>{const cycles=[],damage=[],duty=[];for(const id of C.dungeonIds){const c=new C();c.enter(id);const t=c.traps()[0],cfg=C.rules.dungeonTrapTuning[id];cycles.push(cfg.cycle);damage.push(cfg.damage);duty.push(cfg.active/cfg.cycle);assert(t.warningTime>=1.2);assert(t.activeTime>=.8);assert(t.damageFraction===cfg.damage);}for(let i=1;i<cycles.length;i++){assert(cycles[i]<cycles[i-1]);assert(damage[i]>damage[i-1]);assert(duty[i]>duty[i-1]);}});
check('Guardian strength scales by region while main-dungeon guardians give no gold or XP',()=>{for(const [i,id] of C.dungeonIds.entries()){const c=new C();c.enter(id);const cfg=C.rules.guardianScaling[i],g=c.zone().enemies.find(e=>e.guard&&e.form==='normal');assert.equal(g.baseHp,Math.round((65+i*105)*cfg.hp));assert.equal(g.baseDamage,Math.round((7+i*8)*cfg.damage));assert.equal(g.xp,0);assert.equal(g.gold,0);}});
check('Dungeon guardians are materially tougher than equivalent regional field melee mobs',()=>{const baseHp=[65,170,275,380,485],baseDamage=[7,15,23,31,39];for(const [i,id]of C.dungeonIds.entries()){const c=new C();c.enter(id);const g=c.zone().enemies.find(e=>e.guard&&e.form==='normal'),fieldHp=Math.round(baseHp[i]*C.rules.ordinaryMeleeScaling[i].hp),fieldDamage=Math.round(baseDamage[i]*C.rules.ordinaryMeleeScaling[i].damage);assert(g.baseHp>=fieldHp*1.25,id+' guardian HP clearly exceeds field melee');assert(g.baseDamage>=fieldDamage*1.12,id+' guardian damage clearly exceeds field melee');assert.equal(g.guardianBalanceVersion,2);}});
check('Existing saved guardians upgrade once to the stronger v0.8.36 scaling without healing wounded guards',()=>{const c=new C();c.enter('crypt');const raw=c.snapshot(),g=raw.zones.crypt.enemies.find(e=>e.guard&&e.hp>0),legacy=C.rules.guardianLegacyScaling[0],next=C.rules.guardianScaling[0];g.baseHp=Math.round(65*legacy.hp);g.baseDamage=Math.round(7*legacy.damage);g.maxHp=g.baseHp;g.hp=g.maxHp*.4;g.damage=g.baseDamage;g.guardianBalanceVersion=1;raw.zones.crypt.guardianBalanceVersion=1;const r=C.restore(raw),u=r.zone().enemies.find(e=>e.id===g.id);assert.equal(u.baseHp,Math.round(65*next.hp));assert.equal(u.baseDamage,Math.round(7*next.damage));assert(Math.abs(u.hp/u.maxHp-.4)<1e-9);assert.equal(u.guardianBalanceVersion,2);const again=C.restore(r.snapshot()).zone().enemies.find(e=>e.id===g.id);assert.equal(again.baseHp,u.baseHp);assert.equal(again.baseDamage,u.baseDamage);});
check('Dungeon guardian streaks spawn two elite guards at the 50% branch and gate the first-clear reward',()=>{const c=new C('normal','paladin',()=>.2);c.enter('crypt');const guards=c.zone().enemies.filter(e=>e.guard),a=guards[0],b=guards.find(e=>e!==a&&e.species===a.species);kill(c,a,true);kill(c,b,true);assert.equal(c.s.pending[a.species].count,2);for(const e of c.zone().enemies.filter(e=>e.guard&&e.hp>0))kill(c,e);kill(c,c.zone().enemies.find(e=>e.type==='boss'));assert(!c.s.paid['clear:crypt']);c.updateElites(3);const elites=c.zone().enemies.filter(e=>e.form==='ringleader');assert.equal(elites.length,2);assert(elites.every(e=>e.guard));assert(elites.every(e=>e.ranged===b.ranged));elites.forEach(e=>kill(c,e));c.updateElites(.1);c.checkClear();assert(c.s.paid['clear:crypt']);});
check('Dungeon upgrade keeps dead guardians dead and adds only missing new slots; completed saves remain cleared',()=>{const c=new C();c.enter('crypt');const z=c.zone();z.enemies=z.enemies.filter(e=>!e.guard||z.enemies.filter(x=>x.guard).indexOf(e)<6);kill(c,z.enemies.find(e=>e.guard));const s=c.snapshot();delete s.zones.crypt.dungeonVersion;delete s.zones.crypt.combatVersion;s.zones.crypt.props=s.zones.crypt.props.filter(p=>!p.decorative);const r=C.restore(s);assert.equal(r.zone().enemies.filter(e=>e.guard).length,10);assert.equal(r.zone().enemies.filter(e=>e.guard&&e.hp===0).length,1);assert.equal(r.hero.gold,c.hero.gold);r.zone().enemies.filter(e=>e.guard&&e.hp>0).forEach(e=>kill(r,e));r.victory('crypt','normal');r.s.paid['clear:crypt']=true;const cleared=r.snapshot();delete cleared.zones.crypt.dungeonVersion;const done=C.restore(cleared);assert(!done.zone().enemies.some(e=>e.guard&&e.hp>0));});
check('Field goblin and skeleton variants fire aimed projectiles; reed beasts switch between spit and physical attacks',()=>{const c=new C();for(const species of ['goblin','skeleton'])assert(c.zone().enemies.some(e=>e.species===species&&e.ranged));c.enter('march');const e=c.zone().enemies.find(e=>e.species==='reedbeast'&&e.hybrid);assert(e);c.zone().enemies=[e];c.s.party=[];Object.assign(c.hero,c.safe(e.x+150,e.y));c.engage(e);const hp=c.hero.hp;c.updateEnemies(.1);assert(e.rangedAim);assert.equal(c.hero.hp,hp);for(let i=0;i<6;i++)c.updateEnemies(.1);assert(c.s.projectiles.some(p=>p.style==='spit'));c.s.projectiles=[];e.rangedAim=null;e.cd=0;Object.assign(c.hero,c.safe(e.x+40,e.y));const hp2=c.hero.hp;c.updateEnemies(.1);assert(c.hero.hp<hp2);assert(!e.rangedAim);});
check('Pure ranged enemies backpedal when crowded instead of becoming stationary turrets',()=>{const c=new C();c.enter('frontier');c.s.party=[];const e=c.zone().enemies.find(e=>e.species==='archer'&&e.ranged);assert(e);c.zone().enemies=[e];e.cd=5;Object.assign(c.hero,c.safe(e.x+55,e.y));c.engage(e);assert(c.line(e,c.hero));const before=Math.hypot(e.x-c.hero.x,e.y-c.hero.y);c.updateEnemies(.2);assert(Math.hypot(e.x-c.hero.x,e.y-c.hero.y)>before,'archer creates space');assert.equal(c.s.projectiles.length,0);});
check('March spitter projectiles impose a brief control slow without changing their damage model',()=>{const c=new C();c.enter('march');c.zone().props=[];c.s.party=[];const e=c.makeEnemy({species:'reedbeast',name:'Reed beast spitter',level:5,hp:500,damage:20,gold:0,xp:0},{x:500,y:500});Object.assign(e,C.rules.rangedProfiles.reedbeast,{ranged:true,aggro:true,cd:0});c.zone().enemies=[e];Object.assign(c.hero,{x:650,y:500,maxHp:10000,hp:10000,slow:0});e.rangedAim={x:c.hero.x,y:c.hero.y,timer:0};c.updateEnemies(.01);assert(c.s.projectiles.some(p=>p.slow===C.rules.rangedProfiles.reedbeast.projectileSlow));for(let i=0;i<40&&c.s.projectiles.length;i++)c.updateProjectiles(.05);assert(c.hero.slow>0,'spit slows on impact');});
check('Ringleader hybrids commit to melee sooner and rearm pursuit pressure after landing a hit',()=>{const c=new C();c.enter('frontier');c.s.party=[];c.zone().props=[];const e=c.zone().enemies.find(e=>e.species==='orc'&&e.hybrid);assert(e,'frontier contains an orc axe thrower');let lane=null;for(let y=300;y<3000&&!lane;y+=100)for(let x=300;x<3000&&!lane;x+=100){const a={x,y},b={x:x+85,y};if(!c.blocked(a.x,a.y)&&!c.blocked(b.x,b.y)&&c.clearSegment(a,b))lane={a,b};}assert(lane,'expanded Frontier still provides a clear short melee fixture');Object.assign(e,{...lane.a,home:{...lane.a},form:'ringleader',ringleaderHealthVersion:3,cd:0,pursuitBurstUsed:true});c.zone().enemies=[e];Object.assign(c.hero,lane.b);c.engage(e);const before=Math.hypot(e.x-c.hero.x,e.y-c.hero.y);assert(before<C.rules.rangedEnemyCombat.ringleaderHybridMeleeRange,'fixture begins inside ringleader hybrid melee switch range');c.updateEnemies(.1);assert(!e.rangedAim,'ringleader hybrid stops throwing inside its larger switch range');assert(Math.hypot(e.x-c.hero.x,e.y-c.hero.y)<before,'ringleader hybrid closes for melee');Object.assign(c.hero,{x:e.x+50,y:e.y});assert(c.clearSegment(e,c.hero),'melee contact fixture remains clear');e.cd=0;e.pursuitBurstUsed=true;const hp=c.hero.hp;c.updateEnemies(.1);assert(c.hero.hp<hp,'ringleader lands melee after closing');assert.equal(e.pursuitBurstUsed,false,'melee contact rearms the existing pursuit burst for the next escape');});
check('Melee dungeon guardians screen the hero away from a ranged packmate',()=>{const c=new C();c.enter('crypt');c.zone().props=[];const melee=c.makeEnemy({species:'skeleton',name:'Skeleton guardian',level:3,hp:500,damage:20,gold:0,xp:0},{x:500,y:500}),ranged=c.makeEnemy({species:'skeleton',name:'Skeleton bow guardian',level:3,hp:500,damage:20,gold:0,xp:0},{x:560,y:500});Object.assign(melee,{guard:true,pack:'screen-pack',aggro:true,cd:0,ranged:false});Object.assign(ranged,{guard:true,pack:'screen-pack',aggro:true,cd:99,ranged:true,shotRange:290,shotSpeed:280,projectileStyle:'arrow'});const ally=c.unit('soldier',495,500);c.s.party=[ally];c.zone().enemies=[melee,ranged];Object.assign(c.hero,{x:520,y:500,maxHp:10000,hp:10000});const heroHp=c.hero.hp,allyHp=ally.hp;c.updateEnemies(.1);assert(c.hero.hp<heroHp,'screening guardian pressures hero');assert.equal(ally.hp,allyHp,'closer companion is ignored while hero threatens ranged partner');});
check('All main-dungeon guardians and guardian ringleaders give zero gold and XP, including migrated saves',()=>{for(const id of C.dungeonIds){const c=new C('normal','paladin',()=>.9);c.enter(id);const z=c.zone(),g=z.enemies.find(e=>e.guard);assert.equal(g.xp,0);assert.equal(g.gold,0);const a=z.enemies.filter(e=>e.guard&&e.species===g.species).slice(0,2);a.forEach(e=>kill(c,e,true));c.updateElites(3);const elite=z.enemies.find(e=>e.form==='ringleader');assert(elite&&elite.guard);assert.equal(elite.xp,0);assert.equal(elite.gold,0);const snapshot=c.snapshot();snapshot.zones[id].guardRewardsVersion=1;for(const e of snapshot.zones[id].enemies.filter(e=>e.guard)){e.gold=100;e.xp=100;}const r=C.restore(snapshot);assert(r.zone().enemies.filter(e=>e.guard).every(e=>e.xp===0&&e.gold===0));assert.equal(r.hero.gold,c.hero.gold);}});
check('Bosses, guardians, guardian elites and summons are immune to every trap pulse',()=>{for(const id of C.dungeonIds){const c=new C();c.enter(id);const z=c.zone(),guard=z.enemies.find(e=>e.guard),boss=z.enemies.find(e=>e.type==='boss'),elite={...guard,id:'elite-fixture',form:'ringleader'},summon={...guard,id:'summon-fixture',summon:true,guard:false};z.enemies.push(elite,summon);const enemies=[guard,boss,elite,summon];for(const [j,t]of c.traps().entries()){Object.assign(c.hero,t);enemies.forEach(e=>Object.assign(e,t));const hp=enemies.map(e=>e.hp);const cfg=C.rules.dungeonTrapTuning[id];z.clock=(cfg.warning+.1-t.index*cfg.offset+cfg.cycle*20)%cfg.cycle;const heroHp=c.hero.hp;c.updateTraps(.1);assert(c.hero.hp<heroHp);assert.deepEqual(enemies.map(e=>e.hp),hp);assert(enemies.every(e=>!e.slow));c.hero.hp=c.hero.maxHp;}}});
check('Peace clears guard elites and deactivates every engineered trap',()=>{const c=new C();for(const id of C.dungeonIds)c.enter(id);for(const b of C.data.bosses)c.victory(b.id,'normal');for(const id of ['darklord',...C.dungeonIds])c.victory(id,'true');c.checkEnding();for(const id of C.dungeonIds){c.enter(id);assert.equal(c.traps().length,0);assert(c.zone().enemies.every(e=>e.neutral));assert(!c.zone().enemies.some(e=>e.guard));}});

check('Outdoor and guardian ringleaders use elite health and damage without increased reward multipliers',()=>{for(const zone of ['vale','crypt']){const c=new C('normal','paladin',()=>.9);c.enter(zone);const e=c.zone().enemies.find(e=>e.type==='mob'&&!e.ranged);c.streak(e);c.streak(e);c.updateElites(3);const elite=c.zone().enemies.find(e=>e.form==='ringleader');assert(elite);assert.equal(elite.baseHp,e.baseHp*C.rules.ringleaderScaling.hp);assert.equal(elite.baseDamage,e.baseDamage*C.rules.ringleaderScaling.damage);assert.equal(elite.gold,e.gold*1.5);assert.equal(elite.xp,e.xp*1.5);assert.equal(!!elite.guard,!!e.guard);}});
check('Ringleaders pursue twenty percent faster while keeping normal slows',()=>{const c=new C();c.enter('crypt');c.s.party=[];Object.assign(c.hero,{x:400,y:240});const source=c.zone().enemies.find(e=>e.guard);const distances=[];for(const form of ['normal','ringleader']){const e={...source,id:'speed-'+form,form,x:160,y:240,home:{x:160,y:240},aggro:true,ranged:false,cd:0,slow:0};c.zone().enemies=[e];assert(c.line(e,c.hero));c.updateEnemies(.1);distances.push(Math.hypot(e.x-160,e.y-240));}assert(Math.abs(distances[1]/distances[0]-C.rules.ringleaderScaling.pursuit)<1e-9);});
check('Ringleaders enter permanent Frenzy below half health and shorten their attack cadence',()=>{const c=new C('normal','paladin',()=>.9);c.enter('vale');const e=c.zone().enemies.find(e=>e.type==='mob'&&!e.ranged&&!e.guard);c.streak(e);c.streak(e);c.updateElites(3);const elite=c.zone().enemies.find(e=>e.form==='ringleader');assert(elite);c.s.party=[];Object.assign(c.hero,{x:elite.x+50,y:elite.y,maxHp:10000,hp:10000});c.engage(elite);elite.hp=elite.maxHp*.49;elite.cd=1;c.updateEnemies(.1);assert(elite.frenzy);assert(elite.cd<=.2);elite.cd=0;c.updateEnemies(.1);assert(elite.cd<=1.4*C.rules.ringleaderScaling.frenzyCooldown);});
check('Dungeon guardians reinforce after eighteen seconds to half population while a boss lives',()=>{const c=new C('normal','paladin',()=>.2);c.enter('crypt');const z=c.zone(),original=C.data.regions[0].guards,target=original/2;z.enemies.filter(e=>e.guard).slice(0,original-target+1).forEach(e=>kill(c,e));assert.equal(z.enemies.filter(e=>e.guard&&e.hp>0).length,target-1);c.updateGuardianReinforcements(17.9);assert.equal(z.enemies.filter(e=>e.guard&&e.hp>0).length,target-1);c.updateGuardianReinforcements(.2);const alive=z.enemies.filter(e=>e.guard&&e.hp>0);assert.equal(alive.length,target);const fresh=alive.filter(e=>e.reinforcement);assert.equal(fresh.length,1);assert(fresh.every(e=>e.gold===0&&e.xp===0));});
check('Guardian reinforcement groups remain bounded, pause under heavy combat and stop after the boss dies',()=>{const c=new C('normal','paladin',()=>.99);c.enter('archive');const z=c.zone(),target=C.data.regions[1].guards/2;z.enemies.filter(e=>e.guard).forEach(e=>kill(c,e));const boss=z.enemies.find(e=>e.type==='boss');boss.aggro=true;c.updateGuardianReinforcements(18.1);let fresh=z.enemies.filter(e=>e.guard&&e.hp>0&&e.reinforcement);assert(fresh.length>=1&&fresh.length<=2);z.enemies.filter(e=>e.guard&&e.hp>0).forEach(e=>{e.aggro=true;});const before=fresh.length;c.updateGuardianReinforcements(40);assert.equal(z.enemies.filter(e=>e.guard&&e.hp>0&&e.reinforcement).length,before);z.enemies.filter(e=>e.guard).forEach(e=>{e.aggro=false;});boss.hp=0;c.kill(boss);c.updateGuardianReinforcements(40);assert.equal(z.enemies.filter(e=>e.guard&&e.hp>0&&e.reinforcement).length,before);assert(z.enemies.filter(e=>e.guard&&e.hp>0).length<=target);});
check('Reinforcement guardians still participate in guardian ringleader streaks without farm rewards',()=>{const c=new C('normal','paladin',()=>.2);c.enter('crypt');const z=c.zone();z.enemies.filter(e=>e.guard).forEach(e=>kill(c,e));c.updateGuardianReinforcements(18.1);const fresh=z.enemies.filter(e=>e.guard&&e.hp>0&&e.reinforcement);assert.equal(fresh.length,2);const source=fresh[0];c.streak(source);c.streak(source);assert(c.s.pending[source.species]);c.updateElites(3);const leaders=z.enemies.filter(e=>e.guard&&e.form==='ringleader'&&e.reinforcement);assert.equal(leaders.length,2);assert(leaders.every(e=>e.species===source.species&&e.gold===0&&e.xp===0));});
check('Awakening guardians and reinforcements match the TRUE boss level and use awakened stats',()=>{const c=new C('normal','paladin',()=>.2);c.s.normal.crypt=true;c.s.phase='awakening';c.s.awakeningLevel=21;c.s.pending.crypt={kind:'dungeon',count:1};c.enter('crypt');const z=c.zone(),boss=z.enemies.find(e=>e.type==='boss'&&e.form==='true'),g=z.enemies.find(e=>e.guard&&e.awakenedGuard),cfg=C.rules.guardianScaling[0],aw=C.rules.awakenedGuardianScaling;assert.equal(boss.level,21);assert.equal(g.level,boss.level);assert.equal(g.baseHp,Math.round(Math.round((120+35*21)*aw.hp)*cfg.hp));assert.equal(g.baseDamage,Math.round(Math.round((12+21)*aw.damage)*cfg.damage));assert.equal(g.gold,0);assert.equal(g.xp,0);z.enemies.filter(e=>e.guard).forEach(e=>kill(c,e));c.updateGuardianReinforcements(18.1);const reinforcements=z.enemies.filter(e=>e.guard&&e.hp>0&&e.reinforcement);assert(reinforcements.length>=1);assert(reinforcements.every(e=>e.awakenedGuard&&e.level===boss.level&&e.gold===0&&e.xp===0));});
check('Legacy ringleaders upgrade once and retain wounded/dead status across reloads',()=>{const c=new C('normal','paladin',()=>.2);c.enter('crypt');const g=c.zone().enemies.find(e=>e.guard);c.streak(g);c.streak(g);c.updateElites(3);const old=c.snapshot(),elites=old.zones.crypt.enemies.filter(e=>e.form==='ringleader');for(const [i,e]of elites.entries()){e.ringleaderHealthVersion=2;e.baseHp/=1.25;e.baseDamage/=1.2;e.maxHp=e.baseHp*2;e.hp=i?0:e.maxHp*.4;}const r=C.restore(old),actual=r.zone().enemies.filter(e=>e.form==='ringleader');assert.equal(actual[0].ringleaderHealthVersion,3);assert.equal(actual[0].hp/actual[0].maxHp,.4);assert.equal(actual[1].hp,0);const again=C.restore(JSON.parse(JSON.stringify(r.s))).zone().enemies.filter(e=>e.form==='ringleader');assert.deepEqual(again.map(e=>[e.baseHp,e.baseDamage,e.maxHp,e.hp]),actual.map(e=>[e.baseHp,e.baseDamage,e.maxHp,e.hp]));});
console.log(n+' dungeon pressure and ranged-variant checks passed.');
