'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine');let n=0;
function check(name,fn){fn();n++;console.log('PASS '+name);}
const kill=(c,e,hero=false)=>{e.heroParticipated=hero;e.hp=0;c.kill(e);};
for(const [i,id]of C.dungeonIds.entries())check(id+' added guards/decor/traps preserve safe routes and readable single-hit pulses',()=>{const c=new C();c.enter(id);const z=c.zone(),traps=c.traps();assert.equal(z.enemies.filter(e=>e.guard).length,[10,14,18,22,26][i]);assert.equal(z.props.filter(p=>p.decorative).length,16);assert(traps.length>=6);assert(traps.filter(t=>Math.hypot(t.x-1160,t.y-1110)<300).length>=2);const original=c.blocked.bind(c);c.blocked=(x,y,zone,r=15,terrain)=>original(x,y,zone,r,terrain)||traps.some(t=>c.trapContains({...t,radius:t.radius+r,length:t.length+2*r},{x,y}));assert(c.route(c.hero,z.enemies.find(e=>e.type==='boss')).length);assert(c.route(c.hero,z.npcs.find(e=>e.kind==='cage')).length);c.blocked=original;c.s.party=[];const first=c.traps()[0];Object.assign(c.hero,first);z.clock=1;let hp=c.hero.hp;c.updateTraps(.1);assert.equal(c.hero.hp,hp);z.clock=1.6;c.updateTraps(.1);assert(c.hero.hp<hp);hp=c.hero.hp;c.updateTraps(.1);assert.equal(c.hero.hp,hp);assert(c.hero.hp>0);});
check('Dungeon guardian streaks spawn two elite guards at the 50% branch and gate the first-clear reward',()=>{const c=new C('normal','paladin',()=>.2);c.enter('crypt');const guards=c.zone().enemies.filter(e=>e.guard),a=guards[0],b=guards.find(e=>e!==a&&e.species===a.species);kill(c,a,true);kill(c,b,true);assert.equal(c.s.pending[a.species].count,2);for(const e of c.zone().enemies.filter(e=>e.guard&&e.hp>0))kill(c,e);kill(c,c.zone().enemies.find(e=>e.type==='boss'));assert(!c.s.paid['clear:crypt']);c.updateElites(3);const elites=c.zone().enemies.filter(e=>e.form==='ringleader');assert.equal(elites.length,2);assert(elites.every(e=>e.guard));assert(elites.every(e=>e.ranged===b.ranged));elites.forEach(e=>kill(c,e));c.updateElites(.1);c.checkClear();assert(c.s.paid['clear:crypt']);});
check('Dungeon upgrade keeps dead guardians dead and adds only missing new slots; completed saves remain cleared',()=>{const c=new C();c.enter('crypt');const z=c.zone();z.enemies=z.enemies.filter(e=>!e.guard||z.enemies.filter(x=>x.guard).indexOf(e)<6);kill(c,z.enemies.find(e=>e.guard));const s=c.snapshot();delete s.zones.crypt.dungeonVersion;delete s.zones.crypt.combatVersion;s.zones.crypt.props=s.zones.crypt.props.filter(p=>!p.decorative);const r=C.restore(s);assert.equal(r.zone().enemies.filter(e=>e.guard).length,10);assert.equal(r.zone().enemies.filter(e=>e.guard&&e.hp===0).length,1);assert.equal(r.hero.gold,c.hero.gold);r.zone().enemies.filter(e=>e.guard&&e.hp>0).forEach(e=>kill(r,e));r.victory('crypt','normal');r.s.paid['clear:crypt']=true;const cleared=r.snapshot();delete cleared.zones.crypt.dungeonVersion;const done=C.restore(cleared);assert(!done.zone().enemies.some(e=>e.guard&&e.hp>0));});
check('Field goblin and skeleton variants fire aimed projectiles; reed beasts switch between spit and physical attacks',()=>{const c=new C();for(const species of ['goblin','skeleton'])assert(c.zone().enemies.some(e=>e.species===species&&e.ranged));c.enter('march');const e=c.zone().enemies.find(e=>e.species==='reedbeast'&&e.hybrid);assert(e);c.zone().enemies=[e];c.s.party=[];Object.assign(c.hero,c.safe(e.x+150,e.y));c.engage(e);const hp=c.hero.hp;c.updateEnemies(.1);assert(e.rangedAim);assert.equal(c.hero.hp,hp);for(let i=0;i<6;i++)c.updateEnemies(.1);assert(c.s.projectiles.some(p=>p.style==='spit'));c.s.projectiles=[];e.rangedAim=null;e.cd=0;Object.assign(c.hero,c.safe(e.x+40,e.y));const hp2=c.hero.hp;c.updateEnemies(.1);assert(c.hero.hp<hp2);assert(!e.rangedAim);});
check('Guardian and guardian-ringleader rewards are sharply lower than outdoor enemies and migrate safely',()=>{for(const [i,id]of C.dungeonIds.entries()){const c=new C('normal','paladin',()=>.9);c.enter(id);const z=c.zone(),g=z.enemies.find(e=>e.guard),region=C.data.regions[i];assert(g.xp<=region.enemy_xp*.25);assert(g.gold<=Math.floor((region.gold_range[0]+region.gold_range[1])/2*.35));const a=z.enemies.filter(e=>e.guard&&e.species===g.species).slice(0,2);a.forEach(e=>kill(c,e,true));c.updateElites(3);const elite=z.enemies.find(e=>e.form==='ringleader');assert(elite&&elite.guard);assert(elite.xp<region.enemy_xp*.5);assert(elite.gold<region.gold_range[0]);const snapshot=c.snapshot();delete snapshot.zones[id].guardRewardsVersion;for(const e of snapshot.zones[id].enemies.filter(e=>e.guard)){e.gold=100;e.xp=100;}const r=C.restore(snapshot);assert(r.zone().enemies.filter(e=>e.guard).every(e=>e.xp<region.enemy_xp*.5));assert.equal(r.hero.gold,c.hero.gold);}});
check('Bosses, guardians, guardian elites and summons are immune to every trap pulse',()=>{for(const id of C.dungeonIds){const c=new C();c.enter(id);const z=c.zone(),guard=z.enemies.find(e=>e.guard),boss=z.enemies.find(e=>e.type==='boss'),elite={...guard,id:'elite-fixture',form:'ringleader'},summon={...guard,id:'summon-fixture',summon:true,guard:false};z.enemies.push(elite,summon);const enemies=[guard,boss,elite,summon];for(const [j,t]of c.traps().entries()){Object.assign(c.hero,t);enemies.forEach(e=>Object.assign(e,t));const hp=enemies.map(e=>e.hp);z.clock=(1.6-j*1.35+80)%8;const heroHp=c.hero.hp;c.updateTraps(.1);assert(c.hero.hp<heroHp);assert.deepEqual(enemies.map(e=>e.hp),hp);assert(enemies.every(e=>!e.slow));c.hero.hp=c.hero.maxHp;}}});
check('Peace clears guard elites and deactivates every engineered trap',()=>{const c=new C();for(const id of C.dungeonIds)c.enter(id);for(const b of C.data.bosses)c.victory(b.id,'normal');for(const id of ['darklord',...C.dungeonIds])c.victory(id,'true');c.checkEnding();for(const id of C.dungeonIds){c.enter(id);assert.equal(c.traps().length,0);assert(c.zone().enemies.every(e=>e.neutral));assert(!c.zone().enemies.some(e=>e.guard));}});
console.log(n+' dungeon pressure and ranged-variant checks passed.');
