'use strict';
const assert = require('node:assert/strict');
const Input = require('../src/prototype/input');
const C = require('../src/prototype/engine');
const items = new Map();
const storage = { getItem: k => items.get(k), setItem: (k,v) => items.set(k,v) };
let controls = Input.create(storage);
assert.equal(controls.preferences.phoneLayout, 'two-thumb');
assert.equal(controls.preferences.touchMove, true);
assert.equal(controls.preferences.mouseMove, false);
assert(controls.rebind('up','KeyS').includes('already used'));
assert.equal(controls.actionFor('KeyW'),'up');
assert(controls.rebind('up','Escape'));
assert.equal(controls.rebind('up','ArrowUp'),null);
assert.equal(controls.actionFor('ArrowUp'),'up');
assert.equal(controls.actionFor('KeyW'),null);
assert.equal(controls.rebind('inventory','KeyQ'),null);
assert.equal(controls.actionFor('KeyR'),null,'old aliases stop applying to rebound actions');
assert.equal(controls.rebind('skill1','KeyR'),null,'unused alias can become an explicit binding');
assert.equal(controls.actionFor('KeyR'),'skill1');
controls.select('phoneLayout','left-hand');controls.select('touchMove',false);controls.select('mouseMove',true);
controls=Input.create(storage);
assert.equal(controls.actionFor('ArrowUp'),'up');
assert.equal(controls.actionFor('KeyQ'),'inventory');
assert.equal(controls.preferences.phoneLayout,'left-hand');
assert.equal(controls.preferences.touchMove,false);
assert.equal(controls.preferences.mouseMove,true);
controls.resetBindings();assert.equal(controls.actionFor('KeyW'),'up');assert.equal(controls.actionFor('KeyR'),'inventory');
items.set(Input.preferenceKey,JSON.stringify({bindings:{up:'KeyS'}}));
assert.equal(Input.create(storage).actionFor('KeyW'),'up','duplicate persisted bindings fall back safely');
items.set(Input.preferenceKey,'broken JSON');assert.equal(Input.create(storage).actionFor('KeyW'),'up');
let warning='';const session=Input.create({getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}},s=>warning=s);
assert.equal(session.rebind('up','ArrowUp'),null);assert.equal(session.actionFor('ArrowUp'),'up');assert(warning);
console.log('PASS rebinding conflicts, persistence, reset, aliases, invalid preferences and unavailable storage');
const c=new C('normal','paladin',()=>.9),initial=c.snapshot();
assert.equal(Input.requestMove(c,{x:-1,y:10}),false);assert(!c.hero.order);
assert.equal(Input.requestMove(c,{x:Infinity,y:10}),false);
const target=c.safe(c.hero.x+120,c.hero.y+80);
assert(Input.requestMove(c,target));assert.equal(c.hero.order.type,'move');
const start={x:c.hero.x,y:c.hero.y};c.tick(.05,{x:1,y:0});assert.equal(c.hero.order,null,'directional movement immediately takes control');
assert(c.hero.x>start.x);assert.equal(c.s.statistics.deaths,initial.statistics.deaths);
assert.equal(c.hero.gold,initial.hero.gold,'input preference changes do not alter currency');
console.log('PASS bounded tap destinations and manual takeover preserve campaign rules');
