'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine');
const fresh=()=>new C('normal','paladin',()=>.9),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const kill=(c,e)=>{e.hp=0;e.heroParticipated=true;c.kill(e);};
let passed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){process.exitCode=1;console.error('FAIL '+name+' '+e.stack);}}
for(const r of C.data.regions)test(r.id+' quests: physical objectives, saved progress and one payment',()=>{
 const c=fresh();c.enter(r.id);const qs=c.questDefs().filter(q=>q.region===r.id);qs.forEach(q=>c.accept(q.id));
 for(const q of qs){const c=fresh();c.enter(r.id);c.accept(q.id);assert(!c.s.quests[q.id].done);
  if(q.kind==='rescue'){const b=c.boss(q.target);c.enter(b.kind==='dungeon'?b.id:r.id);const e=c.zone().enemies.find(e=>e.family===b.id);kill(c,e);const n=c.zone().npcs.find(n=>n.kind==='cage'&&n.family===b.id);Object.assign(c.hero,n);assert(c.interact(n));c.enter(r.id);}
  else if(q.kind==='patrol'){const es=c.zone().enemies.filter(e=>e.type==='mob'&&!e.nightOnly&&e.hp>0).slice(0,q.target);assert.equal(es.length,q.target);es.forEach(e=>kill(c,e));}
  else if(q.kind==='bundles'){const bundles=c.zone().npcs.filter(n=>n.kind==='bundle');assert.equal(bundles.length,3);for(const n of bundles){Object.assign(c.hero,{x:n.x,y:n.y});assert(c.interact(n));assert(!c.visibleNPCs().includes(n));assert(!c.interact(n));}assert(c.questProgress(q).includes('Complete'));}
  else if(q.kind==='sites'){for(const id of q.sites){if(id==='port'){Object.assign(c.hero,{x:C.data.ports[c.regionIndex()][0],y:C.data.ports[c.regionIndex()][1]});c.tick(.01);}else if(id==='minor'){const n=c.zone().npcs.find(n=>n.id===id);Object.assign(c.hero,{x:n.x,y:n.y});c.tick(.01);}else{const n=c.zone().npcs.find(n=>n.id===id);Object.assign(c.hero,{x:n.x,y:n.y});assert(c.interact(n));}}}
  else if(q.kind==='night'){const n=c.zone().npcs.find(n=>n.id==='night-site');c.s.clock=0;Object.assign(c.hero,{x:n.x,y:n.y});c.interact(n);assert(!c.s.discovered[r.id+':night-site']);c.s.clock=500;c.updateNight();c.interact(n);const es=c.zone().enemies.filter(e=>e.nightOnly&&e.species==='wraith').slice(0,2);es.forEach(e=>kill(c,e));}
  else if(q.kind==='escort'){const z=c.zone();z.enemies.forEach(e=>e.hp=0);c.updateEscort(.1);for(let t=0;t<2000&&!c.s.quests[q.id].done;t++){if(z.escort)Object.assign(c.hero,{x:z.escort.x,y:z.escort.y});c.updateEscort(.1);}assert(!z.escort);}
  assert(c.s.quests[q.id].done,q.name);const restored=C.restore(c.snapshot());assert(restored.s.quests[q.id].done);const gold=c.hero.gold;assert(c.claim(q.id));assert.equal(c.hero.gold,gold+q.gold);assert(!c.claim(q.id));
 }
});
test('Outdoor patrol objectives exclude dungeon kills and inactive kills',()=>{const c=fresh(),q='quest-1';kill(c,c.zone().enemies.find(e=>e.type==='mob'));c.accept(q);assert.equal(c.s.quests[q].count,0);c.enter('crypt');kill(c,c.zone().enemies.find(e=>e.guard));assert.equal(c.s.quests[q].count,0);c.enter('vale');kill(c,c.zone().enemies.find(e=>e.type==='mob'&&e.hp>0));assert.equal(c.s.quests[q].count,1);});
test('Each resource and cache is reachable, outside both refuges and protected by a local patrol',()=>{for(const [i,r] of C.data.regions.entries()){const c=fresh();c.enter(r.id);const z=c.zone(),node=z.nodes[0];assert.equal(node.amount,r.resource);assert(c.route(c.hero,node).length);for(const n of [node,...z.npcs.filter(n=>n.kind==='bundle')]){assert([C.data.towns[i],C.data.minors[i]].every(([x,y])=>distance(n,{x,y})>=300));assert(c.route(c.hero,n).length,r.id+' '+n.name);assert(z.enemies.some(e=>e.site===n.site&&distance(e,n)<200&&c.line(e,n)),r.id+' '+n.name+' undefended');}if(i===3)assert(!z.npcs.some(n=>n.kind==='bundle'));for(const n of z.npcs.filter(n=>n.kind==='landmark'))assert(c.siteDescription(n).length>n.name.length+30);}});
test('Worker can be attacked at the deposit; clearing it enables repeated finite round trips',()=>{const c=fresh(),z=c.zone(),n=z.nodes[0],u=c.s.party.find(u=>u.type==='worker');c.s.party=[u];Object.assign(u,{x:n.x,y:n.y});u.order={type:'wait'};const guards=z.enemies.filter(e=>e.site===n.site);guards.forEach(e=>c.engage(e));const before=u.hp;for(let t=0;t<30;t++)c.updateEnemies(.1);assert(u.hp<before,'deposit has no threat');z.enemies.forEach(e=>e.hp=0);u.hp=u.maxHp;n.amount=76;const gold=c.hero.gold;assert(c.gather(n.id));for(let t=0;t<8000&&(n.amount>0||u.carry>.001||u.order);t++)c.updateParty(.1);assert.equal(n.amount,0);assert(Math.abs(u.carry)<1e-6);assert.equal(c.hero.gold,gold+76);assert(!c.gather(n.id));});
test('Site migration preserves depleted resources, enemy deaths, paid quests and collection',()=>{const c=fresh();c.enter('crown');const z=c.zone();z.nodes[0].amount=137;const e=z.enemies.find(e=>e.site);e.hp=0;e.deathPaid=true;c.s.discovered['crown:bundle-0']=true;c.s.quests['quest-24']={active:true,count:0,done:true,paid:true};const s=c.snapshot();delete s.zones.crown.localSitesVersion;Object.assign(s.zones.crown.nodes[0],{x:600,y:760});const restored=C.restore(s);assert.equal(restored.zone().nodes[0].amount,137);assert.equal(restored.zone().enemies.find(a=>a.id===e.id).hp,0);assert(restored.s.quests['quest-24'].paid);assert(!restored.visibleNPCs().some(n=>n.id==='bundle-0'));const next=C.restore(restored.snapshot());assert.deepEqual(next.zone().nodes,restored.zone().nodes);});
test('Escort takes aimed projectiles and area damage; failure retries without completing',()=>{const c=fresh();c.enter('frontier');c.accept('quest-19');c.zone().props=[];c.zone().escort={id:'supply-escort',x:1000,y:800,hp:250,maxHp:250};const n=c.zone().escort,e=c.zone().enemies.find(e=>e.type==='boss');Object.assign(e,{x:900,y:800});Object.assign(c.hero,{x:450,y:500});c.s.party=[];c.s.projectiles=[{source:'enemy',x:960,y:800,dx:1,dy:0,speed:400,life:2,damage:30}];c.updateProjectiles(.1);assert(n.hp<250);const hp=n.hp;c.resolveArea(e,{kind:'circle',x:n.x,y:n.y,radius:80,coefficient:1,fromX:e.x,fromY:e.y});assert(n.hp<hp);n.hp=0;c.updateEscort(.1);assert.equal(c.zone().escort.hp,250);assert(!c.s.quests['quest-19'].done);});
console.log(passed+' local quest and expedition scenarios passed.');
