'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine');
const fresh=()=>new C('normal','paladin',()=>.9),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const kill=(c,e)=>{e.hp=0;e.heroParticipated=true;c.kill(e);};
let passed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){process.exitCode=1;console.error('FAIL '+name+' '+e.stack);}}
for(const r of C.data.regions)test(r.id+' quests: physical objectives, automatic activation and automatic payment',()=>{
 const c=fresh();c.enter(r.id);const qs=c.questDefs().filter(q=>q.region===r.id);assert(qs.every(q=>c.s.quests[q.id]?.active));
 for(const q of qs){const c=fresh();c.enter(r.id);assert(c.s.quests[q.id].active&&!c.s.quests[q.id].done);
  if(q.kind==='rescue'){const b=c.boss(q.target);c.enter(b.kind==='dungeon'?b.id:r.id);const e=c.zone().enemies.find(e=>e.family===b.id);kill(c,e);const n=c.zone().npcs.find(n=>n.kind==='cage'&&n.family===b.id);Object.assign(c.hero,n);assert(c.interact(n));if(q.clear)for(const g of c.zone().enemies.filter(e=>e.mini===q.clear)){g.hp=0;g.heroParticipated=false;c.kill(g);}c.enter(r.id);}
  else if(q.kind==='patrol'){const es=c.zone().enemies.filter(e=>e.type==='mob'&&!e.guard&&!e.nightOnly&&e.hp>0).slice(0,q.target);assert.equal(es.length,q.target);es.forEach(e=>kill(c,e));}
  else if(q.kind==='bundles'){assert.equal(c.zone().npcs.filter(n=>n.kind==='bundle').length,0,q.region+' has no Treasury quest caches outdoors');const entrance=c.zone().npcs.find(n=>n.id==='supply-entrance');assert(entrance);Object.assign(c.hero,entrance);assert(c.interact(entrance));const room=c.zone(),bundles=room.npcs.filter(n=>n.kind==='bundle');assert.equal(bundles.length,q.target,q.region+' Treasury physically contains the authored quest total');assert.equal(room.enemies.filter(e=>e.guard).length,4);assert.equal(c.questProgress(q),'0/'+q.target+' supplies recovered');Object.assign(c.hero,bundles[0]);assert(!c.interact(bundles[0]),'guards protect Treasury caches');for(const e of room.enemies.filter(e=>e.guard)){e.hp=0;e.heroParticipated=false;c.kill(e);}for(let j=0;j<bundles.length;j++){const b=bundles[j];Object.assign(c.hero,b);assert(c.interact(b));assert(!c.visibleNPCs().includes(b));assert(!c.interact(b));if(j<bundles.length-1)assert.equal(c.questProgress(q),(j+1)+'/'+q.target+' supplies recovered');}assert(c.questProgress(q).includes('Complete'));const exit=room.npcs.find(n=>n.kind==='exit');Object.assign(c.hero,exit);assert(c.interact(exit));assert.equal(c.zoneId,r.id);}
  else if(q.kind==='sites'){for(const family of q.requiresRescues||[])c.s.rescued[family]=true;for(const id of q.sites){if(id==='port'){Object.assign(c.hero,{x:C.data.ports[c.regionIndex()][0],y:C.data.ports[c.regionIndex()][1]});c.tick(.01);}else if(id==='minor'){const n=c.zone().npcs.find(n=>n.id===id);Object.assign(c.hero,{x:n.x,y:n.y});c.tick(.01);}else{const n=c.zone().npcs.find(n=>n.id===id);Object.assign(c.hero,{x:n.x,y:n.y});assert(c.interact(n));if(n.sideDungeon){const exit=c.zone().npcs.find(x=>x.kind==='exit');Object.assign(c.hero,exit);assert(c.interact(exit));}}}}
  else if(q.kind==='night'){const n=c.zone().npcs.find(n=>n.id==='night-site');c.s.clock=0;Object.assign(c.hero,{x:n.x,y:n.y});c.interact(n);assert(!c.s.discovered[r.id+':night-site']);c.s.clock=500;c.updateNight();c.interact(n);const es=c.zone().enemies.filter(e=>e.nightOnly&&e.species==='wraith').slice(0,2);es.forEach(e=>kill(c,e));}
  else if(q.kind==='escort'){const z=c.zone();z.enemies.forEach(e=>e.hp=0);c.updateEscort(.1);for(let t=0;t<2000&&!c.s.quests[q.id].done;t++){if(z.escort)Object.assign(c.hero,{x:z.escort.x,y:z.escort.y});c.updateEscort(.1);}assert(!z.escort);}
  else if(q.kind==='barracks'){assert.equal(c.barracksBuildCost(),0);assert(c.build());for(let t=0;t<100&&!c.s.quests[q.id].done;t++)c.updateParty(.1);assert(c.hasCompletedBarracks());}
  assert(c.s.quests[q.id].done,q.name);assert(c.s.quests[q.id].paid,q.name+' reward auto-paid');const restored=C.restore(c.snapshot());assert(restored.s.quests[q.id].done&&restored.s.quests[q.id].paid);assert(!c.claim(q.id));
 }
});
test('Outdoor patrol objectives are active from the start and exclude dungeon kills',()=>{const c=fresh(),q='quest-1';assert(c.s.quests[q].active);kill(c,c.zone().enemies.find(e=>e.type==='mob'&&!e.guard));assert.equal(c.s.quests[q].count,1);c.enter('crypt');kill(c,c.zone().enemies.find(e=>e.guard));assert.equal(c.s.quests[q].count,1);c.enter('vale');kill(c,c.zone().enemies.find(e=>e.type==='mob'&&!e.guard&&e.hp>0));assert.equal(c.s.quests[q].count,2);});
test('Every biome contains four outdoor Dark Lord Tribute sources totaling 640 gold without a resource mini-fort',()=>{for(const [i,r] of C.data.regions.entries()){const c=fresh();c.enter(r.id);const z=c.zone(),nodes=z.nodes;assert.equal(r.resource,640);assert.equal(nodes.length,4,r.id+' tribute source count');assert.equal(nodes.reduce((sum,n)=>sum+n.amount,0),640,r.id+' tribute total');assert(nodes.every(n=>n.tribute&&n.resourceGroup==='tribute-'+r.id&&!n.mini));assert.equal(nodes.filter(n=>n.hidden).length,2,r.id+' hidden source count');assert.equal(c.visibleResourceNodes().length,2,r.id+' only obvious sources initially exposed');assert(!z.minis.some(m=>m.type==='resource'),r.id+' old resource mini-fort removed');assert(!z.npcs.some(n=>n.kind==='mini'&&n.mini==='resource-'+r.id));for(const n of nodes){assert([C.data.towns[i],C.data.minors[i]].every(([x,y])=>distance(n,{x,y})>=250),r.id+' tribute inside refuge');assert(c.route(c.hero,n).length,r.id+' tribute unreachable');}assert(new Set(nodes.map(n=>n.id)).size===4);}});

test('Barracks scouting reveals hidden tribute one location at a time without exposing exact value on the site',()=>{const c=fresh();c.s.rescued.thorn=true;c.trainExpedition('thorn');const hidden=c.hiddenTributeNodes();assert.equal(hidden.length,2);const first=hidden[0],site=c.zone().npcs.find(n=>n.id===first.site);assert(!c.visibleResourceNodes().includes(first));assert(c.scoutTribute());assert(c.visibleResourceNodes().some(n=>n.id===first.id));assert.equal(c.hiddenTributeNodes().length,1);const description=c.siteDescription(site);assert(description.includes('Dark Lord Tribute has been located here'));assert(!description.includes(String(Math.floor(first.amount))+' left'));assert(c.scoutTribute());assert.equal(c.hiddenTributeNodes().length,0);assert(!c.scoutTribute());});

test('Assigned troops recover only known tribute and continue through known sources automatically',()=>{const c=fresh(),z=c.zone(),u=c.s.party[0];c.s.rescued.thorn=true;c.trainExpedition('thorn');c.s.party=[u];z.enemies.forEach(e=>e.hp=0);const visible=c.visibleResourceNodes(),hidden=c.hiddenTributeNodes();for(const n of z.nodes)n.amount=0;visible[0].amount=38;visible[1].amount=38;hidden[0].amount=38;const gold=c.hero.gold;Object.assign(u,{x:visible[0].x,y:visible[0].y});u.order=null;assert(c.gather(visible[0].id));for(let t=0;t<12000&&(visible.some(x=>x.amount>0)||u.carry>.001||u.order);t++)c.updateParty(.1);assert.equal(visible[0].amount+visible[1].amount,0);assert.equal(hidden[0].amount,38,'undiscovered tribute is never auto-selected');assert.equal(c.hero.gold,gold+76);assert(c.scoutTribute());Object.assign(u,{x:hidden[0].x,y:hidden[0].y});u.order=null;assert(c.gather(hidden[0].id));for(let t=0;t<6000&&(hidden[0].amount>0||u.carry>.001||u.order);t++)c.updateParty(.1);assert.equal(hidden[0].amount,0);assert.equal(c.hero.gold,gold+114);});

test('Legacy gathering progress becomes credit against the new 640-gold regional tribute pool',()=>{const c=fresh();c.enter('crown');c.s.gathered.crown=137;const snap=c.snapshot(),rz=snap.zones.crown;rz.nodes=[{id:'gather-crown',x:600,y:760,amount:999,icon:'💎'}];delete rz.resourceDepositsVersion;delete rz.resourceMiniRetiredVersion;const restored=C.restore(snap);assert.equal(restored.zone().nodes.length,4);assert.equal(restored.zone().nodes.reduce((sum,n)=>sum+n.amount,0),503,'640 minus already gathered value');assert(restored.zone().nodes.every(n=>n.tribute&&!n.mini));const next=C.restore(restored.snapshot());assert.deepEqual(next.zone().nodes,restored.zone().nodes);});

test('Five consolidated occupied side interiors have traps, lived-in regional decor, ordinary mobs and no gathering nodes or boss slot',()=>{for(const cfg of C.rules.sideDungeons){const c=fresh();c.enter(cfg.region);const entrance=c.zone().npcs.find(n=>n.family===cfg.id);assert(entrance&&entrance.sideDungeon);Object.assign(c.hero,entrance);assert(c.interact(entrance));assert.equal(c.zoneId,cfg.id);assert.equal(c.zone().nodes.length,0);assert(!c.zone().npcs.some(n=>n.kind==='cage'));assert(!c.zone().enemies.some(e=>e.type==='boss'));assert.equal(c.zone().enemies.filter(e=>e.hp>0).length,cfg.enemyCount);assert(c.zone().props.filter(p=>String(p.id).startsWith('side-decor-')).length>=8);assert(c.traps().length>=3);const exit=c.zone().npcs.find(n=>n.kind==='exit');Object.assign(c.hero,exit);assert(c.interact(exit));assert.equal(c.zoneId,cfg.region);}});

test('Treasury entrances are reachable and legacy outdoor-crate progress migrates inside without loss',()=>{for(const room of C.rules.supplyRooms){const c=fresh();c.enter(room.region);const old=c.snapshot(),z=old.zones[room.region],entrance=z.npcs.find(n=>n.id==='supply-entrance');assert.equal(z.npcs.filter(n=>n.kind==='bundle').length,0);assert(c.route(c.hero,entrance).length,room.name+' entrance');const field=c.fieldCenter(c.regionIndex(room.region));assert(distance(entrance,field)<380,room.id+' Treasury belongs to field-boss territory');const board=z.npcs.find(n=>n.kind==='quests');assert(distance(board,z.npcs.find(n=>n.kind==='rest'&&n.id==='rest'))>150);assert(distance(board,z.npcs.find(n=>n.kind==='supplier'))>115);z.supplyRoomVersion=2;z.npcs.push({id:'bundle-0',kind:'bundle',index:0,x:entrance.x+20,y:entrance.y+20,name:'Legacy outdoor crate'});old.discovered[room.region+':bundle-0']=true;const restored=C.restore(old);assert.equal(restored.s.zones[room.region].npcs.filter(n=>n.kind==='bundle').length,0,room.id+' removes legacy outdoor crate');restored.enter(room.id);const inside=restored.zone().npcs.filter(n=>n.kind==='bundle');assert.equal(inside.length,room.count);assert.equal(restored.visibleNPCs().filter(n=>n.kind==='bundle').length,room.count-1,room.id+' preserves one collected item as inside progress');assert.equal(restored.questProgress(restored.questDefs().find(q=>q.region===room.region&&q.kind==='bundles')),'1/'+room.count+' supplies recovered');}});
test('Field-boss Treasuries are named homes with authored furnishings and migrate old storehouse saves in place',()=>{for(const room of C.rules.supplyRooms){const c=fresh();c.enter(room.region);let z=c.zone(),entrance=z.npcs.find(n=>n.id==='supply-entrance');assert(entrance&&entrance.treasury&&entrance.treasuryBoss===room.boss,room.id+' themed entrance');assert.equal(entrance.name,room.name);assert(room.name.includes(C.data.bosses.find(b=>b.id===room.boss).name),room.id+' named for field boss');c.enter(room.id);z=c.zone();assert.equal(z.treasury,room.boss);const furnishings=z.props.filter(p=>String(p.id).startsWith('treasury-'));assert.equal(furnishings.length,C.rules.treasuryDecor[room.id].length,room.id+' complete furnishing set');assert(new Set(furnishings.map(p=>p.structure)).size>=5,room.id+' lived-in variety');assert(!z.props.some(p=>/^room-(pillar|crate)-/.test(String(p.id))),room.id+' generic mini-dungeon props removed');for(const n of z.npcs.filter(n=>n.kind==='bundle'))assert(c.route(c.hero,n).length,room.id+' cache reachable around furniture');const raw=c.snapshot(),rz=raw.zones[room.id],outer=raw.zones[room.region],oldEntrance=outer.npcs.find(n=>n.id==='supply-entrance');delete rz.treasury;delete rz.treasuryVersion;rz.props=rz.props.filter(p=>!String(p.id).startsWith('treasury-'));rz.props.push({id:'room-pillar-old',x:275,y:480,r:27,structure:'pillar',icon:'🪨'},{id:'room-crate-old',x:575,y:330,r:0,decorative:true,structure:'crate',icon:'📦'});rz.npcs.find(n=>n.id==='exit').name='Return to old storehouse';for(const n of rz.npcs.filter(n=>n.kind==='bundle'))n.name='Old storehouse supplies '+n.index;outer.supplyRoomVersion=1;oldEntrance.name='Old storehouse';delete oldEntrance.treasury;delete oldEntrance.treasuryBoss;for(const e of rz.enemies.filter(e=>e.roomGuard&&!e.roomCaptain))e.name=e.name.replace(/ treasury guard/i,' store guard');const restored=C.restore(raw);const restoredRoom=restored.s.zones[room.id],restoredEntrance=restored.s.zones[room.region].npcs.find(n=>n.id==='supply-entrance');assert.equal(restoredEntrance.name,room.name,room.id+' old entrance renamed');assert(restoredEntrance.treasury&&restoredEntrance.treasuryBoss===room.boss);assert.equal(restoredRoom.treasury,room.boss);assert(restoredRoom.props.some(p=>String(p.id).startsWith('treasury-')));assert(!restoredRoom.props.some(p=>/^room-(pillar|crate)-/.test(String(p.id))));assert(restoredRoom.enemies.filter(e=>e.roomGuard&&!e.roomCaptain).every(e=>/ treasury guard/i.test(e.name)),room.id+' old guards renamed');}});
test('Frontier supply quest is route reconnaissance and stale escort NPCs are retired',()=>{const c=fresh();const q=c.questDefs().find(q=>q.id==='quest-19');assert.equal(q.kind,'sites');assert.deepEqual(q.sites,['convoy','bridge-north','checkpoint']);c.enter('frontier');c.zone().escort={id:'supply-escort',x:1000,y:800,hp:1,maxHp:250};c.updateEscort(.1);assert.equal(c.zone().escort,undefined);for(const id of q.sites)c.discover(id);assert(c.s.quests[q.id].done&&c.s.quests[q.id].paid);});
test('Warlord compound is the single player-facing checkpoint while the old checkpoint name survives only as a quest trigger',()=>{const c=fresh();c.enter('frontier');const hidden=c.zone().npcs.find(n=>n.id==='checkpoint'),compound=c.zone().npcs.find(n=>n.kind==='mini'&&n.mini==='field-warlord');assert(hidden&&hidden.internalSite);assert(compound&&compound.name==='Warlord checkpoint');assert(!c.visibleNPCs().includes(hidden),'duplicate Occupied checkpoint is hidden from map/world rendering');assert(Math.hypot(hidden.x-compound.x,hidden.y-compound.y)<220,'quest trigger belongs to the same compound');Object.assign(c.hero,{x:hidden.x,y:hidden.y});c.tick(.01);assert(c.s.discovered['frontier:checkpoint'],'approaching the visible compound still fulfills the checkpoint visit');});

console.log(passed+' local quest and expedition scenarios passed.');
