'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),Campaign=require('../src/prototype/engine.js');
const source=fs.readFileSync(__dirname+'/game.test.cjs','utf8').split('let passed=0;')[0],scope={require,__dirname,Blob,console};vm.createContext(scope);vm.runInContext(source,scope);const g=scope.fresh({withSquad:true});
const legacy=g.run("player.level=7;player.gold=456;player.xp=33;player.spellLevels[2]=3;dungeonCleared.crypt=true;return saveSnapshot();");const copy=JSON.stringify(legacy),c=Campaign.migrate(legacy,()=>.9);
assert.equal(c.hero.level,7);assert.equal(c.hero.gold,456);assert.equal(c.hero.xp,33);assert.equal(c.hero.skills[1],3);assert(c.s.normal.crypt);assert(!c.s.rescued.crypt);assert(c.s.keys.crypt);assert(c.s.paid['clear:crypt']);assert.equal(JSON.stringify(legacy),copy);c.enter('crypt');assert(!c.zone().enemies.some(e=>e.guard||e.type==='boss'));const cage=c.zone().npcs.find(n=>n.family==='crypt'&&n.kind==='cage');Object.assign(c.hero,{x:cage.x,y:cage.y});assert(c.interact(cage));assert(c.s.rescued.crypt);Campaign.restore(c.snapshot());
console.log('PASS Actual v2 save migration preserves progression and retains the original export unchanged.');

// Simulate a v0.8.59 outdoor layout so an existing run must move its field compound
// and one untouched patrol pack without resetting campaign progress.
const previous=new Campaign(),state=previous.snapshot(),zone=state.zones.vale,oldField={x:950,y:1100},newField=previous.fieldCenter(0),fieldId='field-thorn',dx=oldField.x-newField.x,dy=oldField.y-newField.y,back=p=>{p.x+=dx;p.y+=dy;};
delete zone.outdoorOccupationVersion;zone.roadVersion=3;const fieldMini=zone.minis.find(m=>m.id===fieldId);fieldMini.x=oldField.x;fieldMini.y=oldField.y;for(const p of fieldMini.trapPosts)back(p);for(const p of zone.props.filter(p=>p.mini===fieldId))back(p);for(const e of zone.enemies.filter(e=>e.mini===fieldId)){back(e);back(e.home);}const thorn=zone.enemies.find(e=>e.type==='boss'&&e.family==='thorn'&&e.form==='normal');Object.assign(thorn,oldField);thorn.home={...oldField};const fieldCage=zone.npcs.find(n=>n.kind==='cage'&&n.family==='thorn');Object.assign(fieldCage,{x:oldField.x+90,y:oldField.y+80});const marker=zone.npcs.find(n=>n.kind==='mini'&&n.mini===fieldId);Object.assign(marker,{x:oldField.x-130,y:oldField.y-10});const generic=zone.enemies.filter(e=>e.type==='mob'&&e.pack&&!e.guard&&!e.mini&&!e.site&&!e.summon&&!e.nightOnly&&e.form==='normal'),pack=generic[0]?.pack;assert(pack);for(const [j,e]of zone.enemies.filter(e=>e.pack===pack).entries()){e.home={x:1050+j*20,y:1000+j*20};Object.assign(e,e.home);}state.hero.gold=777;state.quests['quest-1'].count=2;
const migratedLayout=Campaign.restore(state),mz=migratedLayout.s.zones.vale,migratedMini=mz.minis.find(m=>m.id===fieldId),migratedBoss=mz.enemies.find(e=>e.type==='boss'&&e.family==='thorn'&&e.form==='normal'),migratedPack=mz.enemies.filter(e=>e.pack===pack);assert.equal(mz.outdoorOccupationVersion,2);assert.equal(mz.roadVersion,7);assert.equal(migratedMini.x,newField.x);assert.equal(migratedMini.y,newField.y);assert.equal(migratedBoss.home.x,newField.x);assert.equal(migratedBoss.home.y,newField.y);assert.equal(migratedLayout.hero.gold,777);assert.equal(migratedLayout.s.quests['quest-1'].count,2);assert(migratedPack.some(e=>Math.hypot(e.home.x-1050,e.home.y-1000)>250));
console.log('PASS Current saves migrate to the distributed overworld without losing campaign progress.');

