'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine');
const fresh=()=>new C('normal','paladin',()=>.9),kill=(c,e,hero=false)=>{e.hp=0;e.heroParticipated=hero;c.kill(e);};
let passed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){process.exitCode=1;console.error('FAIL '+name+' '+e.stack);}}
for(const [i,r]of C.data.regions.entries())test(r.id+' field and resource dungeons have cover, accessible routes and reduced-reward guardians',()=>{
 const c=fresh();c.enter(r.id);c.s.expeditionRank=2;const z=c.zone();assert.equal(z.minis.length,2);
 for(const m of z.minis){assert(!m.cleared);const walls=z.props.filter(p=>p.mini===m.id);assert(walls.length>=3);const wall=walls[0];assert(c.blocked(wall.x,wall.y));assert(!c.line({x:wall.x-60,y:wall.y},{x:wall.x+60,y:wall.y}));const guards=z.enemies.filter(e=>e.mini===m.id);assert(guards.length>=3);guards.forEach(e=>{assert(e.guard);assert.equal(e.gold,Math.max(1,Math.floor((r.gold_range[0]+r.gold_range[1])/2*.35)));assert.equal(e.xp,r.guard_xp);assert(c.route(c.hero,e.home).length,r.id+' guardian route '+m.id+' '+e.id+' '+JSON.stringify(e.home));});
  const marker=z.npcs.find(n=>n.mini===m.id&&n.kind==='mini');assert(c.route(c.hero,marker).length);assert(c.miniStatus(m.id).includes('guardians'));
 }
 const node=z.nodes[0];assert(!c.gather(node.id));const bundle=z.npcs.find(n=>n.mini===node.mini&&n.kind==='bundle');if(bundle){Object.assign(c.hero,{x:bundle.x,y:bundle.y});assert(!c.interact(bundle));}
 const resource=z.minis.find(m=>m.type==='resource');z.enemies.filter(e=>e.mini===resource.id).forEach(e=>kill(c,e));assert(resource.cleared);assert(c.gather(node.id));if(bundle){Object.assign(c.hero,{x:bundle.x,y:bundle.y});assert(c.interact(bundle));}
 const field=z.minis.find(m=>m.type==='field'),q=c.questDefs().find(q=>q.clear===field.id);assert(c.s.quests[q.id].active);const boss=z.enemies.find(e=>e.family===field.family);kill(c,boss);const captive=z.npcs.find(n=>n.kind==='cage'&&n.family===field.family);Object.assign(c.hero,{x:captive.x,y:captive.y});assert(c.interact(captive));assert(!c.s.quests[q.id].done,'boss/captive alone cannot clear the compound');const g=c.hero.gold;z.enemies.filter(e=>e.mini===field.id).forEach(e=>kill(c,e));assert(field.cleared);assert(c.s.quests[q.id].done&&c.s.quests[q.id].paid);assert.equal(c.hero.gold,g+q.gold);assert(!c.claim(q.id));
 const restored=C.restore(c.snapshot());assert(restored.zone().minis.every(m=>m.cleared));assert(!restored.traps().length);restored.updatePacks(120);assert(restored.zone().enemies.filter(e=>e.mini).every(e=>e.hp===0),'mini guardians respawned');const before=JSON.stringify(restored.zone().minis);restored.enter('vale');restored.enter(r.id);assert.equal(JSON.stringify(restored.zone().minis),before);
});
test('Expanded-world mini guardians remain reachable and old stranded homes repair once',()=>{const c=fresh();c.enter('frontier');let z=c.zone();for(const e of z.enemies.filter(e=>e.guard&&e.mini))assert(c.route(c.hero,e.home).length,'fresh Frontier mini guardian unreachable '+e.id);const raw=c.snapshot(),rz=raw.zones.frontier,target=rz.enemies.find(e=>e.guard&&e.mini);assert(target);target.home={x:1455,y:1500};target.x=1455;target.y=1500;delete rz.miniReachabilityVersion;const r=C.restore(raw);z=r.zone();const repaired=z.enemies.find(e=>e.id===target.id);assert.equal(z.miniReachabilityVersion,1);assert(r.route(r.hero,repaired.home).length,'stranded saved mini guardian was not repaired');});
test('Pending guardian ringleaders prevent clear and inherit the reduced rewards and dungeon identity',()=>{const c=fresh();c.s.rescued.thorn=true;c.trainExpedition('thorn');const z=c.zone(),m=z.minis.find(m=>m.type==='resource'),guards=z.enemies.filter(e=>e.mini===m.id);for(const e of guards)kill(c,e,true);assert(Object.values(c.s.pending).some(p=>p.base.mini===m.id));assert(!m.cleared);assert(!c.gather(z.nodes[0].id));c.updateElites(3);const elites=z.enemies.filter(e=>e.form==='ringleader'&&e.mini===m.id);assert(elites.length);elites.forEach(e=>{assert(e.guard);assert.equal(e.gold,Math.floor((4+8)/2*.35)*1.5);assert.equal(e.xp,4*1.5);kill(c,e,false);});c.updateElites(.1);c.checkMinis();assert(m.cleared);assert(c.gather(z.nodes[0].id));});
test('Old saves gain dungeon geometry once without re-locking proven cleared bosses or depleted resources',()=>{const c=fresh();c.enter('highlands');const s=c.snapshot(),z=s.zones.highlands;delete z.minis;delete z.minisVersion;z.props=z.props.filter(p=>!p.mini);z.npcs=z.npcs.filter(n=>n.kind!=='mini');z.enemies.forEach(e=>{if(e.mini){delete e.mini;e.guard=false;}});z.nodes=[{...z.nodes[0],id:'gather-highlands',amount:237}];delete z.resourceDepositsVersion;s.normal.ridge=true;s.victories['ridge:normal']=true;s.rescued.ridge=true;s.keys.ridge=true;const r=C.restore(s);assert(r.zone().minis.every(m=>m.cleared));assert.equal(r.zone().nodes.reduce((sum,n)=>sum+n.amount,0),237);assert(r.s.rescued.ridge);const next=C.restore(r.snapshot());assert.deepEqual(next.zone().minis,r.zone().minis);assert.equal(next.zone().props.filter(p=>p.mini).length,r.zone().props.filter(p=>p.mini).length);});
test('Outdoor mini traps use the same regional pressure tiers as indoor dungeons and stop after clear',()=>{const map={vale:'crypt',march:'archive',highlands:'mine',frontier:'abyss',crown:'citadel'};for(const region of Object.keys(map)){const c=fresh();c.enter(region);const z=c.zone(),cfg=C.rules.outdoorMiniTrapTuning[region],indoor=C.rules.dungeonTrapTuning[map[region]],traps=c.traps();assert.deepEqual(cfg,indoor);assert(traps.length>=2,region+' mini traps');assert(traps.every(t=>t.cycleLength===cfg.cycle&&t.damageFraction===cfg.damage&&t.warningTime===cfg.warning));const m=z.minis.find(m=>m.type==='resource'),t=traps.find(t=>t.miniId===m.id)||traps[0];z.clock=(cfg.warning+.1-t.index*cfg.offset+cfg.cycle*30)%cfg.cycle;Object.assign(c.hero,{x:t.x,y:t.y});const hp=c.hero.hp;c.updateTraps(.1);assert(c.hero.hp<hp,region+' trap damages');assert(c.hero.hp>=hp-c.hero.maxHp*cfg.damage-1e-8);z.enemies.filter(e=>e.mini===m.id).forEach(e=>kill(c,e));assert(!c.traps().some(t=>t.miniId===m.id));}});
test('Peace opens remaining resource sites without paying unearned field-clear quests',()=>{const c=fresh();assert(c.s.quests['quest-0'].active);c.s.keys.thorn=true;c.rescue('thorn');c.trainExpedition('thorn');for(const b of C.data.bosses)c.victory(b.id,'normal');for(const id of ['darklord',...C.dungeonIds])c.victory(id,'true');c.checkEnding();assert(c.s.quests['quest-0'].closedByPeace);c.checkQuests();assert(!c.claim('quest-0'));assert(c.gather(c.zone().nodes[0].id));assert(!c.traps().length);});
test('v0.7.3 checkpoint and shelf deposits upgrade to separate shrine and foundry dungeons',()=>{for(const [region,oldSite,newSite]of [['frontier','checkpoint','shrine'],['crown','shelf','foundry']]){const c=fresh();c.enter(region);const s=c.snapshot(),z=s.zones[region];delete z.minis;delete z.minisVersion;z.props=z.props.filter(p=>!p.mini);z.npcs=z.npcs.filter(n=>n.kind!=='mini');z.enemies.forEach(e=>{if(e.mini){delete e.mini;e.guard=false;}});z.localSitesVersion=1;const landmark=z.npcs.find(n=>n.id===oldSite);Object.assign(z.nodes[0],{x:landmark.x,y:landmark.y,site:oldSite,amount:137});const restored=C.restore(s);assert.equal(restored.zone().nodes[0].site,newSite);assert.equal(restored.zone().nodes[0].amount,137);assert.equal(restored.zone().localSitesVersion,2);const resource=restored.zone().minis.find(m=>m.type==='resource'),field=restored.zone().minis.find(m=>m.type==='field');assert(Math.hypot(resource.x-field.x,resource.y-field.y)>500);}});
test('Malformed field dungeon saves are rejected',()=>{for(const mutate of [s=>s.zones.vale.minis[0].id='bad',s=>s.zones.vale.minis[0].cleared='yes',s=>s.zones.vale.minis[0].trapPosts=[{x:NaN,y:1,kind:'spikes',index:100}]]){const s=fresh().snapshot();mutate(s);assert.throws(()=>C.restore(s));}});
console.log(passed+' mini dungeon scenarios passed.');
