'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine.js'),D=C.data;
const kill=(c,e)=>{e.hp=0;e.heroParticipated=false;c.kill(e);};
for(const [gap,m]of [[-2,1],[0,1],[1,.75],[2,.4],[3,.1],[4,0],[8,0]]){const c=new C();c.hero.level=10;assert.deepEqual(c.reward(100,100,10-gap),{gold:100*m,xp:100*m});}
console.log('PASS lower-level XP and gold scale from the first level gap and stop at four');
for(const region of D.regions){const c=new C('normal','paladin',()=>.9);c.enter(region.id);const e=c.zone().enemies.find(e=>e.type==='mob'&&!e.guard&&!e.nightOnly);c.hero.level=e.level;c.hero.xp=0;const gold=e.gold,xp=e.xp;kill(c,e);assert.equal(c.hero.xp,Math.floor(xp*.5));assert.equal(c.s.loot.at(-1).gold,gold);const restored=C.restore(c.snapshot()),r=restored.zone().enemies.find(saved=>saved.id===e.id);assert.equal(r.xp,xp,'saved reward base must not compound the nerf');restored.hero.level=r.level;restored.hero.xp=0;r.hp=0;r.deathPaid=false;kill(restored,r);assert.equal(restored.hero.xp,Math.floor(xp*.5));}
console.log('PASS ordinary kills give half XP in every region and saved bases do not decay on reload');
{
 const c=new C('normal','paladin',()=>.9),g=c.zone().enemies.find(e=>e.guard),e=c.zone().enemies.find(e=>e.type==='mob'&&!e.guard);c.hero.level=e.level;
 const elite={...e,form:'ringleader',level:e.level+2,xp:e.xp*1.5};assert.equal(c.enemyReward(elite).xp,Math.floor(e.xp*1.5));assert(c.enemyReward(elite).xp>=3*c.enemyReward(e).xp);c.hero.level=g.level;assert.equal(c.enemyReward(g).xp,g.xp);assert.equal(c.enemyReward({...g,form:'ringleader',level:g.level+2,xp:g.xp*1.5}).xp,Math.floor(g.xp*1.5));
 const b=c.bossEnemy(c.boss('darklord'),'normal',{x:1000,y:1000});assert.equal(b.level,16);c.hero.level=16;assert.equal(c.enemyReward(b).xp,b.xp);c.hero.level=20;assert.deepEqual(c.enemyReward(b),{gold:0,xp:0});c.hero.xp=0;c.xp(120*20);assert.equal(c.hero.level,21,'future content is not limited by a level cap');assert.equal(c.reward(100,100,23).xp,100);
}
console.log('PASS ringleaders and bosses retain challenge rewards, guardians stay reduced, future levels remain open');
{
 const c=new C(),e=c.zone().enemies.find(e=>e.type==='mob'&&!e.guard);for(const p of Object.values(c.s.quests)){p.done=true;p.paid=true;p.active=false;}c.hero.level=e.level+4;c.hero.xp=0;const loot=c.s.loot.length;for(let i=0;i<100;i++){e.deathPaid=false;kill(c,e);}assert.equal(c.hero.xp,0);assert.equal(c.s.loot.length,loot,'zero-reward farming produces no gold piles');
 const qc=new C();qc.hero.level=20;qc.hero.xp=0;qc.discover('bridge-north');qc.discover('port');const q=qc.questDefs().find(q=>q.id==='quest-4');assert(qc.s.quests[q.id].done&&qc.s.quests[q.id].paid);assert.equal(qc.hero.xp,q.xp);assert(!qc.claim(q.id));
 const questXP=D.quests.reduce((n,q)=>n+q[4],0),mobXP=D.regions.reduce((n,r)=>n+r.enemy_count*Math.floor(r.enemy_xp*.5),0);assert(questXP>mobXP*1.5);
}
console.log('PASS trivial farming pays nothing and one-time quests dominate a complete ordinary population sweep');
{
 const baselineHp=[65,170,275,380,485],baselineDamage=[7,15,23,31,39];
 for(const [i,region] of D.regions.entries()){const c=new C('normal','paladin',()=>.9);c.enter(region.id);const meleeCfg=C.rules.ordinaryMeleeScaling[i],rangedCfg=C.rules.ordinaryRangedScaling[i],melee=c.zone().enemies.find(e=>e.type==='mob'&&!e.guard&&!e.ranged&&!e.nightOnly&&e.form==='normal'),ranged=c.zone().enemies.find(e=>e.type==='mob'&&!e.guard&&e.ranged&&!e.nightOnly&&e.form==='normal');assert(melee,region.id+' melee fixture');assert(ranged,region.id+' ranged fixture');assert.equal(melee.baseHp,Math.round(baselineHp[i]*meleeCfg.hp));assert.equal(melee.baseDamage,Math.round(baselineDamage[i]*meleeCfg.damage));assert.equal(ranged.baseHp,Math.round(baselineHp[i]*rangedCfg.hp));assert.equal(ranged.baseDamage,Math.round(baselineDamage[i]*rangedCfg.damage));assert(ranged.baseHp<melee.baseHp,region.id+' ranged HP remains below melee');assert(ranged.baseDamage<=melee.baseDamage,region.id+' ranged damage remains at or below melee');}
}
console.log('PASS ordinary melee and ranged monsters use distinct regional scaling curves');
{
 const c=new C('normal','paladin',()=>.9);c.enter('crown');const raw=JSON.parse(JSON.stringify(c.s)),z=raw.zones.crown,melee=z.enemies.find(e=>e.type==='mob'&&!e.guard&&!e.ranged&&!e.nightOnly&&e.form==='normal'),ranged=z.enemies.find(e=>e.type==='mob'&&!e.guard&&e.ranged&&!e.nightOnly&&e.form==='normal'),mcfg=C.rules.ordinaryMeleeScaling[4],rcfg=C.rules.ordinaryRangedScaling[4];delete z.meleeBalanceVersion;delete z.rangedBalanceVersion;Object.assign(melee,{baseHp:485,maxHp:485,hp:242.5,baseDamage:39,damage:39});delete melee.meleeBalanceVersion;Object.assign(ranged,{baseHp:485,maxHp:485,hp:242.5,baseDamage:39,damage:39});delete ranged.rangedBalanceVersion;const r=C.restore(raw),m=r.zone().enemies.find(x=>x.id===melee.id),rr=r.zone().enemies.find(x=>x.id===ranged.id);assert.equal(m.baseHp,Math.round(485*mcfg.hp));assert.equal(m.baseDamage,Math.round(39*mcfg.damage));assert.equal(rr.baseHp,Math.round(485*rcfg.hp));assert.equal(rr.baseDamage,Math.round(39*rcfg.damage));assert(Math.abs(m.hp/m.maxHp-.5)<1e-9);assert(Math.abs(rr.hp/rr.maxHp-.5)<1e-9);const again=C.restore(r.snapshot()),m2=again.zone().enemies.find(x=>x.id===melee.id),r2=again.zone().enemies.find(x=>x.id===ranged.id);assert.equal(m2.baseHp,m.baseHp);assert.equal(m2.baseDamage,m.baseDamage);assert.equal(r2.baseHp,rr.baseHp);assert.equal(r2.baseDamage,rr.baseDamage);
}
console.log('PASS existing saves upgrade melee and ranged stats once while preserving wounds and avoiding compounding');
