const fs=require('fs'),vm=require('vm'),C=require('../src/prototype/engine.js'),A=require('../src/prototype/audio.js');
const elements=new Map(),events={},frames=[],storage=new Map();
const ctx=new Proxy({}, {get:(o,k)=>o[k]||(()=>{})});
function el(){const classes=new Set(),small={textContent:''};return {hidden:false,children:[],style:{},width:1280,height:800,textContent:'',classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),toggle:(x,v)=>v?classes.add(x):classes.delete(x)},getContext:()=>ctx,append(...x){this.children.push(...x)},replaceChildren(){this.children=[]},setAttribute(){},querySelector:()=>small,scrollIntoView(){},click(){if(!this.disabled)this.onclick?.()},getBoundingClientRect:()=>({left:12,top:670,width:110,height:110}),setPointerCapture(){}};}
const initial=new C();storage.set('azeroth-v4-normal',JSON.stringify(initial.snapshot()));
const scope={Campaign:C,PrototypeAudio:A,PrototypeVisuals:{draw(){},roads(){},height:()=>40},Sprint:{enabled:false,press(){},release(){},tick:()=>1},console,performance:{now:()=>0},innerWidth:1280,innerHeight:800,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},location:{protocol:'file:',hostname:''},navigator:{},document:{hidden:false,body:el(),getElementById:id=>{if(!elements.has(id))elements.set(id,el());return elements.get(id)},createElement:()=>el(),addEventListener(){}},addEventListener:(name,fn)=>(events[name]??=[]).push(fn),requestAnimationFrame:fn=>frames.push(fn),setTimeout(){},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},confirm:()=>true};scope.window=scope;vm.createContext(scope);vm.runInContext(fs.readFileSync(__dirname+'/../src/prototype/app.js','utf8'),scope);
const key=code=>events.keydown.forEach(fn=>fn({code,preventDefault(){}}));

const assert=require('node:assert/strict');
for(const [code,title]of [['KeyR','Inventory'],['KeyC','Talents'],['KeyX','Skills and teachers'],['KeyT','Quest'],['KeyG','Controls']]){scope.Prototype.closeMenu();key(code);assert(!elements.get('modal').hidden);assert(elements.get('modal-title').textContent.includes(title),code+' '+elements.get('modal-title').textContent);}
scope.Prototype.closeMenu();key('KeyV');assert(scope.Prototype.paused);const c=scope.Prototype.game,e=c.zone().enemies.find(e=>e.type==='mob');c.zone().enemies=[e];Object.assign(c.hero,{x:e.x-50,y:e.y});const before=JSON.stringify(c.snapshot());key('Digit1');elements.get('skills').children[0].click();elements.get('skills').children[0].onpointerdown();assert.equal(JSON.stringify(c.snapshot()),before);key('KeyV');assert(!scope.Prototype.paused);
key('KeyG');const first=elements.get('modal-actions').children[0];let confirmed=false;first.onclick=()=>confirmed=true;elements.get('order-button').click();assert(confirmed);scope.Prototype.closeMenu();key('Tab');elements.get('interact-button').click();assert(!scope.Prototype.paused);
key('Tab');c.s.keys.thorn=true;c.rescue('thorn');c.hero.skills[1]=2;const teacher=c.zone().npcs.find(n=>n.id==='service-thorn');Object.assign(c.hero,{x:teacher.x,y:teacher.y});elements.get('interact-button').click();assert(elements.get('modal-description').textContent.includes(C.data.regions[1].name));assert(elements.get('modal-description').textContent.includes(c.boss('mire').captive));scope.Prototype.closeMenu();key('KeyX');assert(elements.get('modal-actions').children.some(b=>b.children.some(d=>d.textContent.includes('Greenwood Vale'))));
console.log('PASS F05 pause blocks keyboard/touch/held casts; F15 restored left-hand shortcuts and menu confirmation; F18 teacher guidance');

scope.Prototype.closeMenu();c.hero.skills=Array(8).fill(1);c.hero.level=40;c.hero.gold=5000;Object.assign(c.hero,{x:teacher.x,y:teacher.y});elements.get('interact-button').click();const buttons=elements.get('modal-actions').children;assert.equal(buttons.length,2);assert(buttons[0].children.some(d=>d.textContent.includes('Skill 1 ')));assert(buttons[1].children.some(d=>d.textContent.includes('Skill 2 ')));assert(!buttons.some(b=>b.textContent.includes('Recovery')));scope.Prototype.closeMenu();c.hero.skills=[1,0,0,0,0,0,0,0];key('KeyX');assert.equal(elements.get('modal-actions').children.length,2);console.log('PASS first specialist hides all advanced skills even when known; unreached skills stay out of the skill book');
scope.Prototype.closeMenu();c.accept('quest-2');const crate=c.zone().npcs.find(n=>n.id==='bundle-0');Object.assign(c.hero,{x:crate.x,y:crate.y});elements.get('interact-button').click();assert(c.s.discovered['vale:bundle-0']);assert(!c.visibleNPCs().includes(crate));assert(JSON.parse(storage.get('azeroth-v4-normal')).discovered['vale:bundle-0']);key('KeyJ');assert(elements.get('modal-actions').children.some(b=>b.children.some(d=>d.textContent.includes('1/3 supplies recovered'))));scope.Prototype.closeMenu();key('KeyZ');assert(elements.get('modal-actions').children.some(b=>b.textContent.includes('Woodland timber')));assert(!elements.get('modal-actions').children.some(b=>b.textContent.includes(crate.name)));scope.Prototype.closeMenu();const node=c.zone().nodes[0];Object.assign(c.hero,{x:node.x,y:node.y});elements.get('interact-button').click();assert.equal(c.s.party.find(u=>u.type==='worker').order.type,'gather');assert.equal(c.s.party.find(u=>u.type==='worker').order.id,node.id);console.log('PASS collection button saves and hides crates; journal names remaining objectives; map and nearby interaction expose guarded worker deposits');
