'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pw=require(process.env.PLAYWRIGHT_MODULE||'playwright'),root=path.resolve(__dirname,'..'),results=path.join(root,'test-results');fs.mkdirSync(results,{recursive:true});
const executable=process.env.CHROMIUM_EXECUTABLE,launch={headless:true};if(executable){launch.executablePath=executable;launch.args=['--no-sandbox','--single-process','--no-zygote','--disable-gpu'];}
let passed=0;async function check(name,fn){await fn();passed++;console.log('PASS '+name);}
(async()=>{for(const v of [{width:1280,height:800,touch:false},{width:375,height:812,touch:true},{width:320,height:568,touch:true},{width:844,height:390,touch:true}]){
const b=await pw.chromium.launch(launch),page=await b.newPage({viewport:{width:v.width,height:v.height},hasTouch:v.touch,isMobile:v.touch}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const url=process.env.PLAYTEST_URL||'file://'+path.join(root,process.env.PLAYTEST_FILE||'index.html');await page.goto(url);const tag=v.width+'x'+v.height;
await check('New-game Succession opt-in and audio gesture '+tag,async()=>{assert.equal(await page.locator('#modal-title').textContent(),'Challenge condition');assert.equal(await page.evaluate(()=>Prototype.audio.ctx),null);await page.getByRole('button',{name:'Succession challenge',exact:true}).click();await page.getByRole('button',{name:/paladin/}).click();await page.waitForFunction(()=>document.querySelector('#modal').hidden);assert(await page.evaluate(()=>Prototype.game.s.challenge.succession));await page.waitForFunction(()=>Prototype.audio.ctx?.state==='running');assert.deepEqual(await page.evaluate(()=>Prototype.game.hero.skills),[1,0,0,0,0,0,0,0]);});
await check('Movement, left controls, Q dormant, pause and keyboard menus '+tag,async()=>{const a=await page.locator('#skills').boundingBox(),j=await page.locator('#joystick').boundingBox();assert(a.x>=0&&a.x+a.width<=v.width/2+1);assert(j.x>=0&&j.y+j.height<=v.height);assert(a.y>=0&&a.y+a.height<=v.height);assert(a.x+a.width<=j.x||j.x+j.width<=a.x||a.y+a.height<=j.y||j.y+j.height<=a.y,'controls overlap');const start=await page.evaluate(()=>[Prototype.game.hero.x,Prototype.game.hero.y]);await page.keyboard.down('d');await page.waitForTimeout(150);await page.keyboard.up('d');const end=await page.evaluate(()=>[Prototype.game.hero.x,Prototype.game.hero.y]);assert(end[0]>start[0]);await page.keyboard.press('q');assert(await page.locator('#sprint-button').isHidden());await page.keyboard.press('Escape');const t=await page.evaluate(()=>Prototype.game.s.time);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>Prototype.game.s.time),t);await page.keyboard.press('f');assert(await page.locator('#modal').isHidden());});
await page.screenshot({path:path.join(results,'adventure-'+tag+'.png')});
await check('Succession first death choice, persistence, automatic last class and game over '+tag,async()=>{await page.evaluate(()=>{const c=Prototype.game;c.hero.gold=789;c.victory('thorn','normal');c.s.keys.thorn=true;c.rescue('thorn');c.hero.level=10;c.hero.skills=[2,2,2,1,1,1,1,0];c.die();});await page.waitForFunction(()=>document.querySelector('#modal-title').textContent==='Choose your successor');assert.equal(await page.locator('#modal-actions button').count(),2);await page.reload();await page.waitForFunction(()=>document.querySelector('#modal-title').textContent==='Choose your successor');await page.getByRole('button',{name:/mage successor/}).click();assert.equal(await page.evaluate(()=>Prototype.game.hero.level),1);assert.equal(await page.evaluate(()=>Prototype.game.hero.gold),789);assert(await page.evaluate(()=>Prototype.game.s.rescued.thorn));await page.evaluate(()=>Prototype.game.die());await page.waitForFunction(()=>Prototype.game.hero.class==='ranger');assert.deepEqual(await page.evaluate(()=>Prototype.game.s.challenge.fallen),['paladin','mage']);await page.evaluate(()=>Prototype.game.die());await page.waitForFunction(()=>document.querySelector('#modal-title').textContent==='The last successor has fallen');await page.screenshot({path:path.join(results,'succession-game-over-'+tag+'.png')});await page.reload();await page.waitForFunction(()=>Prototype.game.s.challenge.gameOver);});
await check('Fresh Standard run resets challenge and preserves profile sound settings '+tag,async()=>{await page.getByRole('button',{name:'Start a new Normal run',exact:true}).click();await page.getByRole('button',{name:'Standard death and refuge recovery',exact:true}).click();await page.getByRole('button',{name:/paladin/}).click();await page.waitForFunction(()=>document.querySelector('#modal').hidden);assert(!(await page.evaluate(()=>Prototype.game.s.challenge.succession)));});
await check('Peace ending, every peaceful place, Nightmare unlock and fresh separate save '+tag,async()=>{await page.evaluate(()=>{const c=Prototype.game;for(const b of Campaign.data.bosses)c.victory(b.id,'normal');for(const id of ['darklord',...Campaign.dungeonIds])c.victory(id,'true');c.checkEnding();});await page.waitForFunction(()=>document.querySelector('#modal-title').textContent==='Peace for everyone');assert(await page.evaluate(()=>Prototype.profile.nightmareUnlocked));await page.screenshot({path:path.join(results,'peace-'+tag+'.png')});await page.getByRole('button',{name:'Continue in the peaceful world',exact:true}).click();await page.evaluate(()=>Prototype.game.enter('crypt'));assert(await page.evaluate(()=>Prototype.game.zone().enemies.every(e=>e.neutral)));await page.keyboard.press('Escape');await page.getByRole('button',{name:'New game in Nightmare Mode',exact:false}).click();await page.getByRole('button',{name:'Standard death and refuge recovery',exact:true}).click();await page.getByRole('button',{name:/ranger/}).click();assert.equal(await page.evaluate(()=>Prototype.game.s.mode),'nightmare');assert(await page.evaluate(()=>Prototype.game.night()));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('azeroth-v4-normal')).phase),'peace');});
assert.deepEqual(errors,[],'browser errors '+tag);await b.close();}
console.log('\n'+passed+' desktop/mobile browser checks passed.');})().catch(e=>{console.error(e.stack);process.exit(1);});
