'use strict';
const assert=require('node:assert/strict'),Campaign=require('../src/prototype/engine.js'),D=Campaign.data;
let passed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){process.exitCode=1;console.error('FAIL '+name+'\n'+e.stack);}}
const fresh=(r=.9,options={})=>new Campaign('normal','paladin',()=>r,options);
function slay(c,e,hero=true){Object.assign(c.hero,c.safe(e.x,e.y));e.heroParticipated=hero;e.hp=0;c.kill(e);}
function boss(c,id,form='normal'){const b=c.boss(id);c.enter(b.kind==='dungeon'?id:b.region);let e=c.zone().enemies.find(e=>e.family===id&&e.form===form&&e.hp>0);if(!e){e=c.bossEnemy(b,form,{x:c.hero.x+100,y:c.hero.y});c.zone().enemies.push(e);}return e;}
function settle(c,n=40){for(let i=0;i<n;i++)c.tick(.1);}
test('All three classes start with one skill and valid save round trips',()=>{for(const id of Object.keys(Campaign.classes)){const c=new Campaign('normal',id);assert.deepEqual(c.hero.skills,[1,0,0,0,0,0,0,0]);assert.deepEqual(Campaign.restore(c.snapshot()).snapshot(),c.snapshot());}});
test('Every town, cage, transport, dungeon and boss is reachable on the terrain graph',()=>{const c=fresh();for(const r of D.regions){c.enter(r.id);for(const n of c.zone().npcs){assert(!c.blocked(n.x,n.y),r.id+' blocked '+n.id);assert(c.route(c.hero,n).length,r.id+' unreachable '+n.id);}const e=c.zone().enemies.find(e=>e.type==='boss');assert(c.route(c.hero,e.home).length,r.id+' boss');}for(const id of Campaign.dungeonIds){c.enter(id);for(const n of c.zone().npcs)assert(c.route(c.hero,n).length,id+' '+n.id);assert(c.route(c.hero,c.zone().enemies.find(e=>e.type==='boss').home).length,id);}});
test('Authored larger populations retain lower rewards and finite resources',()=>{const c=fresh();let mobs=0,guards=0;for(const r of D.regions){c.enter(r.id);mobs+=c.zone().enemies.filter(e=>e.type==='mob').length;assert.equal(c.zone().nodes[0].amount,r.resource);}for(const id of Campaign.dungeonIds){c.enter(id);guards+=c.zone().enemies.filter(e=>e.guard).length;}assert.equal(mobs,240);assert.equal(guards,90);assert.deepEqual(c.reward(40,100,1),{gold:40,xp:100});c.hero.level=7;assert.deepEqual(c.reward(40,100,1),{gold:0,xp:0});});
test('Learning and rank advancement require rescue, levels and funds',()=>{const c=fresh();assert(!c.learn(2,'thorn'));slay(c,boss(c,'thorn'));assert(c.rescue('thorn'));c.hero.level=3;c.hero.gold=100;assert(c.learn(2,'thorn'));assert.equal(c.hero.gold,60);assert(!c.learn(2,'thorn'));assert(c.upgrade(2,'thorn'));assert.equal(c.hero.skills[1],2);assert(!c.upgrade(2,'thorn'));});
test('Supplies, smith tiers and tonics spend gold and cannot duplicate purchases',()=>{const c=fresh();c.hero.gold=1000;assert(c.buyPotion('health'));assert.equal(c.hero.gold,980);assert(!c.buyPotion('tonic'));c.s.rescued.archive=true;const hp=c.hero.maxHp;assert(c.buyPotion('tonic'));assert.equal(c.hero.maxHp,hp+Math.ceil(hp*.1));assert(!c.buyPotion('tonic'));c.rest();assert.equal(c.hero.maxHp,hp);c.s.rescued.crypt=true;assert(c.gear('crypt','weapon'));assert(!c.gear('crypt','weapon'));assert(c.gear('crypt','weapon',true));assert(!c.gear('crypt','weapon',true));});
test('Two hero participating kills trigger two leaders at the 50% branch',()=>{const c=fresh(.2),e=c.zone().enemies.find(e=>e.type==='mob');c.streak(e);assert.equal(c.s.streak.count,1);c.streak(e);assert.equal(c.s.pending[e.species].count,2);c.updateElites(3);assert.equal(c.zone().enemies.filter(x=>x.form==='ringleader').length,2);});
test('Companion-only kills neither advance nor reset streak; hero participation qualifies last hits',()=>{const c=fresh();const a=c.zone().enemies.find(e=>e.species==='goblin'),b=c.zone().enemies.find(e=>e.species==='skeleton');slay(c,a);assert.equal(c.s.streak.count,1);slay(c,b,false);assert.equal(c.s.streak.count,1);const a2=c.zone().enemies.find(e=>e.species==='goblin'&&e.hp>0);slay(c,a2);assert.equal(c.s.pending.goblin.count,1);});
test('Mixed species resets; summons are killable and grant no streak, gold or XP',()=>{const c=fresh();c.streak(c.zone().enemies.find(e=>e.species==='goblin'));c.streak(c.zone().enemies.find(e=>e.species==='skeleton'));assert.equal(c.s.streak.key,'skeleton');assert.equal(c.s.streak.count,1);const e=c.makeEnemy({species:'summon',name:'summon',level:1,hp:1,damage:1,gold:0,xp:0},{x:c.hero.x+30,y:c.hero.y});e.summon=true;c.zone().enemies.push(e);const xp=c.hero.xp,loot=c.s.loot.length;assert(c.cast(1,e.id));assert.equal(e.hp,0);assert.equal(c.hero.xp,xp);assert.equal(c.s.loot.length,loot);assert.equal(c.s.streak.count,1);});
test('Night enemies are strong and use distinct warned abilities',()=>{for(const [zone,species,name] of [['march','wraith','Soul Drain'],['frontier','stalker','Shadow Pounce']]){const c=fresh();c.enter(zone);c.s.clock=500;c.updateNight();const e=c.zone().enemies.find(e=>e.species===species&&e.nightOnly),cfg=Campaign.rules.nightEnemyCombat[species];assert(e);const i=c.regionIndex();assert.equal(e.baseHp,Math.round((120+i*100)*cfg.hp));assert.equal(e.baseDamage,Math.round((12+i*7)*cfg.damage));c.s.party=[];Object.assign(c.hero,{x:e.x+100,y:e.y,maxHp:10000,hp:10000});c.engage(e);e.specialCd=0;c.updateEnemies(.1);assert.equal(e.telegraph?.name,name);if(species==='wraith'){e.hp=e.maxHp*.5;const hp=c.hero.hp;e.telegraph.timer=0;c.updateEnemies(.1);assert(c.hero.hp<hp);assert(c.hero.slow>0);assert(e.hp>e.maxHp*.5);}else{e.telegraph.timer=0;c.updateEnemies(.1);assert(e.motion);assert.equal(e.motion.speed,cfg.pounceSpeed);}}});
test('Boss summons inherit regional threat scaling but keep zero rewards',()=>{const c=fresh();c.enter('crown');const e=boss(c,'darklord');e.attackIndex=2;c.startAttack(e,c.hero);assert.equal(e.telegraph.kind,'summon');c.resolveAttack(e);const adds=c.zone().enemies.filter(x=>x.summon&&x.owner===e.id);assert.equal(adds.length,2);const cfg=Campaign.rules.summonScaling[4];for(const a of adds){assert.equal(a.baseHp,Math.round((40+e.level*15)*cfg.hp));assert.equal(a.baseDamage,Math.round((5+e.level)*cfg.damage));assert.equal(a.gold,0);assert.equal(a.xp,0);assert.equal(a.summonBalanceVersion,1);}});
test('Every boss cycles four named warned mechanics',()=>{const c=fresh();for(const b of D.bosses){const e=boss(c,b.id),names=[];for(let i=0;i<4;i++){c.startAttack(e,c.hero);names.push(e.telegraph.name);assert(e.telegraph.total>=.8);}assert.equal(new Set(names).size,4,b.id);}});
test('Unreachable aggression resets after twelve seconds and ignores player damage as progress',()=>{const c=fresh(),e=c.zone().enemies.find(e=>e.type==='mob');c.s.party=[];Object.assign(c.hero,{x:e.x+330,y:e.y});c.engage(e);e.hp-=20;c.follow=()=>false;for(let i=0;i<119;i++)c.updateEnemies(.1);assert(e.aggro);for(let i=0;i<22;i++)c.updateEnemies(.1);assert.equal(e.hp,e.baseHp);assert(!e.aggro);assert.deepEqual({x:e.x,y:e.y},e.home);});
test('Field normal respawns, two kills summon exactly one TRUE, other field bosses survive awakening',()=>{const c=fresh(),e=boss(c,'thorn');slay(c,e);assert.equal(e.respawn,120);c.updateEnemies(121);assert(e.hp>0);slay(c,e);assert.equal(c.s.pending.thorn.count,1);c.updateElites(3);const t=c.zone().enemies.find(e=>e.family==='thorn'&&e.form==='true'&&e.hp>0);assert(t);slay(c,t);c.updateElites(1);c.s.normal.darklord=true;c.s.true.darklord=true;c.s.victories['darklord:normal']=true;c.s.victories['darklord:true']=true;c.awaken();c.updateEnemies(121);assert(c.zone().enemies.some(e=>e.family==='thorn'&&e.hp>0));});
test('Dungeon one-third roll is saved, grants an early TRUE at most once and never respawns normal',()=>{const c=fresh(.2);slay(c,boss(c,'crypt'));assert(c.s.earlyRoll.crypt);c.activatePending();const t=c.zone().enemies.find(e=>e.form==='true'&&e.hp>0);assert(t);slay(c,t);c.enter('vale');c.enter('crypt');assert(!c.zone().enemies.some(e=>e.type==='boss'&&e.hp>0));const restored=Campaign.restore(c.snapshot(),()=>.9);assert(restored.s.earlyRoll.crypt);});
test('Awakening guarantees missed TRUEs, normalizes the common band and retains early victories',()=>{const c=fresh();slay(c,boss(c,'crypt'));assert.equal(c.s.earlyRoll.crypt,false);c.victory('archive','normal');c.victory('archive','true');slay(c,boss(c,'darklord'));slay(c,boss(c,'darklord','true'));assert.equal(c.s.phase,'awakening');assert(c.s.pending.crypt);assert(!c.s.pending.archive);c.enter('crypt');const e=c.zone().enemies.find(e=>e.form==='true'&&e.hp>0);assert.equal(e.baseHp,13000);assert.equal(e.baseDamage,70);assert.equal(e.level,c.s.awakeningLevel);});
test('Skipped normal dungeon defeated after awakening guarantees TRUE despite a failed roll',()=>{const c=fresh();slay(c,boss(c,'darklord'));slay(c,boss(c,'darklord','true'));slay(c,boss(c,'mine'));assert.equal(c.s.earlyRoll.mine,false);assert(c.s.pending.mine);c.activatePending();assert(c.zone().enemies.some(e=>e.form==='true'&&e.hp>0));});
test('Night first victories deduplicate; Normal caps at fifteen while Nightmare counts twenty',()=>{for(const mode of ['normal','nightmare']){const c=new Campaign(mode);c.s.clock=500;for(const b of D.bosses)c.victory(b.id,'normal');assert.equal(c.nightPoints(),10);c.s.phase='awakening';for(const b of D.bosses)c.victory(b.id,'true');assert.equal(c.nightPoints(),mode==='normal'?15:20);const m=c.multipliers();assert(Math.abs(m.hp-(mode==='normal'?1.55:1.7))<1e-10);c.victory('crypt','true');assert.equal(c.nightPoints(),mode==='normal'?15:20);}});
test('Peace is reachable in both modes, includes 60 native residents, 20 dungeon residents and four neutral field bosses',()=>{for(const mode of ['normal','nightmare']){const c=new Campaign(mode);for(const r of D.regions)c.enter(r.id);for(const id of Campaign.dungeonIds)c.enter(id);for(const b of D.bosses)c.victory(b.id,'normal');c.victory('darklord','true');c.awaken();for(const id of Campaign.dungeonIds)c.victory(id,'true');c.checkEnding();assert(c.peace);let out=0,inside=0,field=0;for(const z of Object.values(c.s.zones)){for(const e of z.enemies){assert(e.neutral);assert.equal(c.damage(e,100),false);if(e.type==='boss')field++;else if(Campaign.dungeonIds.includes(z.id))inside++;else out++;}}assert.equal(out,60);assert.equal(inside,20);assert.equal(field,4);assert.equal(c.traps().length,0);assert(!c.cast(1));assert.equal(c.hitParty(c.hero,999),false);Campaign.restore(c.snapshot());if(mode==='nightmare'){assert.equal(c.s.clock,480);c.s.clock=719.95;c.tick(.1);assert(!c.night());}}});
test('All early TRUE clears allow immediate peace on TRUE Dark Lord; Dark Lord stays absent',()=>{const c=fresh();for(const id of Campaign.dungeonIds){c.victory(id,'normal');c.victory(id,'true');}slay(c,boss(c,'darklord'));slay(c,boss(c,'darklord','true'));assert(c.peace);c.enter('crown');assert(!c.zone().enemies.some(e=>e.family==='darklord'));});
test('Quests are one-time, rescue and exploration facts persist and peace pays only earned rewards',()=>{const c=fresh();c.accept('quest-0');slay(c,boss(c,'thorn'));c.rescue('thorn');for(const g of c.zone().enemies.filter(e=>e.mini==='field-thorn'))slay(c,g,false);assert(c.s.quests['quest-0'].done);const gold=c.hero.gold;assert(c.claim('quest-0'));assert.equal(c.hero.gold,gold+45);assert(!c.claim('quest-0'));c.accept('quest-5');c.discover('den-ruins');c.discover('bridge-south');assert(c.s.quests['quest-5'].done);c.accept('quest-1');for(const b of D.bosses)c.victory(b.id,'normal');for(const id of ['darklord',...Campaign.dungeonIds])c.victory(id,'true');c.checkEnding();assert(c.s.quests['quest-1'].closedByPeace);assert(!c.claim('quest-1'));assert(c.claim('quest-5'));});
test('Paid travel preserves supplies, free return and standard death recovery do not create circular costs',()=>{const c=fresh();assert(c.travel(1));assert.equal(c.s.zone,'march');assert.equal(c.hero.gold,5);assert(c.travel(-1));assert.equal(c.hero.gold,5);c.hero.gold=25;c.travel(1);c.die();c.enter('vale');assert(c.travel(1));assert.equal(c.hero.gold,0);});
test('Six companion cap includes queued recruits; move orders and finite gathering obey their orders',()=>{const c=fresh();c.hero.gold=1000;while(c.recruit('soldier')){}assert.equal(c.s.party.length,6);assert(!c.recruit('archer'));const worker=c.s.party.find(u=>u.type==='worker');worker.order={type:'move',x:worker.x+100,y:worker.y};const old=worker.x;c.updateParty(.1);assert(worker.x>old);c.s.party=[worker];const node=c.zone().nodes[0];node.amount=12;for(const g of c.zone().enemies.filter(e=>e.mini===node.mini))slay(c,g,false);Object.assign(worker,node);worker.order={type:'gather',id:node.id};for(let i=0;i<11;i++)c.updateParty(.1);assert.equal(node.amount,0);const [x,y]=D.towns[0];Object.assign(worker,{x,y});c.updateParty(.1);assert.equal(c.hero.gold%1,0);});
test('Succession preserves gold, all world facts and equipment, resets XP/skills/talents and prompts at first death',()=>{const c=fresh(.9,{succession:true});slay(c,boss(c,'thorn'));c.rescue('thorn');c.hero.gold=888;c.hero.level=12;c.hero.xp=72;c.hero.skills=[3,3,2,1,1,1,1,0];c.hero.talents=[2,1,2,1];c.hero.weapon=1;c.die();assert(c.s.challenge.pending);assert.deepEqual(c.s.challenge.fallen,['paladin']);assert(!c.successor('paladin'));const restored=Campaign.restore(c.snapshot());assert(restored.s.challenge.pending);assert(restored.successor('mage'));assert.equal(restored.hero.level,1);assert.equal(restored.hero.xp,0);assert.equal(restored.hero.gold,888);assert.equal(restored.hero.weapon,1);assert.deepEqual(restored.hero.skills,[1,0,0,0,0,0,0,0]);assert.deepEqual(restored.hero.talents,[0,0,0,0]);assert(restored.s.normal.thorn&&restored.s.rescued.thorn);assert.equal(restored.s.zone,'vale');});
test('Second succession death automatically selects last unused class; third is terminal across reload',()=>{const c=fresh(.9,{succession:true});c.die();c.successor('mage');c.die();assert.equal(c.hero.class,'ranger');assert(!c.s.challenge.pending);assert.deepEqual(c.s.challenge.fallen,['paladin','mage']);c.die();assert(c.s.challenge.gameOver);const restored=Campaign.restore(c.snapshot());const time=restored.s.time;restored.tick(.1);assert.equal(restored.s.time,time);assert(!restored.successor('paladin'));});
test('Malformed saves reject contradictory succession and peace facts without mutating current state',()=>{const c=fresh(),before=c.snapshot();for(const mutate of [s=>s.hero.gold=-1,s=>s.hero.skills[1]=99,s=>s.challenge.fallen=['paladin','paladin'],s=>s.challenge.pending=true,s=>s.phase='peace',s=>s.party[0].hp=1e20,s=>s.earlyRoll.crypt=true,s=>s.zones.vale.enemies[0].home.x=Infinity]){const s=c.snapshot();mutate(s);assert.throws(()=>Campaign.restore(s));assert.deepEqual(c.snapshot(),before);}});
console.log('\n'+passed+' expanded campaign checks passed.');
