'use strict';
const assert=require('node:assert/strict'),Campaign=require('../src/prototype/engine.js');
let routes=0;
for(const region of Campaign.data.regions){const c=new Campaign();c.enter(region.id);const z=c.zone(),i=c.regionIndex(),field=c.fieldCenter(i),town={x:Campaign.data.towns[i][0],y:Campaign.data.towns[i][1]},fieldBoss=Campaign.data.bosses.find(b=>b.region===region.id&&b.kind==='field'),boss=z.enemies.find(e=>e.type==='boss'&&e.family===fieldBoss.id&&e.form==='normal');assert.equal(z.roadVersion,region.id==='frontier'?11:10);assert.equal(z.outdoorOccupationVersion,2);assert(boss);assert(Math.hypot(boss.home.x-field.x,boss.home.y-field.y)<1,region.id+' field boss uses the authored outer compound');assert(Math.hypot(field.x-town.x,field.y-town.y)>700,region.id+' field boss compound stays well away from town');const freePacks=[...new Set(z.enemies.filter(e=>e.type==='mob'&&e.pack&&!e.guard&&!e.mini&&!e.site&&!e.summon&&!e.nightOnly&&e.form==='normal').map(e=>e.pack))];if(freePacks.length>1){const centers=freePacks.map(pack=>{const es=z.enemies.filter(e=>e.pack===pack);return {x:es.reduce((n,e)=>n+e.home.x,0)/es.length,y:es.reduce((n,e)=>n+e.home.y,0)/es.length};});assert(Math.max(...centers.map(p=>p.x))-Math.min(...centers.map(p=>p.x))>250||Math.max(...centers.map(p=>p.y))-Math.min(...centers.map(p=>p.y))>250,region.id+' ordinary patrols are spread across the region instead of one central line');}for(const path of z.roads){for(let j=1;j<path.length;j++){assert(c.clearSegment(path[j-1],path[j]),region.id+' road intersects collision');const a=path[j-1],b=path[j],d=Math.hypot(b.x-a.x,b.y-a.y);for(let n=0;n<=d;n+=10){const p={x:a.x+(b.x-a.x)*n/d,y:a.y+(b.y-a.y)*n/d};const obstruction=z.props.find(q=>!q.roadTrace&&Math.hypot(p.x-q.x,p.y-q.y)<(q.r||0)+40);assert(!obstruction,region.id+' road edge obstructed by '+JSON.stringify(obstruction)+' near '+JSON.stringify(p));}}
 for(const reverse of [false,true]){const points=reverse?[...path].reverse():path;c.hero.x=points[0].x;c.hero.y=points[0].y;const target=points.at(-1);delete c.hero.path;c.hero.routeAge=0;for(let frame=0;frame<1800&&Math.hypot(c.hero.x-target.x,c.hero.y-target.y)>25;frame++)c.follow(c.hero,target,300,.1,20);assert(Math.hypot(c.hero.x-target.x,c.hero.y-target.y)<=25,region.id+' route stalls '+JSON.stringify(target));routes++;}
 }
 if(region.id==='frontier'){const traces=z.props.filter(p=>p.roadTrace);assert(traces.length>=2,'Frontier keeps authored road wear/repair traces');assert(traces.every(p=>p.decorative&&(p.r||0)===0),'road traces never become collision geometry');}
 const s=c.snapshot();delete s.zones[region.id].roadVersion;s.zones[region.id].roads=[];s.hero.gold=777;const restored=Campaign.restore(s);assert.equal(restored.hero.gold,777);assert.equal(restored.zone().roadVersion,region.id==='frontier'?11:10);assert(restored.zone().roads.length);}
// A clear destination across an obstructed cell edge must never create a route through it.
const c=new Campaign();c.zone().props.push({id:'test-obstacle',x:350,y:350,r:24,icon:'🪨'});const a={x:300,y:350},b={x:400,y:350},path=c.route(a,b);let prev=a;assert(path.length);for(const p of path){assert(c.clearSegment(prev,p));prev=p;}const actor={...a};for(let n=0;n<200;n++)c.follow(actor,b,300,.1,10);assert(Math.hypot(actor.x-b.x,actor.y-b.y)<=10+1e-6);
console.log('PASS '+routes+' main-road journeys in both directions, clear road edges, legacy-road migration and obstacle-edge movement');
