const assert=require('assert/strict'),E=require('../src/rts-engine.js');
let count=0;function test(name,fn){try{fn();console.log('PASS '+name);count++;}catch(e){console.error('FAIL '+name,e.stack);process.exitCode=1;}}
function tick(s,seconds){for(let i=0;i<Math.ceil(seconds/.05);i++)E.update(s,.05);}
function peaceful(s){s.enemies.forEach(e=>{e.hp=0;});}
test('RTS selections, group formation and context orders are independent',()=>{const s=E.create();E.select(s,s.units[0]);assert.deepEqual(s.selected,[1]);E.select(s,s.units[1],true);assert.deepEqual(s.selected,[1,2]);E.all(s);E.order(s,{x:400,y:200});assert.equal(new Set(s.units.map(u=>u.order.x)).size,3);E.stop(s);assert(s.units.every(u=>u.order===null));E.select(s,s.units[0]);E.order(s,s.nodes[0]);assert.equal(s.units[0].order.kind,'gather');assert.equal(s.units[1].order,null);});
test('Gathering deposits real resources and depletes the source without duplication',()=>{const s=E.create();peaceful(s);s.nodes[0].amount=24;E.select(s,s.units[0]);E.order(s,s.nodes[0]);tick(s,35);assert.equal(s.gold,104);assert.equal(s.nodes[0].amount,0);assert.equal(s.units[0].carry,0);tick(s,5);assert.equal(s.gold,104);});
test('Construction requires a worker, resources and free ground; training queues pay once',()=>{const s=E.create();peaceful(s);assert.equal(E.build(s,{x:320,y:280}),false);E.select(s,s.units[0]);assert.equal(E.build(s,{x:780,y:100}),false);assert.equal(s.gold,80);assert.equal(E.build(s,{x:320,y:280}),true);assert.equal(s.gold,30);tick(s,10);assert.equal(s.buildings[0].progress,4);E.select(s,s.buildings[0]);assert.equal(E.train(s),true);assert.equal(E.train(s),false);assert.equal(s.gold,0);tick(s,4);assert.equal(s.units.length,4);});
test('Routes cross bridges and avoid river and rock collisions',()=>{const s=E.create();peaceful(s);E.select(s,s.units[2]);E.order(s,{x:950,y:650});for(let i=0;i<500;i++){E.update(s,.05);assert(E.walkable(s.units[2]),JSON.stringify(s.units[2]));}assert(Math.hypot(s.units[2].x-950,s.units[2].y-650)<5);});
test('Town recovery rewards once and unlocks frontier NPC support',()=>{const s=E.create();s.selectedNPC='frontRecruit';assert.equal(E.npcAction(s),false);s.camp.hp=0;s.units[2].x=900;s.units[2].y=660;peaceful(s);E.update(s,.05);assert.equal(s.gold,130);assert(s.towns[1].owned);E.update(s,.05);assert.equal(s.gold,130);assert(E.npcAction(s));assert.equal(s.gold,85);});
test('NPC healing conserves resources at full health; weapon upgrades cannot stack',()=>{const s=E.create();s.selectedNPC='heal';assert.equal(E.npcAction(s),false);assert.equal(s.gold,80);s.units[0].hp=20;assert(E.npcAction(s));assert.equal(s.units[0].hp,70);s.gold=100;s.selectedNPC='upgrade';assert(E.npcAction(s));assert.equal(s.gold,40);assert.equal(E.npcAction(s),false);assert.equal(s.gold,40);});
test('Dark lord telegraphs area damage and combat kills grant a single reward',()=>{const s=E.create(),boss=s.enemies[5];s.enemies.slice(0,5).forEach(e=>e.hp=0);s.units[2].x=boss.x-30;s.units[2].y=boss.y;boss.burst=0;E.update(s,.05);assert(boss.warning>0);const before=s.units[2].hp;s.units[2].x=boss.x-200;s.units[2].order=null;tick(s,1.3);assert.equal(s.units[2].hp,before);assert.equal(boss.warning,0);boss.x=s.units[2].x+30;boss.warning=.05;E.update(s,.05);assert(s.units[2].hp<220);const p=E.create();p.enemies[0].x=220;p.enemies[0].y=250;p.enemies[0].hp=1;E.select(p,p.units[2]);E.order(p,p.enemies[0]);tick(p,1);assert.equal(p.enemies[0].hp,0);assert.equal(p.gold,90);tick(p,1);assert.equal(p.gold,90);});
test('Victory requires both camps, a barracks, frontier and all enemies; defeat freezes',()=>{const s=E.create();peaceful(s);s.camp.hp=s.fortress.hp=0;s.towns[1].owned=true;E.update(s,.05);assert.equal(s.result,null);s.buildings.push({id:5,x:300,y:250,progress:4,queue:0});E.update(s,.05);assert.equal(s.result,'victory');const t=s.time;tick(s,1);assert.equal(s.time,t);const d=E.create();d.units.forEach(u=>u.hp=0);E.update(d,.05);assert.equal(d.result,'defeat');});
test('RTS save restores progress safely and stops orders; bad saves are rejected',()=>{const s=E.create();E.all(s);E.order(s,s.nodes[0]);const restored=E.restore(JSON.stringify(s));assert(restored);assert.equal(restored.gold,80);assert(restored.units.every(u=>u.order===null));assert.deepEqual(restored.selected,[]);assert.equal(E.restore('{'),null);s.units[0].hp=-1;assert.equal(E.restore(JSON.stringify(s)),null);});
test('Full prototype campaign can gather, recruit, cross river and defeat both bosses',()=>{const s=E.create();E.select(s,s.units[0]);assert(E.build(s,{x:310,y:280}));tick(s,8);E.select(s,s.units[1]);E.order(s,s.nodes[0]);tick(s,70);assert(s.gold>=180);s.selectedNPC='upgrade';assert(E.npcAction(s));s.selectedBuilding=s.buildings[0].id;for(let i=0;i<4;i++){assert(E.train(s));tick(s,3.1);}const fighters=()=>s.units.filter(u=>u.hp>0&&u.type!=='worker').map(u=>u.id);
 for(const enemy of s.enemies.slice(0,3)){s.selected=fighters();E.order(s,enemy);tick(s,20);assert.equal(enemy.hp,0);}
 s.selected=fighters();E.order(s,s.camp);tick(s,15);assert.equal(s.camp.hp,0);s.selected=fighters();E.order(s,s.towns[1]);tick(s,25);assert(s.towns[1].owned);
 for(const enemy of s.enemies.slice(3)){s.selected=fighters();E.order(s,enemy);tick(s,20);assert.equal(enemy.hp,0);}
 s.selected=fighters();E.order(s,s.fortress);tick(s,15);assert.equal(s.result,'victory');});
test('Recruits from a riverside barracks spawn on walkable ground',()=>{const s=E.create();peaceful(s);s.buildings.push({id:4,x:710,y:400,progress:4,queue:.01});s.nextId=5;tick(s,.05);assert(E.walkable(s.units[3]));});
test('Deployment packages both RPG and RTS entry points',()=>{const fs=require('fs'),path=require('path');const workflow=fs.readFileSync(path.join(__dirname,'../.github/workflows/pages.yml'),'utf8');assert.match(workflow,/cp index\.html rts\.html manifest\.webmanifest sw\.js _site\//);});
console.log(`\n${count} RTS checks passed.`);
