'use strict';
const assert=require('node:assert/strict'),C=require('../src/prototype/engine');
const fresh=()=>new C('normal','paladin',()=>.9),services=c=>Object.values(c.s.zones).flatMap(z=>z.npcs.filter(n=>['teacher','smith','alchemist'].includes(n.kind)).map(n=>n.family));
for(const captive of C.data.bosses.filter(b=>b.captive)){const c=fresh();for(const r of C.data.regions)c.enter(r.id);assert.deepEqual(services(c),[]);assert(!c.rescue(captive.id));c.s.keys[captive.id]=true;assert(c.rescue(captive.id));assert.deepEqual(Object.keys(c.s.rescued),[captive.id]);assert.deepEqual(services(c),[captive.id]);const restored=C.restore(c.snapshot());assert.deepEqual(services(restored),[captive.id]);assert(!restored.rescue(captive.id));console.log('PASS only '+captive.captive+' enters town after their own rescue, including reload');}
{const final=new C();assert.equal(final.boss('darklord').captive,null);assert(!final.rescue('darklord'));console.log('PASS final Dark Lord has no specialist captive');}
const legacy={version:2,player:{heroClass:'mage',level:7,gold:500,xp:0,spellLevels:{1:2,2:3}},dungeonCleared:{crypt:true},bossDefeated:false,inventory:[]};const c=C.migrate(legacy);assert.deepEqual(Object.keys(c.s.rescued),[]);assert.deepEqual(services(c),[]);assert(c.s.keys.crypt);assert.equal(c.hero.skills[1],3);assert(!c.learn(5,'ridge'));assert(!c.gear('mine','weapon'));assert(!c.buyPotion('health',true));assert(!c.rescue('unknown'));
const old=c.snapshot();delete old.legacyRescueAuditVersion;for(const id of ['thorn','mire','ridge','warlord','citadel','crypt','mine','abyss','darklord'])old.rescued[id]=true;old.zones.vale.npcs.push({id:'service-thorn',kind:'teacher',family:'thorn',x:175,y:245,name:'Mira'});const repaired=C.restore(old);assert(!repaired.s.rescued.thorn);assert(!repaired.s.rescued.ridge);assert(!services(repaired).includes('thorn'));assert(repaired.s.rescued.crypt,'proven legacy victory must not be revoked');assert.equal(repaired.hero.skills[1],3);
const state=fresh().snapshot();state.zones.vale.npcs.push({id:'service-crypt',kind:'smith',family:'crypt',x:240,y:245,name:'Borin'});assert.deepEqual(services(C.restore(state)),[]);
console.log('PASS legacy imports no longer blanket-unlock services; corrupted old unlocks and stray town service NPCs are repaired');
