/* Browser shell. Saved campaign rules are independent of this UI. */
(function(){
'use strict';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d'),D=Campaign.data;
const profileKey='azeroth-v4-profile',saveKey=mode=>'azeroth-v4-'+mode;
let profile={nightmareUnlocked:false,activeMode:'normal',audio:{...PrototypeAudio.defaults}},game,menu=null,menuIndex=0,buttons=[],keys={},joy={x:0,y:0},cursor={x:0,y:0},squadMode=false,selection=['hero'],targetId=null,last=performance.now(),saveTimer=0,hudTimer=0,focused=true,paused=false,autoAttack=false,footstepTimer=0;
try{const p=JSON.parse(localStorage.getItem(profileKey)||'null');if(p){profile.nightmareUnlocked=p.nightmareUnlocked===true;profile.activeMode=p.activeMode==='nightmare'?'nightmare':'normal';profile.audio=p.audio||profile.audio;}}catch(_){}
const audio=new PrototypeAudio(profile.audio);
let appRegistration=null,appUpdateReady=false,appReloadRequested=false;
async function updateApp(){if(!appRegistration)return;if(!save())return;paused=true;clearInput();audio.setPaused(true);status('Checking for a game update…');try{await appRegistration.update();if(appRegistration.waiting){appReloadRequested=true;appRegistration.waiting.postMessage({type:'SKIP_WAITING'});}else{paused=false;status('No update waiting. Check again shortly.');}}catch(_){paused=false;status('Update unavailable. Your saved run is safe.');}}
function status(text){$('status').textContent=text;}
function persistProfile(){try{localStorage.setItem(profileKey,JSON.stringify(profile));return true;}catch(_){status('Local storage unavailable. Export before closing.');return false;}}
function save(){try{localStorage.setItem(saveKey(game.s.mode),JSON.stringify(game.snapshot()));profile.activeMode=game.s.mode;if(game.peace)profile.nightmareUnlocked=true;persistProfile();status('Saved locally · export for a backup');return true;}catch(_){status('Saving failed. Export your run before closing.');return false;}}
function load(mode){try{const raw=localStorage.getItem(saveKey(mode));if(raw){game=Campaign.restore(JSON.parse(raw));return true;}}catch(_){status('Saved run unavailable. Import a backup.');}return false;}
let loaded=load(profile.activeMode);if(!loaded){game=new Campaign();try{const old=localStorage.getItem('azeroth-chronicles-prototype-save-v2');if(old){const candidate=Campaign.migrate(JSON.parse(old));localStorage.setItem('azeroth-v2-original-backup',old);game=candidate;loaded=true;save();}}catch(_){status('Legacy save retained unchanged. Import a valid export to migrate.');}}
let started=loaded;
window.Prototype={get game(){return game;},audio,save,openMenu,closeMenu,get profile(){return profile;},get paused(){return paused||!!menu||!focused||document.hidden;}};
function resize(){canvas.width=innerWidth;canvas.height=innerHeight;cursor={x:innerWidth*.65,y:innerHeight*.5};}resize();addEventListener('resize',resize);
function iso(x,y){return {x:(x-y)*.76,y:(x+y)*.27};}
function offset(){const p=iso(game.hero.x,game.hero.y);return {x:canvas.width*(canvas.width<600?.69:.6)-p.x,y:canvas.height*.5-p.y};}
function screen(e){const p=iso(e.x,e.y),o=offset();return {x:p.x+o.x,y:p.y+o.y};}
function world(x,y){const o=offset(),xx=x-o.x,yy=y-o.y;return {x:(xx/.76+yy/.27)/2,y:(yy/.27-xx/.76)/2};}
function activePlay(){return started&&!paused&&!menu&&focused&&!document.hidden&&!game.s.challenge.pending&&!game.s.challenge.gameOver;}
function help(){openMenu('Controls','Move: WASD or arrows; Q: hold sprint. Skills: 1–5, Space (6), Shift (7), B (8). E: interact or select; F: confirm or order. Tab: squad cursor; backquote: select all. R/I: inventory; C: talents; X: skills; T/J: quests; Z: map; P/V: pause; G: this help; Escape: menu. In menus use W/S or the joystick, then F or Confirm. On touch, Interact becomes Select in squad mode.',[action('Back to game',closeMenu)]);}
function clearInput(){if(typeof Sprint!=='undefined')Sprint.release();keys={};joy={x:0,y:0};autoAttack=false;}
function action(label,fn,detail='',disabled=false){return {label,action:fn,detail,disabled};}
function openMenu(title,description='',actions=[]){clearInput();menu={title,description,actions};menuIndex=0;document.body.classList.add('menu-open');$('modal').hidden=false;$('modal-title').textContent=title;$('modal-description').textContent=description;renderActions();}
function renderActions(){const host=$('modal-actions');host.replaceChildren();buttons=[];for(const a of menu.actions){const b=document.createElement('button');b.textContent=a.label;b.disabled=a.disabled===true;if(a.detail){const span=document.createElement('span');span.className='detail';span.textContent=a.detail;b.append(span);}b.onclick=()=>{audio.unlock();a.action();if(started)save();updateHUD();};host.append(b);buttons.push(b);}highlight();}
function highlight(){buttons.forEach((b,i)=>b.classList.toggle('selected',i===menuIndex));buttons[menuIndex]?.scrollIntoView({block:'nearest'});}
function closeMenu(){if(!started)return;if(game.s.challenge.pending||game.s.challenge.gameOver)return;menu=null;$('modal').hidden=true;document.body.classList.remove('menu-open');clearInput();}
$('close-button').onclick=()=>{audio.unlock();if(!game.s.endingAck&&game.peace){game.s.endingAck=true;save();}closeMenu();};
function exportJSON(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function start(mode,heroClass,succession){if(mode==='nightmare'&&!profile.nightmareUnlocked)return;game=new Campaign(mode,heroClass,Math.random,{succession});started=true;if(typeof Sprint!=='undefined')Sprint.reset();selection=['hero'];squadMode=false;paused=false;profile.activeMode=mode;save();closeMenu();updateHUD();}
function chooseClass(mode,succession){if(succession===undefined){openMenu('Challenge condition','Succession is optional. Each fallen class is lost for this run; after three class deaths the run ends. World progress and gold pass to a level 1 successor.',[action('Standard death and refuge recovery',()=>chooseClass(mode,false)),action('Succession challenge',()=>chooseClass(mode,true))]);return;}
 openMenu('New '+(mode==='nightmare'?'Nightmare':'Normal')+' adventure','The Dark Lord’s armies have imprisoned the people who teach and equip heroes. Rescue them, learn your class skills and bring peace to the world. Start with one skill.',Object.entries(Campaign.classes).map(([id,c])=>action(c.icon+' '+id,()=>{let exists=false;try{exists=!!localStorage.getItem(saveKey(mode));}catch(_){}if(exists&&!confirm('Replace the existing '+mode+' run? Export it first to keep it.'))return;start(mode,id,succession);},id==='paladin'?'Melee, healing and brief immunity':id==='mage'?'Ranged magic, mana recovery and barriers':'Ranged bow, healing and mobility')));}
function openMain(){openMenu('Adventure menu','WASD moves. E interacts. F confirms. Tab changes hero / squad cursor. Skills: 1–5, Space, Left Shift, B. Q is unavailable.',[
 action('Continue',()=>{paused=false;closeMenu();}),...(appRegistration?[action(appUpdateReady?'Install available game update':'Check for game update',updateApp)]:[]),action('Controls and help',help),action('Map and travel routes',showMap),action('Quest journal',()=>quests(false)),action('Skills and teachers',skillBook),action('Inventory and supplies',inventory),action('Companions and construction',partyMenu),action('Talents',talents),action('Sound settings',soundMenu),action(paused?'Resume play':'Pause play',()=>{paused=!paused;closeMenu();}),action('Save run',()=>{save();closeMenu();}),action('Export save',()=>exportJSON(game.snapshot(),'Azeroth_Chronicles_'+game.s.mode+'.json')),action('Import save',()=>$('import-file').click()),action('Export playtest report',()=>exportJSON({version:'0.7.4-prototype',mode:game.s.mode,phase:game.s.phase,hero:game.hero,statistics:game.s.statistics},'Azeroth_Playtest_Report.json')),action('New Normal game',()=>chooseClass('normal')),action('New game in Nightmare Mode',()=>chooseClass('nightmare'),'Unlocked by the peaceful ending',!profile.nightmareUnlocked),action('Load other mode run',()=>{const mode=game.s.mode==='normal'?'nightmare':'normal';if(load(mode)){save();closeMenu();}else game.say('No saved '+mode+' run yet.');})]);}
$('menu-button').onclick=()=>{audio.unlock();if(game.s.challenge.pending)successionMenu();else if(game.s.challenge.gameOver)gameOver();else openMain();};
function ending(){profile.nightmareUnlocked=true;persistProfile();openMenu('Peace for everyone','The evil is defeated. Every dungeon guardian has fallen. The war is over for people and creatures alike.\n\nCreatures are neutral and cannot harm or be harmed. The reclaimed dungeons are their homes.',[action('Continue in the peaceful world',()=>{game.s.endingAck=true;save();closeMenu();}),action('New game in Nightmare Mode',()=>{game.s.endingAck=true;save();chooseClass('nightmare');}),action('Export completed run',()=>exportJSON(game.snapshot(),'Azeroth_Chronicles_Completed.json'))]);}
function successionMenu(){openMenu('Choose your successor','The '+game.hero.class+' has fallen permanently. Gold, rescues, quests and boss progress survive. Your successor starts at level 1 in Millhaven and must learn their skills.',Object.entries(Campaign.classes).filter(([id])=>!game.s.challenge.fallen.includes(id)).map(([id,c])=>action(c.icon+' '+id+' successor',()=>{game.successor(id);save();closeMenu();})));}
function gameOver(){openMenu('The last successor has fallen','All three classes have fallen. This run is over. Its progress remains available for export; continuing it is disabled.',[action('Export final run',()=>exportJSON(game.snapshot(),'Azeroth_Succession_Game_Over.json')),action('Start a new Normal run',()=>chooseClass('normal')),action('Start a new Nightmare run',()=>chooseClass('nightmare'),'',!profile.nightmareUnlocked)]);}
$('import-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('too large');const data=JSON.parse(await file.text()),candidate=data.version===2?Campaign.migrate(data):Campaign.restore(data);localStorage.setItem(saveKey(candidate.s.mode),JSON.stringify(candidate.snapshot()));game=candidate;started=true;profile.activeMode=game.s.mode;if(game.peace)profile.nightmareUnlocked=true;persistProfile();closeMenu();status('Imported successfully.');}catch(_){status('Invalid import. Your current run was kept intact.');}e.target.value='';};
function nearestNPC(){return [...game.visibleNPCs(),...game.zone().nodes.filter(n=>n.amount>0)].filter(n=>Math.hypot(n.x-game.hero.x,n.y-game.hero.y)<115).sort((a,b)=>Math.hypot(a.x-game.hero.x,a.y-game.hero.y)-Math.hypot(b.x-game.hero.x,b.y-game.hero.y))[0];}
function interact(){const n=nearestNPC();if(!n){game.say('Find a marked person or place nearby. Use the map.');return;}if(['rest','cage','bundle','landmark','dungeon','exit','fountain','resource','mini'].includes(n.kind)){game.interact(n);save();updateHUD();return;}if(n.kind==='teacher')teacher(n);else if(n.kind==='smith')smith(n);else if(n.kind==='supplier'||n.kind==='alchemist')supplier(n);else if(n.kind==='recruiter')partyMenu();else if(n.kind==='quests')quests(true);else if(n.kind==='transport'){const i=game.regionIndex(),r=D.regions[i],target=D.regions[i+n.direction],cost=n.direction===1?(game.s.recovery[r.id]?0:r.fare):0;openMenu(n.name,'Fare '+cost+'g. Paid outbound travel includes free return. Health, mana and supplies are preserved.',[action('Travel to '+target.name,()=>{if(game.travel(n.direction))closeMenu();})]);}}
$('interact-button').onclick=()=>{audio.unlock();if(activePlay())squadMode?select():interact();};
function teacher(n){const catalog=game.teacherCatalog(n.family),cap=catalog.maxRank,next=Object.keys(Campaign.rules.teachers).find(id=>Campaign.rules.teachers[id].maxRank>cap);openMenu(n.name,(next?'Higher ranks: rescue '+game.boss(next).captive+' in '+D.regions.find(r=>r.id===game.boss(next).region).name+'. ':'Maximum training rank available here. ')+'Learning a new skill and training its rank are separate. This instructor trains supported skills through rank '+cap+'.',D.skills.filter(s=>game.hero.skills[s[0]-1]?catalog.train.includes(s[0]):catalog.learn.includes(s[0])).map(s=>{const rank=game.hero.skills[s[0]-1],cost=rank?s[5]*rank:s[3],level=rank?Math.max(s[2],2*(rank+1)-1):s[2];return action((rank?'Train ':'Learn ')+s[1]+' · '+cost+'g',()=>{rank?game.upgrade(s[0],n.family):game.learn(s[0],n.family);teacher(n);},'Skill '+s[0]+' · Rank '+rank+' · Hero level '+level,rank>=cap||game.hero.level<level||game.hero.gold<cost); }));}
function skillBook(){openMenu('Skills and teachers','Locked skills require paid instruction from a rescued teacher.',D.skills.filter(s=>game.skillRevealed(s[0])).map(s=>action('Skill '+s[0]+' '+s[1]+' · Rank '+game.hero.skills[s[0]-1],()=>{},s[0]===1?'Always available':s[3]+'g · Level '+s[2]+' · '+game.boss(s[4]).captive+' · '+D.regions.find(r=>r.id===game.boss(s[4]).region).name,true)));}
function supplier(n){const advanced=n.kind==='alchemist';openMenu(n.name,'Per bottle. Potions share a 10 second cooldown and are conserved at full resources.',[
 action('Health potion · '+(advanced?50:20)+'g',()=>{game.buyPotion('health',advanced);supplier(n);},'Restores '+(advanced?150:60)+' health'),action('Mana potion · '+(advanced?40:15)+'g',()=>{game.buyPotion('mana',advanced);supplier(n);},'Restores '+(advanced?100:40)+' mana'),...(advanced?[action('Preparation tonic · 70g',()=>{game.buyPotion('tonic',true);supplier(n);},'10% maximum health until death or refuge rest. Does not stack.')]:[])]);}
function smith(n){const tier={crypt:1,mine:2,abyss:3,darklord:4}[n.family],weapon=[0,100,450,1000,2000][tier],armor=[0,80,300,700,1200][tier];openMenu(n.name,'Equipment replaces the earlier tier in its slot. Bonuses do not stack.',[
 action('Weapon tier '+tier+' · '+weapon+'g',()=>{game.gear(n.family,'weapon');smith(n);},'+'+[0,15,35,55,70][tier]+' power'),action('Armor tier '+tier+' · '+armor+'g',()=>{game.gear(n.family,'armor');smith(n);},'+'+[0,5,12,20,28][tier]+' armor'),action('Reforge weapon · '+Math.ceil(weapon/2)+'g',()=>{game.gear(n.family,'weapon',true);smith(n);},'+5 power once per tier'),action('Reforge armor · '+Math.ceil(armor/2)+'g',()=>{game.gear(n.family,'armor',true);smith(n);},'+3 armor once per tier')]);}
function inventory(){openMenu('Inventory','Gold '+Math.floor(game.hero.gold)+' · Weapon tier '+game.hero.weapon+' · Armor tier '+game.hero.armorTier,[action('Use health potion',()=>{game.potion('health');inventory();},'Saved bottles '+(game.hero.legacyPotions?.filter(p=>p.type==='health').length||0)+' · Normal '+(game.hero.potions.health||0)+' · Greater '+(game.hero.potions.greater_health||0)),action('Use mana potion',()=>{game.potion('mana');inventory();},'Saved bottles '+(game.hero.legacyPotions?.filter(p=>p.type==='mana').length||0)+' · Normal '+(game.hero.potions.mana||0)+' · Greater '+(game.hero.potions.greater_mana||0)),...Object.keys(Campaign.legacyWeapons).filter(name=>game.s.legacyInventory?.includes(name)).map(name=>action('Equip '+name,()=>{game.equipLegacy(name);inventory();},'Saved weapon · +'+Campaign.legacyWeapons[name]+' power')), ...(game.hero.weapon?[action('Equip current weapon tier '+game.hero.weapon,()=>{game.hero.legacyEquipped=false;inventory();})]:[])]);}
function partyMenu(){const town=!game.isDungeon()&&Math.hypot(game.hero.x-D.towns[game.regionIndex()][0],game.hero.y-D.towns[game.regionIndex()][1])<200;openMenu('Companions','Six living companions maximum. Town recruitment and recovery require a refuge. Workers gather finite resources and build barracks.',[
 action(game.s.holdFire?'Allow companion attacks':'Hold fire',()=>{game.s.holdFire=!game.s.holdFire;partyMenu();}),action('Select whole party · Backtick',()=>{selection=['hero',...game.s.party.filter(u=>u.hp>0).map(u=>u.id)];squadMode=true;closeMenu();}),...['worker','soldier','archer'].map(type=>action('Recruit '+type+' · '+{worker:35,soldier:70,archer:100}[type]+'g',()=>{game.recruit(type);partyMenu();},'',!town)),action('Recover fallen companion · 40g',()=>{game.recover();partyMenu();},'',!town),action('Build barracks · 120g',()=>{game.build();partyMenu();}),...game.zone().buildings.map(b=>action('Train soldier · 60g',()=>{game.train(b.id);partyMenu();},b.progress<4?'Under construction':b.queue>0?'Training':'Ready')), ...game.zone().nodes.filter(n=>n.amount>0).map(n=>action('Gather '+n.name+' '+n.icon,()=>{game.gather(n.id);closeMenu();},Math.floor(n.amount)+' gold remaining · guarded expedition · workers return automatically')),...game.s.party.map(u=>action(u.icon+' '+u.type+' · '+Math.ceil(u.hp)+' / '+u.maxHp,()=>{selection=[u.id];squadMode=true;closeMenu();},u.hp<=0?'Fallen':'Select companion',u.hp<=0))]);}
function talents(){openMenu('Talents','Available points '+game.hero.talentPoints,['Attack power +8','Mana regeneration +2','Maximum health +30','Movement speed +40'].map((name,i)=>action(name+' · '+game.hero.talents[i],()=>{game.talent(i);talents();})));}
function quests(atBoard){openMenu(atBoard?'Local quests':'Quest journal','Discovery and rescue progress can predate acceptance. Patrol kills count while active. Rewards pay once.',game.questDefs().filter(q=>!atBoard||q.region===game.definition().id).map(q=>{const p=game.s.quests[q.id];return action(q.name+' · '+(p?.paid?'Paid':p?.closedByPeace?'Resolved by peace':p?.done?'Ready':p?.active?'Active':'Available'),()=>{if(!atBoard)return;if(p?.done)game.claim(q.id);else game.accept(q.id);quests(atBoard);},q.objective+' · '+q.gold+'g / '+q.xp+' XP'+' · '+game.questProgress(q),!atBoard||p?.paid||p?.closedByPeace); }));}
function soundMenu(){const s=audio.settings;openMenu('Music and sound','Independent volumes. Preferences survive new games.',[action(s.muted?'Unmute all sound':'Mute all sound',()=>{audio.setSettings({muted:!s.muted});profile.audio={...audio.settings};persistProfile();soundMenu();}),...['master','music','ambience','effects'].flatMap(key=>[action(key+' − · '+Math.round(s[key]*100)+'%',()=>{audio.setSettings({[key]:s[key]-.1});profile.audio={...audio.settings};persistProfile();soundMenu();}),action(key+' +',()=>{audio.setSettings({[key]:s[key]+.1});profile.audio={...audio.settings};persistProfile();soundMenu();})])]);}
function showMap(){const r=game.definition();openMenu(r.name+' map',r.biome+'\nTransport: '+D.regions.map(r=>r.name).join(' → ')+'\nChoose a marked destination to walk there. Region boundaries require transport.',[...game.visibleNPCs(),...game.zone().nodes.filter(n=>n.amount>0)].map(n=>action(n.icon+' '+n.name,()=>{game.hero.order={type:'move',x:n.x,y:n.y};closeMenu();},Math.round(n.x)+', '+Math.round(n.y)+(n.kind==='landmark'?' · '+game.siteDescription(n):n.kind==='mini'?' · '+game.miniStatus(n.mini):n.kind==='resource'?' · '+(n.mini&&!game.peace&&!game.miniCleared(n.mini)?'Clear guardians to unlock':'Guarded worker expedition'):n.kind==='bundle'?' · Collect with Interact':''))));
 const map=document.createElement('canvas');map.width=420;map.height=280;const c=map.getContext('2d'),size=game.isDungeon()?1500:r.size;c.fillStyle=D.colors[game.regionIndex()];c.fillRect(0,0,420,280);for(let x=0;x<size;x+=50)for(let y=0;y<size;y+=50)if(game.blocked(x,y,game.zoneId,0)){c.fillStyle=game.isDungeon()?'#78807d':'#355d72';c.fillRect(x/size*420,y/size*280,50/size*420+1,50/size*280+1);}for(const n of [...game.visibleNPCs(),...game.zone().nodes.filter(n=>n.amount>0)]){c.fillStyle='#f4d797';c.fillRect(n.x/size*420-2,n.y/size*280-2,4,4);}for(const e of game.zone().enemies.filter(e=>e.hp>0)){c.fillStyle=e.neutral?'#aed6a0':'#e87b7b';c.fillRect(e.x/size*420-1,e.y/size*280-1,3,3);}c.fillStyle='#fff';c.fillRect(game.hero.x/size*420-3,game.hero.y/size*280-3,6,6);$('modal-description').append(map);}
function order(){const p=world(cursor.x,cursor.y),e=game.zone().enemies.find(e=>e.hp>0&&!e.neutral&&Math.hypot(e.x-p.x,e.y-p.y)<90);if(selection.includes('hero'))game.hero.order=e?{type:'attack',id:e.id}:{type:'move',...p};for(const u of game.s.party.filter(u=>selection.includes(u.id)))u.order=e?{type:'attack',id:e.id}:{type:'move',...p};targetId=e?.id||null;}
function select(){const p=world(cursor.x,cursor.y),u=game.s.party.find(u=>u.hp>0&&Math.hypot(u.x-p.x,u.y-p.y)<65),hero=Math.hypot(game.hero.x-p.x,game.hero.y-p.y)<60;selection=hero?['hero']:u?[u.id]:[];targetId=game.zone().enemies.find(e=>e.hp>0&&!e.neutral&&Math.hypot(e.x-p.x,e.y-p.y)<70)?.id||null;}
$('squad-button').onclick=()=>{audio.unlock();squadMode=!squadMode;clearInput();};$('order-button').onclick=()=>{audio.unlock();if(menu)buttons[menuIndex]?.click();else if(activePlay()){if(squadMode)order();else interact();}};
const skillNames=['Basic attack','Second attack','Recovery','Defense or mobility','Area attack','Frequent special','Advanced special','Final special'],icons=['ATK','HIT','HEAL','GUARD','AREA','CAST','BURST','FINAL'],skillKeys=['1','2','3','4','5','Space','Shift','B'];
for(let i=0;i<8;i++){const b=document.createElement('button');b.id='skill-'+(i+1);b.setAttribute('aria-label','Skill '+(i+1)+' '+skillNames[i]);b.innerHTML=icons[i]+'<small>'+skillKeys[i]+'</small>';b.onclick=()=>{audio.unlock();if(activePlay())game.cast(i+1,targetId);};if(i===0){b.onpointerdown=()=>{audio.unlock();if(activePlay())autoAttack=true;};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>autoAttack=false;}$('skills').append(b);}
addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;audio.unlock();const code=e.code;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab','Escape'].includes(code))e.preventDefault();if(code==='Escape'){if(game.s.challenge.pending){successionMenu();return;}if(game.s.challenge.gameOver){gameOver();return;}if(menu)closeMenu();else openMain();return;}if(menu){if(e.repeat)return;if(['KeyS','ArrowDown','KeyD'].includes(code)){menuIndex=(menuIndex+1)%Math.max(1,buttons.length);highlight();}else if(['KeyW','ArrowUp','KeyA'].includes(code)){menuIndex=(menuIndex-1+buttons.length)%Math.max(1,buttons.length);highlight();}else if(['KeyF','Enter','Space'].includes(code))buttons[menuIndex]?.click();return;}if((paused||!focused||document.hidden)&&!['KeyP','KeyV','KeyG'].includes(code))return;keys[code]=true;if(code==='KeyQ')Sprint.press('keyboard',true);if(e.repeat)return;if(code==='Tab'){squadMode=!squadMode;clearInput();}else if(code==='KeyE')squadMode?select():interact();else if(code==='KeyF')squadMode?order():interact();else if(code==='Backquote')selection=['hero',...game.s.party.filter(u=>u.hp>0).map(u=>u.id)];else if(code==='KeyP'||code==='KeyV'){paused=!paused;clearInput();}else if(code==='KeyZ')showMap();else if(code==='KeyI'||code==='KeyR')inventory();else if(code==='KeyC')talents();else if(code==='KeyX')skillBook();else if(code==='KeyG')help();else if(code==='KeyJ'||code==='KeyT')quests(false);else{const num=/Digit([1-5])/.exec(code)?.[1]||({Space:6,ShiftLeft:7,KeyB:8}[code]);if(num)game.cast(Number(num),targetId);}});
addEventListener('keyup',e=>{delete keys[e.code];if(e.code==='KeyQ')Sprint.press('keyboard',false);});
const joystick=$('joystick');let pointer=null,menuJoyTime=0;function joyUpdate(e){const r=joystick.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width*.4),dy=(e.clientY-r.top-r.height/2)/(r.height*.4),n=Math.max(1,Math.hypot(dx,dy));joy={x:dx/n,y:dy/n};$('stick').style.transform='translate('+joy.x*24+'px,'+joy.y*24+'px)';}
joystick.onpointerdown=e=>{if(pointer!==null)return;e.preventDefault();audio.unlock();pointer=e.pointerId;joystick.setPointerCapture(pointer);joyUpdate(e);};joystick.onpointermove=e=>{if(e.pointerId===pointer)joyUpdate(e);};joystick.onpointerup=joystick.onpointercancel=joystick.onlostpointercapture=e=>{if(e.pointerId===pointer){pointer=null;joy={x:0,y:0};$('stick').style.transform='';}};
canvas.onpointermove=e=>{if(e.pointerType!=='touch'&&squadMode)cursor={x:e.clientX,y:e.clientY};};canvas.onpointerdown=e=>{audio.unlock();if(!activePlay())return;const p=world(e.clientX,e.clientY);if(squadMode){cursor={x:e.clientX,y:e.clientY};e.button===2?order():select();}else{const enemy=game.zone().enemies.find(a=>a.hp>0&&!a.neutral&&Math.hypot(a.x-p.x,a.y-p.y)<80);if(enemy){targetId=enemy.id;game.hero.order={type:'attack',id:enemy.id};}else game.hero.order={type:'move',...p};}};canvas.oncontextmenu=e=>e.preventDefault();
addEventListener('blur',()=>{focused=false;clearInput();save();audio.setPaused(true);});addEventListener('focus',()=>{focused=true;last=performance.now();});document.addEventListener('visibilitychange',()=>{clearInput();last=performance.now();if(document.hidden){save();audio.setPaused(true);}});addEventListener('pagehide',save);
function updateHUD(){const h=game.hero;$('hero-stats').innerHTML=Campaign.classes[h.class].icon+' '+h.class+' · Level '+h.level+'<br><span class="health">HP '+Math.ceil(h.hp)+' / '+h.maxHp+'</span><br><span class="mana">MP '+Math.floor(h.mp)+' / '+h.maxMp+'</span><br><span class="gold">'+Math.floor(h.gold)+' gold</span> · XP '+Math.floor(h.xp)+' / '+120*h.level;$('location').textContent=game.definition().name+(game.isDungeon()?' · '+game.boss(game.zoneId).place:'')+' · '+(game.peace?'At peace':game.s.mode==='nightmare'?'Nightmare':game.night()?'Night':'Day');
 const remaining=Campaign.dungeonIds.filter(id=>!game.s.true[id]);$('objective').textContent=game.peace?'Peace for everyone. Explore the creatures’ new homes.':game.s.phase==='awakening'?'TRUE guardians remaining: '+remaining.map(id=>game.boss(id).name).join(', '):game.s.rescued.thorn?'Rescue specialists, learn skills and reach the Dark Lord. Map: Z.':'Find Thornfang and rescue Mira to learn your next skills. Map: Z.';
 $('squad-button').textContent=squadMode?'Hero control · Tab':'Squad cursor · Tab';for(let i=0;i<8;i++){const b=$('skill-'+(i+1)),rank=h.skills[i];b.classList.toggle('locked',!rank);const revealed=game.skillRevealed(i+1);b.title=(revealed?skillNames[i]:'Undiscovered skill')+(rank?' · Rank '+rank:' · Not learned');b.setAttribute('aria-label','Skill '+(i+1)+' '+(revealed?skillNames[i]:'Undiscovered')); b.querySelector('small').textContent=!rank?'Locked':h.cd[i]>0?h.cd[i].toFixed(1):skillKeys[i];}const n=nearestNPC();$('interact-button').textContent=squadMode?'Select · E':'Interact · E';$('order-button').textContent=menu?'Confirm · F':squadMode?'Order · F':'Interact · F';$('interact-button').title=n?n.name:'Find a marked person';$('message').textContent=game.messages.at(-1)||'Explore, prepare and rescue. Music starts with your first action.';}
function diamond(x,y,size,color){const p=screen({x,y});ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+size*.76,p.y+size*.27);ctx.lineTo(p.x,p.y+size*.54);ctx.lineTo(p.x-size*.76,p.y+size*.27);ctx.closePath();ctx.fill();}
function sprite(e,p){PrototypeVisuals.draw(ctx,e,p,game.regionIndex(),!!game.s.rescued[e.family]);}
function draw(){ctx.fillStyle='#0c1913';ctx.fillRect(0,0,canvas.width,canvas.height);const z=game.zone(),size=game.isDungeon()?1500:game.definition().size,i=game.regionIndex();for(let x=0;x<size;x+=80)for(let y=0;y<size;y+=80){const p=screen({x,y});if(p.x<-160||p.x>canvas.width+160||p.y<-100||p.y>canvas.height+100)continue;let color=game.isDungeon()?({crypt:'#343c39',archive:'#30464a',mine:'#44433b',abyss:'#44373b',citadel:'#3b414b'}[game.zoneId]):D.colors[i];if(game.blocked(x+40,y+40,game.zoneId,0)&&!z.props.some(p=>Math.hypot(x+40-p.x,y+40-p.y)<p.r))color=game.isDungeon()?'#737c70':i===4?'#914c30':i>=2?'#5c5b55':'#2e6170';diamond(x,y,80,color);if(game.isDungeon()&&!game.blocked(x+40,y+40,game.zoneId,0)){const q=screen({x:x+40,y:y+40});ctx.strokeStyle='#a9b7a016';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+60.8,p.y+21.6);ctx.lineTo(p.x,p.y+43.2);ctx.stroke();}}
 PrototypeVisuals.roads(ctx,z.roads||[],screen,i);
 for(const t of game.traps()){const p=screen(t),active=t.phase>=1.5&&t.phase<2.1,warning=t.phase<1.5;ctx.fillStyle=active?'#e9534bcc':warning?'#e8bd5f88':'#777b6544';ctx.strokeStyle=active?'#ffab77':warning?'#ffd580':'#9b9c7a66';ctx.lineWidth=2;ctx.beginPath();if(t.kind==='jet'){for(const [j,v]of [{x:t.x-t.length/2,y:t.y-28},{x:t.x+t.length/2,y:t.y-28},{x:t.x+t.length/2,y:t.y+28},{x:t.x-t.length/2,y:t.y+28}].entries()){const q=screen(v);j?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);}ctx.closePath();}else ctx.ellipse(p.x,p.y,t.radius*.76,t.radius*.27,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(t.kind==='spikes')for(const dx of [-12,0,12]){ctx.beginPath();ctx.moveTo(p.x+dx-4,p.y+5);ctx.lineTo(p.x+dx,p.y-(active?18:5));ctx.lineTo(p.x+dx+4,p.y+5);ctx.fill();}else if(t.kind==='seal'){ctx.strokeStyle=active?'#f6c77a':'#b4b8a0';ctx.beginPath();ctx.moveTo(p.x,p.y-7);ctx.lineTo(p.x+12,p.y);ctx.lineTo(p.x,p.y+7);ctx.lineTo(p.x-12,p.y);ctx.closePath();ctx.stroke();}}
 for(const e of z.enemies.filter(e=>e.rangedAim)){const from=screen(e),to=screen(e.rangedAim);ctx.strokeStyle='#f0d09288';ctx.lineWidth=2;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(from.x,from.y-15);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.setLineDash([]);}

 for(const e of z.enemies.filter(e=>e.telegraph)){const a=e.telegraph,p=screen(a);ctx.strokeStyle='#ffd479';ctx.fillStyle='#ea664577';ctx.lineWidth=3;
  if(a.kind==='line'||a.kind==='volley'){for(const o of a.kind==='volley'?[-.22,0,.22]:a.count===2?[-85,85]:[0]){const angle=a.angle+(a.kind==='volley'?o:0),offset=a.kind==='volley'?0:o,w=a.kind==='volley'?22:a.count===2?35:45,side={x:Math.cos(angle+Math.PI/2),y:Math.sin(angle+Math.PI/2)},from={x:a.fromX+side.x*offset,y:a.fromY+side.y*offset},to=a.kind==='volley'?{x:from.x+Math.cos(angle)*650,y:from.y+Math.sin(angle)*650}:{x:a.x+side.x*offset,y:a.y+side.y*offset};ctx.beginPath();for(const [j,q]of [{x:from.x+side.x*w,y:from.y+side.y*w},{x:to.x+side.x*w,y:to.y+side.y*w},{x:to.x-side.x*w,y:to.y-side.y*w},{x:from.x-side.x*w,y:from.y-side.y*w}].entries()){const p=screen(q);j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);}ctx.closePath();ctx.fill();ctx.stroke();}}
  else if(a.kind==='cone'||a.kind==='sector'){ctx.beginPath();ctx.moveTo(p.x,p.y);for(let j=0;j<=12;j++){const angle=a.angle-(a.kind==='sector'?.65:1.1)+j*(a.kind==='sector'?1.3:2.2)/12,q=screen({x:a.x+Math.cos(angle)*a.radius,y:a.y+Math.sin(angle)*a.radius});ctx.lineTo(q.x,q.y);}ctx.closePath();ctx.fill();ctx.stroke();}
  else for(const patch of game.attackPatches(a)){const q=screen(patch);ctx.beginPath();ctx.ellipse(q.x,q.y,patch.radius*.76,patch.radius*.27,0,0,Math.PI*2);if(a.kind!=='ring')ctx.fill();ctx.stroke();}
  ctx.fillStyle='#fff3c8';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(a.name+' · '+a.timer.toFixed(1),p.x,p.y-12);}
 for(const a of game.s.hazards){const p=screen(a);ctx.fillStyle='#db473766';ctx.strokeStyle='#f09e57';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(p.x,p.y,a.radius*.76,a.radius*.27,0,0,Math.PI*2);a.kind==='ring'?ctx.stroke():ctx.fill();}
 const entities=[...z.props.map(p=>({...p,renderKind:'prop'})),...game.visibleNPCs().map(p=>({...p,renderKind:'npc'})),...z.nodes.filter(n=>n.amount>0).map(p=>({...p,renderKind:'node'})),...z.buildings.map(p=>({...p,renderKind:'building'})),...z.enemies.filter(e=>e.hp>0).map(p=>({...p,renderKind:'enemy'})),...game.s.party.filter(u=>u.hp>0).map(p=>({...p,renderKind:'ally'})),{...game.hero,icon:Campaign.classes[game.hero.class].icon,renderKind:'hero'},...(z.escort?[{...z.escort,icon:'🧑‍🌾',name:'Supply escort',renderKind:'ally'}]:[])].sort((a,b)=>a.x+a.y-b.x-b.y);
 for(const e of entities){const p=screen(e);if(p.x<-100||p.x>canvas.width+100||p.y<-100||p.y>canvas.height+100)continue;ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(p.x,p.y+10,18,6,0,0,Math.PI*2);ctx.fill();ctx.font=(e.renderKind==='prop'?34:30)+'px system-ui';ctx.textAlign='center';let icon=e.icon;if(e.kind==='cage')icon=game.s.rescued[e.family]?'🔓':game.s.keys[e.family]||game.peace?'🗝️':'🔒';sprite(e,p);
  if(['enemy','ally','hero'].includes(e.renderKind)){if(!e.neutral){ctx.fillStyle='#111';ctx.fillRect(p.x-21,p.y-PrototypeVisuals.height(e),42,4);ctx.fillStyle=e.renderKind==='enemy'?'#e78070':'#a4d698';ctx.fillRect(p.x-21,p.y-PrototypeVisuals.height(e),42*e.hp/e.maxHp,4);}ctx.font='10px system-ui';ctx.fillStyle=e.neutral?'#dcf2c8':e.renderKind==='enemy'?'#f8cebd':'#dcebcf';ctx.fillText(e.renderKind==='enemy'?e.name+(e.neutral?' · Neutral':' · Lv '+e.level):e.renderKind==='ally'?e.type||e.name:'',p.x,p.y-PrototypeVisuals.height(e)-6);if(selection.includes(e.id)||e.renderKind==='hero'&&selection.includes('hero')||targetId===e.id){ctx.strokeStyle='#ffe089';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+8,23,9,0,0,Math.PI*2);ctx.stroke();}}
  if(e.renderKind==='npc'){if(e.kind==='mini')e.name+=game.peace?' · Peaceful':game.miniCleared(e.mini)?' · Cleared':' · Guardians';ctx.font='bold 11px system-ui';ctx.fillStyle='#ffe4a2';ctx.fillText(e.name,p.x,p.y-PrototypeVisuals.height(e)-4);}if(e.renderKind==='node'){ctx.font='10px system-ui';ctx.fillStyle='#f5e7b8';ctx.fillText(e.name+' · '+Math.floor(e.amount)+' gold',p.x,p.y-25);}}
 for(const l of game.s.loot.filter(l=>l.zone===game.zoneId)){const p=screen(l);ctx.font='20px system-ui';ctx.fillText('🪙',p.x,p.y);}for(const p of game.s.projectiles){const q=screen(p);ctx.fillStyle=p.style==='spit'?'#acd38e':p.style==='stone'?'#c5ac83':p.style==='cinder'?'#eea66a':p.source==='enemy'?'#f2d9a5':'#a5dcff';if(p.style==='arrow'){ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=2;const tail=screen({x:p.x-(p.dx||1)*20,y:p.y-(p.dy||0)*20});ctx.beginPath();ctx.moveTo(tail.x,tail.y);ctx.lineTo(q.x,q.y);ctx.stroke();}ctx.beginPath();ctx.arc(q.x,q.y,p.style==='arrow'?2:5,0,Math.PI*2);ctx.fill();}
 if(game.night()){ctx.fillStyle=game.peace?'#19243a33':'#08112a66';ctx.fillRect(0,0,canvas.width,canvas.height);}if(squadMode){ctx.strokeStyle='#ffeaa1';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(cursor.x-12,cursor.y);ctx.lineTo(cursor.x+12,cursor.y);ctx.moveTo(cursor.x,cursor.y-12);ctx.lineTo(cursor.x,cursor.y+12);ctx.stroke();}if(paused||!focused||document.hidden){ctx.fillStyle='#0006';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='bold 25px system-ui';ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText('Paused',canvas.width*.65,canvas.height*.45);}}
function frame(now){const dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;const frozen=paused||menu||!focused||document.hidden||game.s.challenge.pending||game.s.challenge.gameOver;if(menu){menuJoyTime-=dt;if(Math.abs(joy.y)>.4&&menuJoyTime<=0&&buttons.length){menuIndex=(menuIndex+(joy.y>0?1:-1)+buttons.length)%buttons.length;highlight();menuJoyTime=.3;}}audio.update(game,paused||!!menu||!focused||document.hidden||game.s.challenge.gameOver);if(!frozen){let x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+joy.x,y=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+joy.y;if(squadMode){cursor.x=Math.max(5,Math.min(canvas.width-5,cursor.x+x*440*dt));cursor.y=Math.max(5,Math.min(canvas.height-5,cursor.y+y*440*dt));x=y=0;}else if(joy.x||joy.y){const p=world(canvas.width*.5+joy.x*100,canvas.height*.5+joy.y*100),base=world(canvas.width*.5,canvas.height*.5);x=p.x-base.x;y=p.y-base.y;}const speedFactor=Sprint.tick(dt,!!(x||y||game.hero.order));game.tick(dt,{x,y,speedFactor});if(x||y||game.hero.order){footstepTimer+=dt;if(footstepTimer>.35){audio.effect('footstep');footstepTimer=0;}}if(Sprint.enabled)Sprint.hud();if(autoAttack||keys.Digit1)game.cast(1,targetId);saveTimer+=dt;if(saveTimer>=5){saveTimer=0;save();}}
 const events=game.effects.splice(0);for(const e of events)audio.effect(e.type);if(events.some(e=>['rescue','learning','upgrade','level','bossDefeat','peace','quest','questComplete','supplies','miniClear','travel','death','successor','gameOver'].includes(e.type)))save();if(events.some(e=>e.type==='peace'))ending();if(game.s.challenge.pending&&menu?.title!=='Choose your successor')successionMenu();if(game.s.challenge.gameOver&&!menu)gameOver();if(game.peace&&!game.s.endingAck&&!menu)ending();hudTimer+=dt;if(hudTimer>.15){hudTimer=0;updateHUD();}draw();requestAnimationFrame(frame);}
if(Sprint.enabled){Sprint.init();$('sprint-button').onpointerdown=()=>Sprint.press('touch',true);$('sprint-button').onpointerup=$('sprint-button').onpointercancel=$('sprint-button').onpointerleave=()=>Sprint.press('touch',false);}
updateHUD();if(!loaded)chooseClass('normal');requestAnimationFrame(frame);
if(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'){if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(appReloadRequested){appReloadRequested=false;location.reload();}});navigator.serviceWorker.register('./sw.js').then(reg=>{appRegistration=reg;function check(){appUpdateReady=!!reg.waiting;if(appUpdateReady)status('A game update is ready. Open Menu to install it.');}check();reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(worker)worker.addEventListener('statechange',check);});}).catch(()=>{});}}
})();
