/* Browser shell. Saved campaign rules are independent of this UI. */
(function(){
'use strict';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d'),D=Campaign.data;
const profileKey='azeroth-v4-profile',saveKey=mode=>'azeroth-v4-'+mode;
let profile={nightmareUnlocked:false,activeMode:'normal',audio:{...PrototypeAudio.defaults}},game,menu=null,menuIndex=0,buttons=[],keys={},joy={x:0,y:0},cursor={x:0,y:0},squadMode=false,selection=['hero'],targetId=null,last=performance.now(),saveTimer=0,hudTimer=0,focused=true,paused=false,autoAttack=false,footstepTimer=0,gateDismissed=false,criticalNoticeSeen=null,criticalNoticeUntil=0,visualFx=[];
try{const p=JSON.parse(localStorage.getItem(profileKey)||'null');if(p){profile.nightmareUnlocked=p.nightmareUnlocked===true;profile.activeMode=p.activeMode==='nightmare'?'nightmare':'normal';profile.audio=p.audio||profile.audio;}}catch(_){}
const audio=new PrototypeAudio(profile.audio);
let appRegistration=null,appUpdateReady=false,appReloadRequested=false,installPrompt=null;
async function updateApp(){if(!appRegistration)return;if(!save())return;paused=true;clearInput();audio.setPaused(true);status('Checking for a game update…');try{await appRegistration.update();const worker=appRegistration.installing;if(worker&&worker.state!=='installed'&&worker.state!=='activated')await new Promise(resolve=>{const done=()=>{worker.removeEventListener('statechange',check);clearTimeout(timer);resolve();},check=()=>{if(worker.state==='installed'||worker.state==='activated'||worker.state==='redundant')done();},timer=setTimeout(done,15000);worker.addEventListener('statechange',check);check();});if(appRegistration.waiting){appReloadRequested=true;appRegistration.waiting.postMessage({type:'SKIP_WAITING'});}else{paused=false;audio.setPaused(false);status('No update waiting. Check again shortly.');}}catch(_){paused=false;audio.setPaused(false);status('Update unavailable. Your saved run is safe.');}}
function runningAsApp(){return (window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches)||navigator.standalone===true;}
function installInstructions(){openMenu('Install on phone','Install once, then Azeroth Chronicles launches from the home screen like an app and keeps its offline cache on that device.\n\nAndroid / Chrome: use the Install button when available. If Chrome does not offer it, open the browser menu and choose Install app or Add to Home screen.\n\niPhone / iPad: open the game in Safari, tap Share, choose Add to Home Screen, then Add.',installPrompt?[action('Install Azeroth Chronicles',installApp,'Open the phone installation prompt')]:[],systemMenu);}
async function installApp(){if(runningAsApp()){status('Azeroth Chronicles is already running as an installed app.');closeMenu();return;}if(!installPrompt){installInstructions();return;}const prompt=installPrompt;installPrompt=null;try{await prompt.prompt();const choice=await prompt.userChoice;if(choice&&choice.outcome==='accepted'){status('Azeroth Chronicles installed. Open it from your home screen.');closeMenu();}else installInstructions();}catch(_){installInstructions();}}
function status(text){$('status').textContent=text;}
function persistProfile(){try{localStorage.setItem(profileKey,JSON.stringify(profile));return true;}catch(_){status('Local storage unavailable. Export before closing.');return false;}}
function save(){try{localStorage.setItem(saveKey(game.s.mode),JSON.stringify(game.snapshot()));profile.activeMode=game.s.mode;if(game.peace)profile.nightmareUnlocked=true;persistProfile();status('Saved locally · export for a backup');return true;}catch(_){status('Saving failed. Export your run before closing.');return false;}}
function load(mode){try{const raw=localStorage.getItem(saveKey(mode));if(raw){game=Campaign.restore(JSON.parse(raw));return true;}}catch(_){status('Saved run unavailable. Import a backup.');}return false;}
let loaded=load(profile.activeMode);if(!loaded){game=new Campaign();try{const old=localStorage.getItem('azeroth-chronicles-prototype-save-v2');if(old){const candidate=Campaign.migrate(JSON.parse(old));localStorage.setItem('azeroth-v2-original-backup',old);game=candidate;loaded=true;save();}}catch(_){status('Legacy save retained unchanged. Import a valid export to migrate.');}}
let started=loaded;
window.Prototype={get game(){return game;},audio,save,openMenu,closeMenu,labelVisible:worldLabelVisible,get profile(){return profile;},get paused(){return paused||!!menu||!focused||document.hidden;}};
function resize(){canvas.width=innerWidth;canvas.height=innerHeight;cursor={x:innerWidth*.65,y:innerHeight*.5};}resize();addEventListener('resize',resize);
function iso(x,y){return {x:(x-y)*.76,y:(x+y)*.27};}
function offset(){const p=iso(game.hero.x,game.hero.y);return {x:canvas.width*(canvas.width<600?.69:.6)-p.x,y:canvas.height*.5-p.y};}
function screen(e){const p=iso(e.x,e.y),o=offset();return {x:p.x+o.x,y:p.y+o.y};}
function world(x,y){const o=offset(),xx=x-o.x,yy=y-o.y;return {x:(xx/.76+yy/.27)/2,y:(yy/.27-xx/.76)/2};}
function activePlay(){return started&&!paused&&!menu&&focused&&!document.hidden&&!game.s.challenge.pending&&!game.s.challenge.gameOver;}
function desktopMouse(e){return !!(e?.isTrusted&&e.pointerType==='mouse'&&(!window.matchMedia||window.matchMedia('(hover: hover) and (pointer: fine)').matches));}
function worldLabelVisible(e){if(e.renderKind==='enemy')return e.type==='boss'||!!e.aggro;if(e.renderKind==='npc'||e.renderKind==='building')return Math.hypot(e.x-game.hero.x,e.y-game.hero.y)<=220;return true;}
function help(back=closeMenu){openMenu('Controls','MOVE\nWASD — Move hero\nLeft joystick — Move on touch devices\n\nCOMBAT\n1–5 — Skills 1–5\nSpace — Skill 6\nLeft Shift — Skill 7\nB — Skill 8\nH / Left mouse — Health potion\nM / Right mouse — Mana potion\nQ — Reserved / unavailable\n\nINTERACT & COMMAND\nE — Interact / select\nF — Confirm / order\nTab — Hero / squad cursor\nWASD — Move squad cursor while active\nBacktick — Recall squad / select whole party\n\nMENUS\nI / R — Inventory\nC — Talents\nX — Skills\nJ / T — Quests\nZ — Map\nP / V — Pause\nG — Controls\nEsc — Adventure menu\n\nMENU NAVIGATION\nW / A — Previous\nS / D — Next\nF / Enter / Space — Confirm\n\nPC INPUT\nMouse clicks do not move the hero, command the squad or activate menus. Left mouse uses an HP potion; right mouse uses an MP potion.\n\nTouch controls use the labeled on-screen buttons.',[],back);}
function clearInput(){if(typeof Sprint!=='undefined')Sprint.release();keys={};joy={x:0,y:0};autoAttack=false;}
function action(label,fn,detail='',disabled=false){return {label,action:fn,detail,disabled};}
function openMenu(title,description='',actions=[],back=closeMenu){clearInput();gateDismissed=false;menu={title,description,actions,back};menuIndex=0;document.body.classList.add('menu-open');$('modal').hidden=false;$('modal-title').textContent=title;$('modal-description').textContent=description;renderActions();}
let menuTouchBlockUntil=0;function renderActions(){const host=$('modal-actions');host.replaceChildren();buttons=[];for(const a of menu.actions){const b=document.createElement('button');b.textContent=a.label;b.disabled=a.disabled===true;if(a.detail){const span=document.createElement('span');span.className='detail';span.textContent=a.detail;b.append(span);}b.onclick=e=>{if(desktopMouse(e)||e?.pointerType==='touch'||(e?.isTrusted&&performance.now()<menuTouchBlockUntil))return;audio.unlock();a.action();if(started)save();updateHUD();};host.append(b);buttons.push(b);}const back=$('close-button');back.hidden=false;buttons.push(back);highlight();}
function highlight(){buttons.forEach((b,i)=>b.classList.toggle('selected',i===menuIndex));buttons[menuIndex]?.scrollIntoView({block:'nearest'});}
function closeMenu(){if(game.s.challenge.pending||game.s.challenge.gameOver)gateDismissed=true;menu=null;$('modal').hidden=true;document.body.classList.remove('menu-open');clearInput();}
$('modal').ontouchstart=()=>{menuTouchBlockUntil=performance.now()+700;};
$('close-button').onclick=e=>{if(desktopMouse(e)||e?.pointerType==='touch'||(e?.isTrusted&&performance.now()<menuTouchBlockUntil))return;audio.unlock();if(!game.s.endingAck&&game.peace){game.s.endingAck=true;save();}menu?.back();};
function exportJSON(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function start(mode,heroClass,succession){if(mode==='nightmare'&&!profile.nightmareUnlocked)return;game=new Campaign(mode,heroClass,Math.random,{succession});started=true;if(typeof Sprint!=='undefined')Sprint.reset();selection=['hero'];squadMode=false;paused=false;profile.activeMode=mode;save();closeMenu();updateHUD();}
function chooseClass(mode,succession){if(succession===undefined){openMenu('Challenge condition','The Dark Lord rules the land. To keep heroes from becoming strong enough to challenge him, his forces have captured the specialists who teach skills, forge equipment and prepare adventurers. Free them, rebuild your strength and confront his rule.\n\nSuccession is optional. Each fallen class is lost for this run; after three class deaths the run ends.',[action('Standard death and refuge recovery',()=>chooseClass(mode,false)),action('Succession challenge',()=>chooseClass(mode,true))]);return;}
 openMenu('New '+(mode==='nightmare'?'Nightmare':'Normal')+' adventure','Choose the hero who will begin the resistance. You start with one skill; rescuing the captured specialists unlocks the training and equipment needed to face the Dark Lord.',Object.entries(Campaign.classes).map(([id,c])=>action(c.icon+' '+id,()=>{let exists=false;try{exists=!!localStorage.getItem(saveKey(mode));}catch(_){}if(exists&&!confirm('Replace the existing '+mode+' run? Export it first to keep it.'))return;start(mode,id,succession);},id==='paladin'?'Melee, healing and brief immunity':id==='mage'?'Ranged magic, mana recovery and barriers':'Ranged bow, healing and mobility')),()=>chooseClass(mode));}
function awakeningChecklist(){return Campaign.dungeonIds.map(id=>{const b=game.boss(id),region=D.regions.find(r=>r.id===b.region);return {id,label:(game.s.true[id]?'✓ ':game.s.normal[id]?'⚔ ':'◇ ')+b.name,detail:(game.s.true[id]?'TRUE defeated':game.s.normal[id]?'TRUE awakened — return and challenge it':'Normal boss still alive — defeat it to awaken TRUE')+' · '+region.name};});}
function finaleMenu(back=openMain){const done=Campaign.dungeonIds.filter(id=>game.s.true[id]).length;openMenu('Awakening · Final objective','The TRUE Dark Lord is gone forever. Defeat every remaining TRUE dungeon guardian to end the war.\n\nProgress: '+done+'/5 TRUE guardians defeated.',awakeningChecklist().map(x=>action(x.label,()=>{},x.detail,true)),back);}
function acknowledgeAwakening(){game.s.awakeningAck=true;save();closeMenu();}
function awakeningMenu(){const done=Campaign.dungeonIds.filter(id=>game.s.true[id]).length;openMenu('The Dungeons Awaken','The TRUE Dark Lord has fallen and will not return. His defeat has awakened the remaining TRUE guardians of the five great dungeons. Defeat every remaining TRUE dungeon guardian to end the war. Previously defeated TRUE guardians remain defeated.\n\nProgress: '+done+'/5 defeated.',[...awakeningChecklist().map(x=>action(x.label,()=>{},x.detail,true)),action('Continue',acknowledgeAwakening)],acknowledgeAwakening);}
function characterMenu(){openMenu('Character and party','Progression, skills and companions.',[action('Skills and teachers',()=>skillBook(characterMenu)),action('Talents',()=>talents(characterMenu)),action('Companions and construction',()=>partyMenu(characterMenu))],openMain);}
function saveMenu(){openMenu('Save and game management','Backups, reports and run management.',[action('Save run',()=>{save();closeMenu();}),action('Export save',()=>exportJSON(game.snapshot(),'Azeroth_Chronicles_'+game.s.mode+'.json')),action('Import save',()=>$('import-file').click()),action('Export playtest report',()=>exportJSON({version:'0.8.41-prototype',mode:game.s.mode,phase:game.s.phase,hero:game.hero,statistics:game.s.statistics},'Azeroth_Playtest_Report.json')),action('New Normal game',()=>chooseClass('normal')),action('New game in Nightmare Mode',()=>chooseClass('nightmare'),'Unlocked by the peaceful ending',!profile.nightmareUnlocked),action('Load other mode run',()=>{const mode=game.s.mode==='normal'?'nightmare':'normal';if(load(mode)){save();closeMenu();}else game.say('No saved '+mode+' run yet.');})],systemMenu);}
function systemMenu(){openMenu('Game and settings','Controls, audio and save management.',[...(!runningAsApp()?[action('Install on phone',installApp,'Add Azeroth Chronicles to the home screen')]:[]),...(appRegistration?[action(appUpdateReady?'Install available game update':'Check for game update',updateApp)]:[]),action('Controls',()=>help(systemMenu)),action('Sound settings',()=>soundMenu(systemMenu)),action(paused?'Resume play':'Pause play',()=>{paused=!paused;closeMenu();}),action('Save and game management',saveMenu)],openMain);}
function openMain(){openMenu('Adventure menu','Choose what you need. Back returns to play.',[
 action('Map and travel routes',showMap),action('Quest journal',()=>quests(false)),action('Inventory and supplies',inventory),action('Character and party',characterMenu),...(game.s.phase==='awakening'?[action('Awakening · Final objective',()=>finaleMenu(openMain),'TRUE dungeon guardians '+Campaign.dungeonIds.filter(id=>game.s.true[id]).length+'/5')]:[]),...(profile.nightmareUnlocked?[action('★ New Game — Nightmare Mode',()=>chooseClass('nightmare'),'Unlocked by the peaceful ending · Standard or Succession challenge')]:[]),action('Game and settings',systemMenu)]);}
$('menu-button').onclick=e=>{if(desktopMouse(e))return;audio.unlock();if(!started)chooseClass('normal');else if(game.s.challenge.pending)successionMenu();else if(game.s.challenge.gameOver)gameOver();else openMain();};
$('talent-button').onclick=e=>{if(desktopMouse(e))return;audio.unlock();if(started&&!game.s.challenge.pending&&!game.s.challenge.gameOver)talents();};
function ending(){profile.nightmareUnlocked=true;persistProfile();openMenu('Peace for everyone','The evil is defeated. Every dungeon guardian has fallen. The war is over for people and creatures alike.\n\nCreatures are neutral and cannot harm or be harmed. The reclaimed dungeons are their homes.',[action('Continue in the peaceful world',()=>{game.s.endingAck=true;save();closeMenu();}),action('New game in Nightmare Mode',()=>{game.s.endingAck=true;save();chooseClass('nightmare');}),action('Export completed run',()=>exportJSON(game.snapshot(),'Azeroth_Chronicles_Completed.json'))]);}
function successionMenu(){openMenu('Choose your successor','The '+game.hero.class+' has fallen permanently. The death penalty has already removed 20% of carried gold; the remaining gold, rescues, quests and boss progress survive. Your successor starts at level 1 in Millhaven and must learn their skills.',Object.entries(Campaign.classes).filter(([id])=>!game.s.challenge.fallen.includes(id)).map(([id,c])=>action(c.icon+' '+id+' successor',()=>{game.successor(id);save();closeMenu();})));}
function gameOver(){openMenu('The last successor has fallen','All three classes have fallen. This run is over. Its progress remains available for export; continuing it is disabled.',[action('Export final run',()=>exportJSON(game.snapshot(),'Azeroth_Succession_Game_Over.json')),action('Start a new Normal run',()=>chooseClass('normal')),action('Start a new Nightmare run',()=>chooseClass('nightmare'),'',!profile.nightmareUnlocked)]);}
$('import-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('too large');const data=JSON.parse(await file.text()),candidate=data.version===2?Campaign.migrate(data):Campaign.restore(data);localStorage.setItem(saveKey(candidate.s.mode),JSON.stringify(candidate.snapshot()));game=candidate;started=true;profile.activeMode=game.s.mode;if(game.peace)profile.nightmareUnlocked=true;persistProfile();closeMenu();status('Imported successfully.');}catch(_){status('Invalid import. Your current run was kept intact.');}e.target.value='';};
function nearestNPC(){return [...game.visibleNPCs(),...game.zone().nodes.filter(n=>n.amount>0),...game.zone().buildings.map(b=>({...b,kind:'barracks',name:b.name||'Barracks'}))].filter(n=>Math.hypot(n.x-game.hero.x,n.y-game.hero.y)<115).sort((a,b)=>Math.hypot(a.x-game.hero.x,a.y-game.hero.y)-Math.hypot(b.x-game.hero.x,b.y-game.hero.y))[0];}
function interact(){const n=nearestNPC();if(!n){game.say('Find a marked person or place nearby. Use the map.');return;}if(['rest','cage','bundle','landmark','dungeon','exit','fountain','resource','mini'].includes(n.kind)){game.interact(n);save();updateHUD();return;}if(n.kind==='barracks')barracksMenu(n);else if(n.kind==='teacher')teacher(n);else if(n.kind==='smith')smith(n);else if(n.kind==='supplier'||n.kind==='alchemist')supplier(n);else if(n.kind==='recruiter')partyMenu();else if(n.kind==='quests')quests(true);else if(n.kind==='transport'){const i=game.regionIndex(),r=D.regions[i],target=D.regions[i+n.direction],cost=n.direction===1?(game.s.recovery[r.id]?0:r.fare):0;openMenu(n.name,'Fare '+cost+'g. Paid outbound travel includes free return. Health, mana and supplies are preserved.',[action('Travel to '+target.name,()=>{if(game.travel(n.direction))closeMenu();})]);}}
$('interact-button').onclick=e=>{if(desktopMouse(e))return;audio.unlock();if(activePlay())squadMode?select():interact();};
function teacher(n){const catalog=game.teacherCatalog(n.family),cap=catalog.maxRank,next=Object.keys(Campaign.rules.teachers).find(id=>Campaign.rules.teachers[id].maxRank>cap);openMenu(n.name,(next?'Higher ranks: rescue '+game.boss(next).captive+' in '+D.regions.find(r=>r.id===game.boss(next).region).name+'. ':'Maximum training rank available here. ')+'Learning a new skill and training its rank are separate. Rescue and gold are the only access gates; this instructor trains supported skills through rank '+cap+'.',D.skills.filter(s=>game.hero.skills[s[0]-1]?catalog.train.includes(s[0]):catalog.learn.includes(s[0])).map(s=>{const rank=game.hero.skills[s[0]-1],cost=rank?s[5]*rank:s[3];return action((rank?'Train ':'Learn ')+s[1]+' · '+cost+'g',()=>{rank?game.upgrade(s[0],n.family):game.learn(s[0],n.family);teacher(n);},'Skill '+s[0]+' · Rank '+rank+' · Specialist cap '+cap,rank>=cap||game.hero.gold<cost); }));}
function skillBook(back=closeMenu){openMenu('Skills and teachers','Locked skills require paid instruction from a rescued teacher. Specialists do not impose hero-level requirements.',D.skills.filter(s=>game.skillRevealed(s[0])).map(s=>action('Skill '+s[0]+' '+s[1]+' · Rank '+game.hero.skills[s[0]-1],()=>{},s[0]===1?'Always available':s[3]+'g · '+game.boss(s[4]).captive+' · '+D.regions.find(r=>r.id===game.boss(s[4]).region).name,true)),back);}
function supplier(n){const advanced=n.kind==='alchemist';openMenu(n.name,'Per bottle. Potions restore their amount over five seconds, share a 10 second cooldown and are conserved at full resources.',[
 action('Health potion · '+(advanced?50:20)+'g',()=>{game.buyPotion('health',advanced);supplier(n);},'Restores '+(advanced?150:60)+' health'),action('Mana potion · '+(advanced?40:15)+'g',()=>{game.buyPotion('mana',advanced);supplier(n);},'Restores '+(advanced?100:40)+' mana'),...(advanced?[action('Preparation tonic · 70g',()=>{game.buyPotion('tonic',true);supplier(n);},'10% maximum health until death or refuge rest. Does not stack.')]:[])]);}
function smith(n){const tier={crypt:1,mine:2,abyss:3,darklord:4}[n.family],weapon=[0,100,450,1000,2000][tier],armor=[0,80,300,700,1200][tier];openMenu(n.name,'Equipment replaces the earlier tier in its slot. Bonuses do not stack.',[
 action('Weapon tier '+tier+' · '+weapon+'g',()=>{game.gear(n.family,'weapon');smith(n);},'+'+[0,15,35,55,70][tier]+' power'),action('Armor tier '+tier+' · '+armor+'g',()=>{game.gear(n.family,'armor');smith(n);},'+'+[0,5,12,20,28][tier]+' armor'),action('Reforge weapon · '+Math.ceil(weapon/2)+'g',()=>{game.gear(n.family,'weapon',true);smith(n);},'+5 power once per tier'),action('Reforge armor · '+Math.ceil(armor/2)+'g',()=>{game.gear(n.family,'armor',true);smith(n);},'+3 armor once per tier')]);}
function inventory(back=closeMenu){openMenu('Inventory','Gold '+Math.floor(game.hero.gold)+' · Weapon tier '+game.hero.weapon+' · Armor tier '+game.hero.armorTier,[action('Use health potion',()=>{game.potion('health');inventory(back);},'Saved bottles '+(game.hero.legacyPotions?.filter(p=>p.type==='health').length||0)+' · Normal '+(game.hero.potions.health||0)+' · Greater '+(game.hero.potions.greater_health||0)),action('Use mana potion',()=>{game.potion('mana');inventory(back);},'Saved bottles '+(game.hero.legacyPotions?.filter(p=>p.type==='mana').length||0)+' · Normal '+(game.hero.potions.mana||0)+' · Greater '+(game.hero.potions.greater_mana||0)),...Object.keys(Campaign.legacyWeapons).filter(name=>game.s.legacyInventory?.includes(name)).map(name=>action('Equip '+name,()=>{game.equipLegacy(name);inventory(back);},'Saved weapon · +'+Campaign.legacyWeapons[name]+' power')), ...(game.hero.weapon?[action('Equip current weapon tier '+game.hero.weapon,()=>{game.hero.legacyEquipped=false;inventory(back);})]:[])],back);}
function recallSquad(){game.recallParty();selection=['hero',...game.s.party.filter(u=>u.hp>0).map(u=>u.id)];squadMode=false;targetId=null;document.body.classList.remove('squad-mode');updateHUD();}
function partyMenu(back=closeMenu){const town=!game.isDungeon()&&Math.hypot(game.hero.x-D.towns[game.regionIndex()][0],game.hero.y-D.towns[game.regionIndex()][1])<200;openMenu('Companions','Companions follow the hero by default and only join fights the hero is actively engaged in. Recall cancels squad orders and regroups everyone. Six living companions maximum.',[
 action('Recall and follow squad · Backtick',()=>{recallSquad();closeMenu();},'Cancel combat, movement and worker orders; regroup on the hero'),action(game.s.holdFire?'Allow companion attacks':'Hold fire',()=>{game.s.holdFire=!game.s.holdFire;partyMenu(back);}),...['worker','soldier','archer'].map(type=>action('Recruit '+type+' · '+{worker:35,soldier:70,archer:100}[type]+'g',()=>{game.recruit(type);partyMenu(back);},'',!town)),action('Recover fallen companion · 40g',()=>{game.recover();partyMenu(back);},'',!town),action('Build barracks · 120g',()=>{game.build();partyMenu(back);}),...game.zone().buildings.map(b=>action('Train soldier · 60g',()=>{game.train(b.id);partyMenu(back);},b.progress<4?'Under construction':b.queue>0?'Training':'Ready')), ...game.zone().nodes.filter(n=>n.amount>0).map(n=>action('Gather '+n.name+' '+n.icon,()=>{game.gather(n.id);closeMenu();},Math.floor(n.amount)+' gold remaining · guarded expedition · workers return automatically')),...game.s.party.map(u=>action(u.icon+' '+u.type+' · '+Math.ceil(u.hp)+' / '+u.maxHp,()=>{selection=[u.id];squadMode=true;closeMenu();},u.hp<=0?'Fallen':'Select companion',u.hp<=0))],back);}
function talents(back=closeMenu){openMenu('Talents','Available points '+game.hero.talentPoints,['Attack power +8','Mana regeneration +2','Maximum health +30','Movement speed +40'].map((name,i)=>action(name+' · '+game.hero.talents[i],()=>{game.talent(i);talents(back);})),back);}
function quests(atBoard){const local=atBoard?game.questDefs().filter(q=>q.region===game.definition().id):game.questDefs();openMenu(atBoard?'Local quests':'Quest journal',atBoard?'All local quests are already ACTIVE. Rewards are automatically delivered as soon as their objectives are completed.':'All quests begin active automatically. Rewards are delivered immediately on completion; no return trip is required.',local.map(q=>{const p=game.s.quests[q.id];return action(q.name+' · '+(p?.paid?'Complete':p?.closedByPeace?'Resolved by peace':'ACTIVE'),()=>{},q.objective+' · '+q.gold+'g / '+q.xp+' XP · '+game.questProgress(q));}));}
function soundMenu(back=closeMenu){const s=audio.settings;openMenu('Music and sound','Independent volumes. Preferences survive new games.',[action(s.muted?'Unmute all sound':'Mute all sound',()=>{audio.setSettings({muted:!s.muted});profile.audio={...audio.settings};persistProfile();soundMenu(back);}),...['master','music','ambience','effects'].flatMap(key=>[action(key+' − · '+Math.round(s[key]*100)+'%',()=>{audio.setSettings({[key]:s[key]-.1});profile.audio={...audio.settings};persistProfile();soundMenu(back);}),action(key+' +',()=>{audio.setSettings({[key]:s[key]+.1});profile.audio={...audio.settings};persistProfile();soundMenu(back);})])],back);}
function showMap(){const r=game.definition(),fieldTrue=game.zone().enemies.filter(e=>e.hp>0&&e.type==='boss'&&e.form==='true'&&game.boss(e.family)?.kind==='field').map(e=>({...e,kind:'trueboss',icon:'⚔️'})),targets=[...fieldTrue,...game.visibleNPCs(),...game.zone().nodes.filter(n=>n.amount>0)];openMenu((game.supplyRoom()?.name||r.name)+' map',r.biome+'\nTransport: '+D.regions.map(r=>r.name).join(' → ')+'\nChoose a marked destination to walk there. Region boundaries require transport.',targets.map(n=>action(n.icon+' '+n.name,()=>{game.hero.order={type:'move',x:n.x,y:n.y};closeMenu();},Math.round(n.x)+', '+Math.round(n.y)+(n.kind==='trueboss'?' · TRUE boss hunt target':n.kind==='landmark'?' · '+game.siteDescription(n):n.kind==='dungeon'&&game.s.phase==='awakening'?' · '+(game.s.true[n.family]?'TRUE defeated':game.s.normal[n.family]?'TRUE awakened — challenge it':'Normal boss still alive — defeat it first'):n.kind==='mini'?' · '+game.miniStatus(n.mini):n.kind==='resource'?' · '+(n.mini&&!game.peace&&!game.miniCleared(n.mini)?'Clear guardians to unlock':'Guarded worker expedition'):n.kind==='bundle'?' · Collect with Interact':''))));
 const map=document.createElement('canvas');map.width=420;map.height=280;const c=map.getContext('2d'),size=game.supplyRoom()?900:game.isDungeon()?1500:r.size,sx=x=>x/size*420,sy=y=>y/size*280;
 c.fillStyle=D.colors[game.regionIndex()];c.fillRect(0,0,420,280);c.strokeStyle='#e0ddb21b';c.lineWidth=1;for(let x=35;x<420;x+=35){c.beginPath();c.moveTo(x,0);c.lineTo(x,280);c.stroke();}for(let y=35;y<280;y+=35){c.beginPath();c.moveTo(0,y);c.lineTo(420,y);c.stroke();}
 for(let x=0;x<size;x+=50)for(let y=0;y<size;y+=50)if(game.blocked(x,y,game.zoneId,0)){c.fillStyle=game.isDungeon()?'#78807d':'#355d72';c.fillRect(sx(x),sy(y),sx(50)+1,sy(50)+1);}
 c.strokeStyle='#d9c898';c.lineWidth=2;for(const road of game.zone().roads||[]){c.beginPath();road.forEach((p,j)=>j?c.lineTo(sx(p.x),sy(p.y)):c.moveTo(sx(p.x),sy(p.y)));c.stroke();}
 for(const n of [...game.visibleNPCs(),...game.zone().nodes.filter(n=>n.amount>0)]){const x=sx(n.x),y=sy(n.y);c.fillStyle=n.kind==='quests'?'#f5d883':n.kind==='dungeon'||n.kind==='exit'?'#a9d4c6':'#f2e4b9';c.strokeStyle='#162a25';c.lineWidth=1.5;c.beginPath();c.arc(x,y,n.kind==='quests'?5:3.5,0,Math.PI*2);c.fill();c.stroke();}for(const e of game.zone().enemies.filter(e=>e.hp>0)){c.fillStyle=e.neutral?'#aed6a0':'#e87b7b';c.fillRect(sx(e.x)-1,sy(e.y)-1,3,3);}c.strokeStyle='#fff2bd';c.lineWidth=2;c.beginPath();c.arc(sx(game.hero.x),sy(game.hero.y),6,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(sx(game.hero.x)-8,sy(game.hero.y));c.lineTo(sx(game.hero.x)+8,sy(game.hero.y));c.moveTo(sx(game.hero.x),sy(game.hero.y)-8);c.lineTo(sx(game.hero.x),sy(game.hero.y)+8);c.stroke();c.strokeStyle='#e2cf9a';c.strokeRect(1,1,418,278);$('modal-description').append(map);}
function order(){const p=world(cursor.x,cursor.y),e=game.zone().enemies.find(e=>e.hp>0&&!e.neutral&&Math.hypot(e.x-p.x,e.y-p.y)<90),units=game.s.party.filter(u=>selection.includes(u.id));if(selection.includes('hero'))game.hero.order=e?{type:'attack',id:e.id}:{type:'move',...p};if(units.length)game.s.recallActive=false;for(const u of units)u.order=e?{type:'attack',id:e.id}:{type:'move',...p};targetId=e?.id||null;}
function select(){const p=world(cursor.x,cursor.y),u=game.s.party.find(u=>u.hp>0&&Math.hypot(u.x-p.x,u.y-p.y)<65),hero=Math.hypot(game.hero.x-p.x,game.hero.y-p.y)<60;selection=hero?['hero']:u?[u.id]:[];targetId=game.zone().enemies.find(e=>e.hp>0&&!e.neutral&&Math.hypot(e.x-p.x,e.y-p.y)<70)?.id||null;}
$('squad-button').onclick=e=>{if(desktopMouse(e))return;audio.unlock();squadMode=!squadMode;clearInput();updateHUD();};$('recall-button').onclick=e=>{if(desktopMouse(e))return;audio.unlock();if(activePlay()){recallSquad();save();}};$('order-button').onclick=e=>{if(desktopMouse(e))return;audio.unlock();if(menu)buttons[menuIndex]?.click();else if(activePlay()){if(squadMode)order();else interact();}};
const skillNames=['Basic attack','Second attack','Recovery','Defense or mobility','Area attack','Frequent special','Advanced special','Final special'],icons=['ATK','HIT','HEAL','GUARD','AREA','CAST','BURST','FINAL'],skillKeys=['1','2','3','4','5','Space','Shift','B'];
for(let i=0;i<8;i++){const b=document.createElement('button');b.id='skill-'+(i+1);b.setAttribute('aria-label','Skill '+(i+1)+' '+skillNames[i]);b.innerHTML=icons[i]+'<small>'+skillKeys[i]+'</small>';b.onclick=e=>{if(desktopMouse(e))return;audio.unlock();if(activePlay())game.cast(i+1,targetId);};if(i===0){b.onpointerdown=e=>{if(desktopMouse(e))return;audio.unlock();if(activePlay())autoAttack=true;};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>autoAttack=false;}$('skills').append(b);}
function usePotion(type){if(!activePlay())return;audio.unlock();if(game.potion(type)){updateHUD();save();}}
const quickItems=document.createElement('div');quickItems.id='quick-items';for(const [type,label,key]of [['health','Health','H'],['mana','Mana','M']]){const b=document.createElement('button');b.id=type+'-potion';b.className='potion-button';b.setAttribute('aria-label','Use '+type+' potion ('+key+')');b.onclick=e=>{if(desktopMouse(e))return;usePotion(type);};quickItems.append(b);}$('skills').append(quickItems);
addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;audio.unlock();const code=e.code;if(['Space','Tab','Escape'].includes(code))e.preventDefault();if(code==='Escape'){if(menu)menu.back();else if(!started)chooseClass('normal');else if(game.s.challenge.pending)successionMenu();else if(game.s.challenge.gameOver)gameOver();else openMain();return;}if(menu){if(e.repeat)return;if(['KeyS','KeyD'].includes(code)){menuIndex=(menuIndex+1)%Math.max(1,buttons.length);highlight();}else if(['KeyW','KeyA'].includes(code)){menuIndex=(menuIndex-1+buttons.length)%Math.max(1,buttons.length);highlight();}else if(['KeyF','Enter','Space'].includes(code))buttons[menuIndex]?.click();return;}if((paused||!focused||document.hidden)&&!['KeyP','KeyV','KeyG'].includes(code))return;keys[code]=true;if(code==='KeyQ')Sprint.press('keyboard',true);if(e.repeat)return;if(code==='Tab'){squadMode=!squadMode;clearInput();}else if(code==='KeyE')squadMode?select():interact();else if(code==='KeyF')squadMode?order():interact();else if(code==='Backquote'){recallSquad();save();}else if(code==='KeyP'||code==='KeyV'){paused=!paused;clearInput();}else if(code==='KeyZ')showMap();else if(code==='KeyI'||code==='KeyR')inventory();else if(code==='KeyH')usePotion('health');else if(code==='KeyM')usePotion('mana');else if(code==='KeyC')talents();else if(code==='KeyX')skillBook();else if(code==='KeyG')help();else if(code==='KeyJ'||code==='KeyT')quests(false);else{const num=/Digit([1-5])/.exec(code)?.[1]||({Space:6,ShiftLeft:7,KeyB:8}[code]);if(num)game.cast(Number(num),targetId);}});
addEventListener('keyup',e=>{delete keys[e.code];if(e.code==='KeyQ')Sprint.press('keyboard',false);});
const joystick=$('joystick');let pointer=null,menuJoyTime=0;function joyUpdate(e){const r=joystick.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width*.4),dy=(e.clientY-r.top-r.height/2)/(r.height*.4),n=Math.max(1,Math.hypot(dx,dy));joy={x:dx/n,y:dy/n};$('stick').style.transform='translate('+joy.x*24+'px,'+joy.y*24+'px)';}
joystick.onpointerdown=e=>{if(e.pointerType==='mouse'||pointer!==null)return;e.preventDefault();audio.unlock();pointer=e.pointerId;joystick.setPointerCapture(pointer);joyUpdate(e);};joystick.onpointermove=e=>{if(e.pointerId===pointer)joyUpdate(e);};joystick.onpointerup=joystick.onpointercancel=joystick.onlostpointercapture=e=>{if(e.pointerId===pointer){pointer=null;joy={x:0,y:0};$('stick').style.transform='';}};
canvas.onpointermove=null;canvas.onpointerdown=e=>{if(e.pointerType==='mouse')e.preventDefault();};addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||!activePlay())return;if(e.button===0){e.preventDefault();usePotion('health');}else if(e.button===2){e.preventDefault();usePotion('mana');}},true);addEventListener('contextmenu',e=>{if(activePlay())e.preventDefault();});
addEventListener('blur',()=>{focused=false;clearInput();save();audio.setPaused(true);});addEventListener('focus',()=>{focused=true;last=performance.now();});document.addEventListener('visibilitychange',()=>{clearInput();last=performance.now();if(document.hidden){save();audio.setPaused(true);}});addEventListener('pagehide',save);
function updateCriticalNotice(){const host=$('message'),latest=game.notices?.at(-1),now=performance.now();if(latest&&latest!==criticalNoticeSeen){criticalNoticeSeen=latest;criticalNoticeUntil=now+(latest.duration||5.5)*1000;host.textContent=latest.text;host.classList.add('visible');}if(criticalNoticeUntil&&now>=criticalNoticeUntil){criticalNoticeUntil=0;host.classList.remove('visible');}}
function updateHUD(){document.body.classList.toggle('squad-mode',squadMode);const h=game.hero,hp=Math.max(0,Math.min(100,h.hp/h.maxHp*100)),mp=Math.max(0,Math.min(100,h.mp/h.maxMp*100));const talentButton=$('talent-button'),talentCount=$('talent-count');talentCount.textContent=h.talentPoints;talentButton.classList.toggle('talent-ready',h.talentPoints>0);talentButton.title=h.talentPoints>0?h.talentPoints+' unspent talent point'+(h.talentPoints===1?'':'s')+' · press C':'Talents · press C';$('hero-stats').innerHTML='<div class="hero-title"><span>'+Campaign.classes[h.class].icon+' '+h.class+'</span><small>LEVEL '+h.level+'</small></div><div class="resource-line health"><span>HP '+Math.ceil(h.hp)+' / '+h.maxHp+'</span><i style="--fill:'+hp+'%"></i></div><div class="resource-line mana"><span>MP '+Math.floor(h.mp)+' / '+h.maxMp+'</span><i style="--fill:'+mp+'%"></i></div><div class="wallet"><span class="gold">'+Math.floor(h.gold)+' gold</span><span>XP '+Math.floor(h.xp)+' / '+120*h.level+'</span></div>';if(h.potionEffect)$('hero-stats').innerHTML+='<small class="restoring">Restoring '+(h.potionEffect.type==='health'?'HP':'MP')+' · '+h.potionEffect.seconds.toFixed(1)+'s</small>';$('location').textContent=game.definition().name+(game.supplyRoom()?' · '+game.supplyRoom().name:game.isDungeon()?' · '+game.boss(game.zoneId).place:'')+' · '+(game.peace?'At peace':game.s.mode==='nightmare'?'Nightmare':game.night()?'Night':'Day');
 for(const [type,label,key]of [['health','Health','H'],['mana','Mana','M']]){const b=$(type+'-potion'),stock=(h.potions[type]||0)+(h.potions['greater_'+type]||0)+(h.legacyPotions?.filter(p=>p.type===type).length||0),full=type==='health'?h.hp>=h.maxHp:h.mp>=h.maxMp;b.disabled=!stock||h.potionCd>0||full;b.innerHTML=label+' · '+stock+'<small>'+key+(h.potionCd>0?' · '+h.potionCd.toFixed(1)+'s':' · Auto 35%')+'</small>';b.title=label+' potion · automatic at 35% or use manually with '+key+' · restores over five seconds · shared 10-second cooldown';}
 const remaining=Campaign.dungeonIds.filter(id=>!game.s.true[id]),liveFieldTrue=game.zone().enemies.find(e=>e.hp>0&&e.type==='boss'&&e.form==='true'&&game.boss(e.family)?.kind==='field'),pendingField=Object.entries(game.s.pending||{}).find(([id,p])=>p.kind==='field'&&p.zone===game.zoneId&&!game.s.true[id]);$('objective').textContent=game.peace?'Peace for everyone. Explore the creatures’ new homes.':liveFieldTrue?'TRUE BOSS · '+liveFieldTrue.name+' is roaming '+game.definition().name+' · Map: Z':pendingField&&!pendingField[1].active?'TRUE BOSS · '+game.boss(pendingField[0]).name+' TRUE emerging in '+Math.max(0,Math.ceil(pendingField[1].delay))+'s':game.s.phase==='awakening'?'AWAKENING · Final objective · '+(5-remaining.length)+'/5 TRUE guardians defeated · Map: Z':game.s.rescued.thorn?'Rescue specialists, learn skills and reach the Dark Lord. Map: Z.':'Find Thornfang and rescue Mira to learn your next skills. Map: Z.';
 $('squad-button').textContent=squadMode?'Hero control · Tab':'Squad cursor · Tab';for(let i=0;i<8;i++){const b=$('skill-'+(i+1)),rank=h.skills[i];b.classList.toggle('locked',!rank);const revealed=game.skillRevealed(i+1);b.title=(revealed?skillNames[i]:'Undiscovered skill')+(rank?' · Rank '+rank:' · Not learned')+(i===0&&PrototypeRules.movementBasicClasses[h.class]?' · Also triggers while moving':'');b.setAttribute('aria-label','Skill '+(i+1)+' '+(revealed?skillNames[i]:'Undiscovered')); b.querySelector('small').textContent=!rank?'Locked':h.cd[i]>0?h.cd[i].toFixed(1):skillKeys[i];}const n=nearestNPC();$('interact-button').textContent=squadMode?'Select · E':'Interact · E';$('order-button').textContent=menu?'Confirm · F':squadMode?'Order · F':'Interact · F';$('interact-button').title=n?n.name:'Find a marked person';updateCriticalNotice();}
function sprite(e,p){PrototypeVisuals.draw(ctx,e,p,game.regionIndex(),!!game.s.rescued[e.family]);}
function groundMarker(e,p){const type=e.renderKind,important=type==='hero'||e.type==='boss'||e.kind==='quests';if(!['hero','ally','enemy','npc','node'].includes(type))return;ctx.strokeStyle=type==='hero'?'#f5d992bb':type==='ally'?'#a7d3a77d':type==='enemy'?e.neutral?'#b9d8b177':e.type==='boss'?'#ec8b76aa':'#b8786870':e.kind==='quests'?'#f5d18cbb':'#d5ca9b66';ctx.lineWidth=important?2:1;ctx.beginPath();ctx.ellipse(p.x,p.y+9,important?28:21,important?11:8,0,0,Math.PI*2);ctx.stroke();if(important){ctx.strokeStyle='#f3e2bb44';ctx.beginPath();ctx.ellipse(p.x,p.y+9,34,14,0,0,Math.PI*2);ctx.stroke();}}
function healthPlate(e,p){const y=p.y-PrototypeVisuals.height(e),w=e.type==='boss'?54:42,left=p.x-w/2;ctx.fillStyle='#0c1a19dd';ctx.fillRect(left-2,y-2,w+4,8);ctx.fillStyle='#5a645b';ctx.fillRect(left,y,w,4);ctx.fillStyle=e.renderKind==='enemy'?'#e87966':'#91d59c';ctx.fillRect(left,y,w*Math.max(0,Math.min(1,e.hp/e.maxHp)),4);ctx.fillStyle='#ffffff77';ctx.fillRect(left,y,w*Math.max(0,Math.min(1,e.hp/e.maxHp)),1);}
function projectileVector(p){const dx=Number.isFinite(p.dx)?p.dx:1,dy=Number.isFinite(p.dy)?p.dy:0,q=screen(p),tail=screen({x:p.x-dx*24,y:p.y-dy*24}),vx=q.x-tail.x,vy=q.y-tail.y,len=Math.hypot(vx,vy)||1;return {q,ux:vx/len,uy:vy/len,px:-vy/len,py:vx/len};}
function drawProjectile(p){const {q,ux,uy,px,py}=projectileVector(p),style=p.style||'magic';ctx.save();ctx.lineCap='round';ctx.lineJoin='round';
 if(style==='arrow'){ctx.strokeStyle='#d8c69a';ctx.fillStyle='#e8e1c6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(q.x-ux*24,q.y-uy*24);ctx.lineTo(q.x+ux*4,q.y+uy*4);ctx.stroke();ctx.beginPath();ctx.moveTo(q.x+ux*7,q.y+uy*7);ctx.lineTo(q.x-ux*2+px*4,q.y-uy*2+py*4);ctx.lineTo(q.x-ux*2-px*4,q.y-uy*2-py*4);ctx.closePath();ctx.fill();ctx.strokeStyle='#9b6f4f';ctx.lineWidth=1.5;for(const s of [-1,1]){ctx.beginPath();ctx.moveTo(q.x-ux*19,q.y-uy*19);ctx.lineTo(q.x-ux*14+px*4*s,q.y-uy*14+py*4*s);ctx.stroke();}}
 else if(style==='axe'){ctx.translate(q.x,q.y);ctx.rotate(performance.now()/90);ctx.strokeStyle='#77563b';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-9,0);ctx.lineTo(9,0);ctx.stroke();ctx.fillStyle='#c9c5b6';ctx.beginPath();ctx.moveTo(4,-7);ctx.quadraticCurveTo(13,0,4,7);ctx.lineTo(0,4);ctx.lineTo(0,-4);ctx.closePath();ctx.fill();}
 else if(style==='stone'){ctx.fillStyle='#a9916f';ctx.strokeStyle='#655a4d';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(q.x-6,q.y-2);ctx.lineTo(q.x-2,q.y-6);ctx.lineTo(q.x+5,q.y-4);ctx.lineTo(q.x+7,q.y+2);ctx.lineTo(q.x+1,q.y+6);ctx.lineTo(q.x-5,q.y+3);ctx.closePath();ctx.fill();ctx.stroke();ctx.globalAlpha=.35;ctx.fillStyle='#d1b98e';for(const d of [13,21]){ctx.beginPath();ctx.arc(q.x-ux*d,q.y-uy*d,2,0,Math.PI*2);ctx.fill();}}
 else if(style==='spit'){ctx.translate(q.x,q.y);ctx.rotate(Math.atan2(uy,ux));ctx.fillStyle='#9dcc7d';ctx.beginPath();ctx.ellipse(0,0,8,4,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(-10,1,2.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(-16,-2,1.5,0,Math.PI*2);ctx.fill();}
 else if(style==='cinder'){ctx.fillStyle='#e97542';ctx.beginPath();ctx.moveTo(q.x+ux*7,q.y+uy*7);ctx.lineTo(q.x-ux*13+px*5,q.y-uy*13+py*5);ctx.lineTo(q.x-ux*8,q.y-uy*8);ctx.lineTo(q.x-ux*13-px*5,q.y-uy*13-py*5);ctx.closePath();ctx.fill();ctx.fillStyle='#ffd17a';ctx.beginPath();ctx.arc(q.x,q.y,3.5,0,Math.PI*2);ctx.fill();}
 else if(style==='spectral'){ctx.strokeStyle='#b6b8ff';ctx.fillStyle='#8d90d9';ctx.globalAlpha=.5;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(q.x-ux*20,q.y-uy*20);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.globalAlpha=1;ctx.beginPath();ctx.moveTo(q.x+ux*7,q.y+uy*7);ctx.lineTo(q.x+px*5,q.y+py*5);ctx.lineTo(q.x-ux*6,q.y-uy*6);ctx.lineTo(q.x-px*5,q.y-py*5);ctx.closePath();ctx.fill();}
 else{ctx.strokeStyle='#9fd8ff';ctx.fillStyle='#c7ecff';ctx.globalAlpha=.45;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(q.x-ux*18,q.y-uy*18);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.globalAlpha=1;ctx.beginPath();ctx.moveTo(q.x+ux*7,q.y+uy*7);ctx.lineTo(q.x+px*4,q.y+py*4);ctx.lineTo(q.x-ux*6,q.y-uy*6);ctx.lineTo(q.x-px*4,q.y-py*4);ctx.closePath();ctx.fill();}
 ctx.restore();}
function queueVisualFx(events){for(const e of events){if(e.type==='hit'&&Number.isFinite(e.x))visualFx.push({type:'impact',x:e.x,y:e.y,life:.2,max:.2});else if(e.type==='hurt'&&Number.isFinite(e.x))visualFx.push({type:'hurt',x:e.x,y:e.y,life:.25,max:.25});else if(e.type==='heal')visualFx.push({type:'heal',resource:e.resource||'health',x:e.x??game.hero.x,y:e.y??game.hero.y,life:.55,max:.55});else if(e.type==='swing')visualFx.push({type:'swing',...e,life:.18,max:.18});}if(visualFx.length>40)visualFx.splice(0,visualFx.length-40);}
function updateVisualFx(dt){for(const f of visualFx)f.life-=dt;visualFx=visualFx.filter(f=>f.life>0);}
function drawVisualFx(){for(const f of visualFx){const a=Math.max(0,f.life/f.max),p=screen(f);ctx.save();ctx.globalAlpha=a;
  if(f.type==='impact'){ctx.strokeStyle='#fff0b6';ctx.lineWidth=2;for(let j=0;j<4;j++){const an=j*Math.PI/2+.35;ctx.beginPath();ctx.moveTo(p.x+Math.cos(an)*4,p.y+Math.sin(an)*4);ctx.lineTo(p.x+Math.cos(an)*13,p.y+Math.sin(an)*13);ctx.stroke();}}
  else if(f.type==='hurt'){ctx.strokeStyle='#f08b78';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,8+(1-a)*10,0,Math.PI*2);ctx.stroke();}
  else if(f.type==='heal'){ctx.strokeStyle=f.resource==='mana'?'#9fcfff':'#a9e7b0';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+7,20+(1-a)*11,8+(1-a)*4,0,0,Math.PI*2);ctx.stroke();for(let j=0;j<4;j++){const x=p.x+(j-1.5)*8,y=p.y-8-(1-a)*(12+j*3);ctx.globalAlpha=a*.75;ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill();}}
  else if(f.type==='swing'){const t=screen({x:f.targetX??f.x+1,y:f.targetY??f.y}),ang=Math.atan2(t.y-p.y,t.x-p.x);ctx.strokeStyle='#f6e2a6';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,31,ang-.85,ang+.55);ctx.stroke();}
  ctx.restore();}
 const h=game.hero,p=screen(h);if(h.immune>0){ctx.save();ctx.strokeStyle='#f6dda0aa';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+6,29,12,0,0,Math.PI*2);ctx.stroke();ctx.restore();}if(h.haste>0){ctx.save();ctx.strokeStyle='#d9f2ff99';ctx.lineWidth=1.5;for(let j=-1;j<=1;j++){ctx.beginPath();ctx.moveTo(p.x-24,p.y+j*7);ctx.lineTo(p.x-38,p.y+j*7+3);ctx.stroke();}ctx.restore();}if(h.potionEffect){ctx.save();ctx.strokeStyle=h.potionEffect.type==='mana'?'#82bfff88':'#8bd99a88';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+8,25,10,0,0,Math.PI*2);ctx.stroke();ctx.restore();}}

function draw(){ctx.fillStyle='#0c1913';ctx.fillRect(0,0,canvas.width,canvas.height);const z=game.zone(),room=!!game.supplyRoom(),dungeon=game.isDungeon(),size=room?900:dungeon?1500:game.definition().size,i=game.regionIndex();for(let x=0;x<size;x+=80)for(let y=0;y<size;y+=80){const p=screen({x,y});if(p.x<-160||p.x>canvas.width+160||p.y<-100||p.y>canvas.height+100)continue;const blocked=dungeon&&game.blocked(x+40,y+40,game.zoneId,0)&&!z.props.some(q=>Math.hypot(x+40-q.x,y+40-q.y)<q.r);PrototypeVisuals.floor(ctx,p,x,y,i,room,room?'':dungeon?game.zoneId:'',blocked);}
 if(!game.isDungeon())PrototypeVisuals.terrain(ctx,screen,i);
 PrototypeVisuals.roads(ctx,z.roads||[],screen,i);
 if(!game.isDungeon())PrototypeVisuals.bridges(ctx,screen,i);
 for(const t of game.traps()){const p=screen(t),warningTime=t.warningTime??1.5,activeTime=t.activeTime??.6,active=t.phase>=warningTime&&t.phase<warningTime+activeTime,warning=t.phase<warningTime;ctx.fillStyle=active?'#e9534bcc':warning?'#e8bd5f88':'#777b6544';ctx.strokeStyle=active?'#ffab77':warning?'#ffd580':'#9b9c7a66';ctx.lineWidth=2;ctx.beginPath();if(t.kind==='jet'){const hw=t.halfWidth??28;for(const [j,v]of [{x:t.x-t.length/2,y:t.y-hw},{x:t.x+t.length/2,y:t.y-hw},{x:t.x+t.length/2,y:t.y+hw},{x:t.x-t.length/2,y:t.y+hw}].entries()){const q=screen(v);j?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);}ctx.closePath();}else ctx.ellipse(p.x,p.y,t.radius*.76,t.radius*.27,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(t.kind==='spikes')for(const dx of [-12,0,12]){ctx.beginPath();ctx.moveTo(p.x+dx-4,p.y+5);ctx.lineTo(p.x+dx,p.y-(active?18:5));ctx.lineTo(p.x+dx+4,p.y+5);ctx.fill();}else if(t.kind==='seal'){ctx.strokeStyle=active?'#f6c77a':'#b4b8a0';ctx.beginPath();ctx.moveTo(p.x,p.y-7);ctx.lineTo(p.x+12,p.y);ctx.lineTo(p.x,p.y+7);ctx.lineTo(p.x-12,p.y);ctx.closePath();ctx.stroke();}}
 for(const e of z.enemies.filter(e=>e.rangedAim)){const from=screen(e),to=screen(e.rangedAim);ctx.strokeStyle='#f0d092aa';ctx.lineWidth=2;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(from.x,from.y-15);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(to.x,to.y,5,0,Math.PI*2);ctx.stroke();}

 for(const e of z.enemies.filter(e=>e.telegraph)){const a=e.telegraph,p=screen(a);ctx.strokeStyle='#ffe09a';ctx.fillStyle='#dc644c82';ctx.lineWidth=3;ctx.setLineDash([8,5]);
  if(a.kind==='line'||a.kind==='volley'){for(const o of a.kind==='volley'?[-.22,0,.22]:a.count===2?[-85,85]:[0]){const angle=a.angle+(a.kind==='volley'?o:0),offset=a.kind==='volley'?0:o,w=a.kind==='volley'?22:a.count===2?35:45,side={x:Math.cos(angle+Math.PI/2),y:Math.sin(angle+Math.PI/2)},from={x:a.fromX+side.x*offset,y:a.fromY+side.y*offset},to=a.kind==='volley'?{x:from.x+Math.cos(angle)*650,y:from.y+Math.sin(angle)*650}:{x:a.x+side.x*offset,y:a.y+side.y*offset};ctx.beginPath();for(const [j,q]of [{x:from.x+side.x*w,y:from.y+side.y*w},{x:to.x+side.x*w,y:to.y+side.y*w},{x:to.x-side.x*w,y:to.y-side.y*w},{x:from.x-side.x*w,y:from.y-side.y*w}].entries()){const p=screen(q);j?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);}ctx.closePath();ctx.fill();ctx.stroke();}}
  else if(a.kind==='cone'||a.kind==='sector'){ctx.beginPath();ctx.moveTo(p.x,p.y);for(let j=0;j<=12;j++){const angle=a.angle-(a.kind==='sector'?.65:1.1)+j*(a.kind==='sector'?1.3:2.2)/12,q=screen({x:a.x+Math.cos(angle)*a.radius,y:a.y+Math.sin(angle)*a.radius});ctx.lineTo(q.x,q.y);}ctx.closePath();ctx.fill();ctx.stroke();}
  else for(const patch of game.attackPatches(a)){const q=screen(patch);ctx.beginPath();ctx.ellipse(q.x,q.y,patch.radius*.76,patch.radius*.27,0,0,Math.PI*2);if(a.kind!=='ring')ctx.fill();ctx.stroke();}
  ctx.setLineDash([]);ctx.font='bold 12px system-ui';ctx.textAlign='center';const label=a.name+' · '+a.timer.toFixed(1),w=ctx.measureText(label).width+16;ctx.fillStyle='#241d1acb';ctx.fillRect(p.x-w/2,p.y-31,w,21);ctx.strokeStyle='#f4c984';ctx.lineWidth=1;ctx.strokeRect(p.x-w/2,p.y-31,w,21);ctx.fillStyle='#fff3c8';ctx.fillText(label,p.x,p.y-16);}
 for(const a of game.s.hazards){const p=screen(a);ctx.fillStyle='#db473766';ctx.strokeStyle='#f09e57';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(p.x,p.y,a.radius*.76,a.radius*.27,0,0,Math.PI*2);a.kind==='ring'?ctx.stroke():ctx.fill();}
 const boardCue=null,captainCue=game.zoneId==='vale'&&game.s.party.length<=2;
 const entities=[...z.props.map(p=>({...p,renderKind:'prop'})),...game.visibleNPCs().map(p=>({...p,renderKind:'npc'})),...z.nodes.filter(n=>n.amount>0).map(p=>({...p,renderKind:'node'})),...z.buildings.map(p=>({...p,renderKind:'building'})),...z.enemies.filter(e=>e.hp>0).map(p=>({...p,renderKind:'enemy'})),...game.s.party.filter(u=>u.hp>0).map(p=>({...p,renderKind:'ally'})),{...game.hero,icon:Campaign.classes[game.hero.class].icon,renderKind:'hero'},...(z.escort?[{...z.escort,icon:'🧑‍🌾',name:'Supply escort',renderKind:'ally'}]:[])].sort((a,b)=>a.x+a.y-b.x-b.y);
 for(const e of entities){const p=screen(e);if(p.x<-100||p.x>canvas.width+100||p.y<-100||p.y>canvas.height+100)continue;groundMarker(e,p);ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(p.x,p.y+12,e.type==='boss'?25:18,e.type==='boss'?8:6,0,0,Math.PI*2);ctx.fill();ctx.font=(e.renderKind==='prop'?34:30)+'px system-ui';ctx.textAlign='center';if(e.renderKind==='enemy'&&e.pursuitBurst>0){ctx.strokeStyle='#e9d3a8b0';ctx.lineWidth=2;for(const dy of [-1,6,13]){ctx.beginPath();ctx.moveTo(p.x-32,p.y+dy);ctx.lineTo(p.x-22,p.y+dy-3);ctx.stroke();}}sprite(e,p);
  if(['enemy','ally','hero'].includes(e.renderKind)){const visibleCombat=e.renderKind!=='enemy'||worldLabelVisible(e);if(visibleCombat&&!e.neutral)healthPlate(e,p);if(visibleCombat){const isTrueBoss=e.renderKind==='enemy'&&e.type==='boss'&&e.form==='true';ctx.font=isTrueBoss?'bold 12px system-ui':e.type==='boss'?'bold 11px system-ui':'10px system-ui';ctx.fillStyle=isTrueBoss?'#ffe08a':e.renderKind==='enemy'?'#f8cebd':'#dcebcf';ctx.shadowColor='#091510';ctx.shadowBlur=isTrueBoss?5:3;const label=e.renderKind==='enemy'?(isTrueBoss?'TRUE · '+e.name.replace(/\s+TRUE$/,'')+' · Lv '+e.level:e.name+' · Lv '+e.level):e.renderKind==='ally'?e.type||e.name:'';ctx.fillText(label,p.x,p.y-PrototypeVisuals.height(e)-7);if(isTrueBoss){const w=ctx.measureText('TRUE').width+12,y=p.y-PrototypeVisuals.height(e)-25;ctx.fillStyle='#3a2d12dd';ctx.fillRect(p.x-w/2,y-11,w,15);ctx.strokeStyle='#ffe08a';ctx.lineWidth=1.5;ctx.strokeRect(p.x-w/2,y-11,w,15);ctx.fillStyle='#fff1b4';ctx.font='bold 9px system-ui';ctx.fillText('TRUE',p.x,y);}ctx.shadowBlur=0;}if(selection.includes(e.id)||e.renderKind==='hero'&&selection.includes('hero')||targetId===e.id){ctx.strokeStyle='#ffe089';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+8,23,9,0,0,Math.PI*2);ctx.stroke();}}
  if(e.renderKind==='npc'){const label=worldLabelVisible(e),name=e.kind==='mini'?e.name+(game.peace?' · Peaceful':game.miniCleared(e.mini)?' · Cleared':' · Guardians'):e.name;if(label){ctx.font='bold 11px system-ui';ctx.fillStyle='#ffe4a2';ctx.shadowColor='#07140e';ctx.shadowBlur=4;ctx.fillText(name,p.x,p.y-PrototypeVisuals.height(e)-4);ctx.shadowBlur=0;}const cue=e.kind==='quests'?boardCue:e.kind==='recruiter'&&captainCue?'!':null;if(cue){ctx.fillStyle=cue==='?'?'#9fe4ad':'#f9ce72';ctx.beginPath();ctx.arc(p.x,p.y-80,16,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff1b4';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#19291e';ctx.font='bold 23px system-ui';ctx.fillText(cue,p.x,p.y-72);}}if(e.renderKind==='building'&&worldLabelVisible(e)){ctx.font='bold 10px system-ui';ctx.fillStyle='#e8ddb8';ctx.shadowColor='#07140e';ctx.shadowBlur=3;ctx.fillText(e.name||(/^barracks/.test(e.id||'')?'Barracks':'Building'),p.x,p.y-PrototypeVisuals.height(e)-4);ctx.shadowBlur=0;}if(e.renderKind==='node'){ctx.font='10px system-ui';ctx.fillStyle='#f5e7b8';ctx.fillText(e.name+' · '+Math.floor(e.amount)+' gold',p.x,p.y-25);}}
 for(const l of game.s.loot.filter(l=>l.zone===game.zoneId)){const p=screen(l);ctx.fillStyle='#4e3823';ctx.beginPath();ctx.ellipse(p.x,p.y+5,11,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#dcad54';ctx.beginPath();ctx.arc(p.x,p.y-3,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f7dfa0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y-3,4,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff0bb';ctx.fillRect(p.x-3,p.y-8,2,2);}for(const p of game.s.projectiles)drawProjectile(p);drawVisualFx();
 if(game.night()){ctx.fillStyle=game.peace?'#19243a33':'#08112a66';ctx.fillRect(0,0,canvas.width,canvas.height);}if(squadMode){ctx.strokeStyle='#ffeaa1';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(cursor.x-12,cursor.y);ctx.lineTo(cursor.x+12,cursor.y);ctx.moveTo(cursor.x,cursor.y-12);ctx.lineTo(cursor.x,cursor.y+12);ctx.stroke();}if(paused||!focused||document.hidden){ctx.fillStyle='#0006';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='bold 25px system-ui';ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText('Paused',canvas.width*.65,canvas.height*.45);}}
function frame(now){const dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;const frozen=paused||menu||!focused||document.hidden||game.s.challenge.pending||game.s.challenge.gameOver;if(menu){menuJoyTime-=dt;if(Math.abs(joy.y)>.4&&menuJoyTime<=0&&buttons.length){menuIndex=(menuIndex+(joy.y>0?1:-1)+buttons.length)%buttons.length;highlight();menuJoyTime=.3;}}audio.update(game,paused||!!menu||!focused||document.hidden||game.s.challenge.gameOver);if(!frozen){let x=(keys.KeyD?1:0)-(keys.KeyA?1:0)+joy.x,y=(keys.KeyS?1:0)-(keys.KeyW?1:0)+joy.y;if(squadMode){cursor.x=Math.max(5,Math.min(canvas.width-5,cursor.x+x*440*dt));cursor.y=Math.max(5,Math.min(canvas.height-5,cursor.y+y*440*dt));x=y=0;}else if(joy.x||joy.y){const p=world(canvas.width*.5+joy.x*100,canvas.height*.5+joy.y*100),base=world(canvas.width*.5,canvas.height*.5);x=p.x-base.x;y=p.y-base.y;}const speedFactor=Sprint.tick(dt,!!(x||y||game.hero.order)),movingHero=game.hero,was={x:movingHero.x,y:movingHero.y,zone:game.zoneId,deaths:game.s.statistics.deaths};game.tick(dt,{x,y,speedFactor});if((x||y)&&game.hero===movingHero&&PrototypeRules.movementBasicClasses[movingHero.class]&&game.zoneId===was.zone&&game.s.statistics.deaths===was.deaths&&Math.hypot(movingHero.x-was.x,movingHero.y-was.y)>.25)game.cast(1,targetId);if(x||y||game.hero.order){footstepTimer+=dt;if(footstepTimer>.35){audio.effect('footstep');footstepTimer=0;}}if(Sprint.enabled)Sprint.hud();if(autoAttack||keys.Digit1)game.cast(1,targetId);saveTimer+=dt;if(saveTimer>=5){saveTimer=0;save();}}
 const events=game.effects.splice(0);queueVisualFx(events);updateVisualFx(dt);for(const e of events)audio.effect(e.type);if(events.some(e=>['heal','rescue','learning','upgrade','level','bossDefeat','peace','quest','questComplete','supplies','miniClear','travel','death','successor','gameOver'].includes(e.type)))save();const levelEvent=events.find(e=>e.type==='level');if(levelEvent)status('Level '+levelEvent.level+'! Talent point available · press C or use Talents.');if(events.some(e=>e.type==='peace'))ending();if(game.s.phase==='awakening'&&!game.s.awakeningAck&&!menu)awakeningMenu();if(game.s.challenge.pending&&!gateDismissed&&menu?.title!=='Choose your successor')successionMenu();if(game.s.challenge.gameOver&&!gateDismissed&&!menu)gameOver();if(game.peace&&!game.s.endingAck&&!menu)ending();hudTimer+=dt;if(hudTimer>.15){hudTimer=0;updateHUD();}draw();requestAnimationFrame(frame);}
if(Sprint.enabled){Sprint.init();$('sprint-button').onpointerdown=e=>{if(e.pointerType!=='mouse')Sprint.press('touch',true);};$('sprint-button').onpointerup=$('sprint-button').onpointercancel=$('sprint-button').onpointerleave=()=>Sprint.press('touch',false);}
updateHUD();if(!loaded)chooseClass('normal');requestAnimationFrame(frame);
addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
addEventListener('appinstalled',()=>{installPrompt=null;status('Azeroth Chronicles installed. Open it from your home screen.');});
if(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'){if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(appReloadRequested){appReloadRequested=false;location.reload();}});navigator.serviceWorker.register('./sw.js').then(reg=>{appRegistration=reg;function check(){appUpdateReady=!!reg.waiting;if(appUpdateReady)status('A game update is ready. Open Menu to install it.');}check();reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(worker)worker.addEventListener('statechange',check);});}).catch(()=>{});}}
})();
