/* Existing original compositions and explicit audible/silent event catalog. */
(function (root) {
  'use strict';
  const themes = [
    {
      id: 'vale',
      bpm: 92,
      root: 60,
      lead: 'triangle',
      melody: [
        0,
        2,
        4,
        7,
        4,
        2,
        0,
        2,
        4,
        5,
        7,
        9,
        7,
        4,
        2,
        null,
        4,
        7,
        9,
        7,
        5,
        4,
        2,
        0,
        2,
        4,
        5,
        2,
        0,
        null,
        0,
        null,
      ],
    },
    {
      id: 'march',
      bpm: 78,
      root: 62,
      lead: 'sine',
      melody: [
        0,
        null,
        4,
        3,
        2,
        null,
        6,
        4,
        3,
        2,
        0,
        null,
        -1,
        2,
        3,
        null,
        4,
        6,
        7,
        6,
        4,
        null,
        3,
        2,
        0,
        2,
        3,
        4,
        2,
        null,
        0,
        null,
      ],
    },
    {
      id: 'highlands',
      bpm: 84,
      root: 55,
      lead: 'triangle',
      melody: [
        0,
        0,
        4,
        null,
        7,
        7,
        5,
        4,
        2,
        null,
        0,
        2,
        4,
        null,
        2,
        null,
        7,
        9,
        7,
        5,
        4,
        2,
        4,
        null,
        5,
        4,
        2,
        0,
        -1,
        2,
        0,
        null,
      ],
    },
    {
      id: 'frontier',
      bpm: 100,
      root: 57,
      lead: 'triangle',
      melody: [
        0,
        2,
        0,
        4,
        3,
        null,
        2,
        0,
        -2,
        0,
        2,
        3,
        4,
        3,
        2,
        null,
        4,
        5,
        7,
        5,
        4,
        null,
        3,
        2,
        0,
        2,
        3,
        2,
        0,
        -2,
        0,
        null,
      ],
    },
    {
      id: 'crown',
      bpm: 72,
      root: 60,
      lead: 'sine',
      melody: [
        7,
        null,
        6,
        4,
        3,
        null,
        2,
        0,
        -1,
        null,
        0,
        2,
        3,
        2,
        0,
        null,
        4,
        null,
        5,
        7,
        6,
        null,
        4,
        3,
        2,
        0,
        2,
        3,
        2,
        null,
        0,
        null,
      ],
    },
    {
      id: 'crypt',
      bpm: 76,
      root: 57,
      lead: 'sine',
      melody: [
        0,
        null,
        4,
        null,
        3,
        2,
        null,
        0,
        -1,
        null,
        2,
        null,
        3,
        2,
        0,
        null,
        4,
        null,
        7,
        6,
        4,
        null,
        3,
        2,
        0,
        null,
        2,
        3,
        2,
        null,
        0,
        null,
      ],
    },
    {
      id: 'archive',
      bpm: 82,
      root: 62,
      lead: 'sine',
      melody: [
        0,
        4,
        null,
        7,
        6,
        null,
        4,
        3,
        2,
        null,
        0,
        3,
        2,
        null,
        -1,
        null,
        4,
        7,
        null,
        9,
        7,
        6,
        4,
        null,
        3,
        4,
        2,
        null,
        0,
        2,
        0,
        null,
      ],
    },
    {
      id: 'mine',
      bpm: 96,
      root: 53,
      lead: 'triangle',
      melody: [
        0,
        0,
        null,
        3,
        0,
        2,
        4,
        null,
        3,
        3,
        null,
        2,
        0,
        null,
        -2,
        null,
        4,
        4,
        null,
        7,
        5,
        4,
        3,
        null,
        2,
        0,
        2,
        3,
        0,
        null,
        0,
        null,
      ],
    },
    {
      id: 'abyss',
      bpm: 90,
      root: 55,
      lead: 'triangle',
      melody: [
        0,
        2,
        3,
        null,
        4,
        3,
        2,
        0,
        -2,
        null,
        0,
        2,
        3,
        2,
        null,
        0,
        7,
        6,
        4,
        null,
        5,
        4,
        3,
        2,
        0,
        2,
        3,
        4,
        2,
        null,
        0,
        null,
      ],
    },
    {
      id: 'citadel',
      bpm: 70,
      root: 60,
      lead: 'sine',
      melody: [
        0,
        null,
        7,
        null,
        6,
        4,
        null,
        3,
        2,
        null,
        4,
        null,
        3,
        2,
        0,
        null,
        4,
        null,
        7,
        9,
        7,
        null,
        6,
        4,
        3,
        null,
        2,
        4,
        2,
        null,
        0,
        null,
      ],
    },
    {
      id: 'field-boss',
      bpm: 112,
      root: 50,
      lead: 'triangle',
      melody: [0, 0, 3, 4, 0, 2, 3, null, 5, 4, 3, 2, 0, 0, -1, null],
    },
    {
      id: 'dungeon-boss',
      bpm: 104,
      root: 48,
      lead: 'triangle',
      melody: [0, 3, 4, 7, 6, 4, 3, 2, 0, 0, -1, 2, 3, 4, 2, null],
    },
    {
      id: 'darklord-boss',
      bpm: 88,
      root: 45,
      lead: 'triangle',
      melody: [0, null, 0, 3, 4, null, 6, 4, 3, 2, 0, null, -1, 0, 2, null],
    },
    {
      id: 'finale',
      bpm: 80,
      root: 60,
      lead: 'sine',
      melody: [
        0,
        2,
        4,
        7,
        9,
        null,
        7,
        4,
        5,
        7,
        9,
        11,
        12,
        null,
        7,
        null,
        4,
        5,
        7,
        9,
        7,
        4,
        2,
        null,
        0,
        4,
        7,
        9,
        7,
        4,
        0,
        null,
      ],
    },
  ];
  // A (8 bars), varied A (8), contrasting B (8), resolved A (8): 256 eighth notes.
  const colors = {
    vale: 'triangle',
    march: 'sine',
    highlands: 'sawtooth',
    frontier: 'triangle',
    crown: 'sine',
    crypt: 'triangle',
    archive: 'sine',
    mine: 'triangle',
    abyss: 'sawtooth',
    citadel: 'sine',
  };
  for (const t of themes) {
    const phrase = t.melody;
    const a = Array.from({ length: 64 }, (_, i) => phrase[i % phrase.length]);
    const b = Array.from({ length: 64 }, (_, i) =>
      i % 8 === 7
        ? null
        : i % 4 === 0
          ? 7 + [0, 2, 1, -1][Math.floor(i / 16)]
          : phrase[(i + 12) % phrase.length] === null
            ? null
            : 7 - phrase[(i + 12) % phrase.length],
    );
    t.form = [
      ...a,
      ...a.map((n, i) => (n === null ? null : n + (i % 16 === 10 ? 1 : 0))),
      ...b,
      ...a.map((n, i) =>
        n === null ? null : i > 55 ? Math.max(0, 3 - Math.floor((i - 56) / 2)) : n,
      ),
    ];
  }
  const scale = (peace) => (peace ? [0, 2, 4, 5, 7, 9, 11] : [0, 2, 3, 5, 7, 8, 10]);
  const pitch = (degree, peace) => {
    const s = scale(peace),
      oct = Math.floor(degree / 7),
      i = ((degree % 7) + 7) % 7;
    return s[i] + 12 * oct;
  };
  const defaults = { master: 0.65, music: 0.4, ambience: 0.25, effects: 0.7, muted: false };
  const eventNotes = {
    purchase: [75, 79],
    successor: [60, 64, 72],
    gameOver: [43, 38, 31],
    heal: [64, 67, 72],
    gold: [84, 88],
    level: [72, 76, 79, 84],
    rescue: [67, 72, 76],
    learning: [60, 64, 67],
    upgrade: [64, 67, 72],
    travel: [55, 62, 67],
    eliteWarning: [45, 46, 52],
    eliteFrenzy: [43, 48, 55],
    captainPhase: [46, 53, 58],
    captainSummon: [43, 50, 55],
    warning: [57, 57],
    bossDefeat: [60, 67, 72],
    awakening: [48, 55, 60, 67],
    peace: [60, 64, 67, 72, 76, 79],
    death: [50, 46, 43],
    reset: [48, 43],
    construction: [48, 55, 60],
    barracksUpgrade: [52, 59, 64],
    questComplete: [64, 67, 72],
    quest: [60, 64],
    supplies: [72, 76],
    miniClear: [60, 67],
    squadRecall: [55, 62],
    squadDoctrine: [60, 65],
    manaDrain: [50, 43],
    companionVitality: [55, 62, 67],
    talentRespec: [60, 55],
    rangerSupportTraining: [64, 71],
    expeditionSupport: [60, 67, 72],
    expeditionRank: [60, 67, 72, 79],
    rest: [55, 60, 64],
    tributeDiscovery: [72, 79, 84],
    sideInteriorDiscovery: [52, 59, 64],
  };
  const contextualEffectTypes = new Set([
    'melee',
    'swing',
    'projectileLaunch',
    'projectileImpact',
    'spell',
    'charged',
    'chargedArea',
    'chargedImpact',
    'hurt',
    'hit',
    'basicComboFinisher',
    'companionSkill',
  ]);
  const api = { themes, colors, scale, pitch, defaults, eventNotes, contextualEffectTypes };
  if (typeof module !== 'undefined') module.exports = api;
  else root.PrototypeAudioCatalog = api;
})(typeof window !== 'undefined' ? window : globalThis);
