/* Approved content tables from the audited expansion design. */
const PrototypeData = {
  regions: [
    {
      id: 'vale',
      name: 'Greenwood Vale',
      levels: '1 to 4',
      size: 2700,
      town: 'Millhaven',
      minor: 'Orchard Hamlet',
      biome: 'Woodland and farmland',
      transport: 'Merchant wagon',
      fare: 25,
      route:
        "Millhaven at (300, 350) connects to Orchard Hamlet at (900, 700), the Forest Crypt at (2150, 2100), and the merchant wagon stand behind Millhaven at (135, 540). A north to south river at x 1200 can be crossed at the mill bridge near y 750 and a southern footbridge near y 1750. Thornfang's den lies beyond the settled orchard country near (760, 1750).",
      obstacle:
        'Dense thickets close direct shortcuts, but broad woodland paths remain walkable. The river, lake shore and mill pond are impassable water. Houses and fences shape streets without blocking exits.',
      exploration:
        'Millhaven, Orchard Hamlet and the working mill remain a rural woodland country. Beyond the local goblin camps and skeleton territories, the Crypt Guardian oversees an unfinished seasonal retreat for the Dark Lord and his trusted friends. The Guardian is an outsider and trusted friend who acts as caretaker and project overseer. The Dark Lord owns these woods because he wanted a place here; Dark Crown remains his permanent seat.',
      resource: 640,
      questgold: 160,
      questxp: 600,
      enemy_count: 32,
      gold_range: [4, 8],
      enemy_xp: 18,
      guards: 10,
      guard_xp: 4,
      route_kills: 16,
    },
    {
      id: 'march',
      name: 'Flooded Marches',
      levels: '4 to 7',
      size: 3000,
      town: 'Reedport',
      minor: 'Fisher Camp',
      biome: 'Wetland and lake shores',
      transport: 'Ferryman',
      fare: 60,
      route:
        "The wagon stops behind Reedport near the western map edge at (145, 1380). Raised roads connect Fisher Camp at (1050, 500), Mirejaw's marsh territory near (2180, 1120), the Sunken Archive entrance at (2600, 2350), and the Reedport ferry at (2250, 650).",
      obstacle:
        'A lake occupies the central basin. Two raised crossings and a bridge provide useful choices around it. Reeds are decorative or collision marked; open water is consistently impassable.',
      exploration:
        'Reedport and Fisher Camp live by fishing while Mirejaw, Reed Beasts and night Wraiths keep their own territories. The Drowned Keeper is a capable scholar, fishing enthusiast and councillor who proposed capturing the specialists. His nickname comes from a past drowning; his active Archive now faces a separate preservation emergency. Neri is being forced to save the records; outside, removed books and restoration supplies mark the emergency.',
      resource: 640,
      questgold: 380,
      questxp: 1200,
      enemy_count: 40,
      gold_range: [8, 14],
      enemy_xp: 38,
      guards: 14,
      guard_xp: 7,
      route_kills: 16,
    },
    {
      id: 'highlands',
      name: 'Ironroot Highlands',
      levels: '7 to 10',
      size: 3400,
      town: 'Stonecross',
      minor: 'Quarry Outpost',
      biome: 'Mountains and pine forest',
      transport: 'Pack beast caravan',
      fare: 110,
      route:
        "The ferry landing at (425, 1900) climbs by switchbacks to Stonecross at (850, 1500), Quarry Outpost at (1750, 1150), the Ridge Tyrant's mountain watchtower near (2700, 700), the Colossus Mine entrance at (2850, 2350), and the caravan stand on Stonecross's western approach at (590, 1420).",
      obstacle:
        'Cliffs divide the plateau into connected terraces. Switchbacks, a stone bridge and a timber crossing provide routes. Rock walls and pine thickets block movement and projectiles consistently.',
      exploration:
        'The Dark Lord took these mineral-rich mountains long ago; Ironroot now supplies his crowns. His Master of Coin, the Ridge Tyrant, keeps ore, wages and caravans moving and calls it proof of better rule. Stonecross trades and raises families; Quarry Outpost sorts and hauls. Some welcome regular payday, others resent who owns the mountain. Wolves keep wild hunting grounds; Ogres work stone, cook, sleep and play at their own hearths.',
      resource: 640,
      questgold: 700,
      questxp: 1800,
      enemy_count: 48,
      gold_range: [14, 22],
      enemy_xp: 44,
      guards: 18,
      guard_xp: 8,
      route_kills: 20,
    },
    {
      id: 'frontier',
      name: 'Ashen Frontier',
      levels: '10 to 13',
      size: 3400,
      town: 'Emberwatch',
      minor: 'Burned Hamlet',
      biome: 'Scorched woodland and fortified roads',
      transport: 'Dragon rider',
      fare: 180,
      route:
        "The caravan stops behind Emberwatch near (155, 615). The old damaged road has become a working occupation corridor: convoy and repair yards feed the guarded ravine crossing, inspection spurs and the Ashen Warlord's checkpoint near (2600, 1650), while a supply route supports the Dark Lord’s air-superiority project at Abyss Bastion (3000, 2700); the civilian transport dragon landing sits behind Emberwatch near (145, 260), distinct from Abyss Bastion's military dragon operation.",
      obstacle:
        'A ravine still splits the scarred region. The guarded northern crossing and longer burned-forest route remain the practical alternatives; charred trunks, fort walls, repairs and collapsed masonry leave visible gaps rather than a healed landscape.',
      exploration:
        'Ashen Frontier is a province recovering under oppression: Emberwatch functions under control, Burned Hamlet mixes ruins with repair and everyday survival, and roadside work yards, bivouacs, drill camps, inspection posts and checkpoint support spaces show the occupiers investing in reliable movement and supply. The Ruined Shrine barracks, ordinary-monster forts, night Stalker hold and guarded approach to the Dark Lord’s dragon-breeding and flight-preparation center preserve the damage and danger beneath that new order.',
      resource: 640,
      questgold: 1200,
      questxp: 2400,
      enemy_count: 56,
      gold_range: [22, 32],
      enemy_xp: 50,
      guards: 22,
      guard_xp: 9,
      route_kills: 24,
    },
    {
      id: 'crown',
      name: 'Dark Crown',
      levels: '13 to 16 and beyond',
      size: 3800,
      town: 'Crownwatch',
      minor: 'Ash Refuge',
      biome: 'Volcanic highland and dark fortifications',
      transport: 'Dragon return route',
      fare: 0,
      route:
        "The dragon return platform sits northwest of Crownwatch at the end of a dedicated administrative road. Crownwatch and Ash Refuge feed a labor and levy network, while separate military roads lead toward the Citadel of Ashes at (2400, 1100), Crown field barracks and eastern control gates. Cindermaw's roosting territory near (2200, 1750) occupies its own ash-beast sphere. A southern wild track and a fortress service road converge on the siege works and final fortress gate near (3000, 3000); beyond it, the Dark Lord waits in his courtyard around (3250, 3200).",
      obstacle:
        'Lava channels, sheer ravines and fortress walls are impassable. Bridges, controlled roads and distributed border gates make access legible. Hazard patches sit beside viable safe routes; narrow combat spaces still permit retreat.',
      exploration:
        "Dark Crown is the lived-in machinery of the regime: Crownwatch and its labor quarter, military command around the Citadel, Cindermaw's ash-beast domain, Crown barracks and toll redoubts, siege logistics, monster-held peripheral ground and the increasingly formal fortress approach. The ruined foundry, crystal shelf and transport roads show how supplies and tribute move through the same hierarchy the player is dismantling.",
      resource: 640,
      questgold: 1900,
      questxp: 3000,
      enemy_count: 64,
      gold_range: [30, 44],
      enemy_xp: 67,
      guards: 26,
      guard_xp: 10,
      route_kills: 24,
    },
  ],
  bosses: [
    {
      id: 'thorn',
      region: 'vale',
      kind: 'field',
      name: 'Thornfang',
      level: 2,
      captive: 'Mira the Village Instructor',
      service: 'Learn skill 2 and train skills 1 and 2 to rank 2',
      requires: [1],
      hp: 1200,
      damage: 10,
      gold: 35,
      xp: 30,
      place: 'Orchard den',
      attacks: [
        'Bite: short frontal arc, 0.8 second warning and 0.8 second recovery.',
        'Pounce: marks a landing circle for 1.3 seconds; misses leave a 1.5 second opening.',
        'Root line: a narrow ground line warns for 1.2 seconds and briefly slows on contact.',
        'Den howl: warns for 1.5 seconds, then calls three low health pups; a maximum of three pups may be alive.',
      ],
    },
    {
      id: 'crypt',
      region: 'vale',
      kind: 'dungeon',
      name: 'Crypt Guardian',
      level: 3,
      captive: 'Borin the Village Smith',
      service: 'Village weapon improvements and basic equipment crafting',
      requires: [1],
      hp: 650,
      damage: 16,
      gold: 65,
      xp: 55,
      place: 'Forest Crypt',
      attacks: [
        'Bone sweep: frontal cone, 1.0 second warning and a safe rear arc.',
        'Bone volley: three visible projectiles with 1.2 second windup; solid pillars block them.',
        'Grave call: 1.6 second warning, then three skeletons; existing summons count toward the cap.',
        'Draining ground: marks one patch for 1.6 seconds; it lasts 4 seconds and leaves a route around it.',
      ],
    },
    {
      id: 'mire',
      region: 'march',
      kind: 'field',
      name: 'Mirejaw',
      level: 5,
      captive: 'Sela the Frontier Instructor',
      service: 'Learn skills 3, 4 and 6 and train supported skills to rank 3',
      requires: [1, 2],
      hp: 1100,
      damage: 24,
      gold: 100,
      xp: 105,
      place: 'Marsh island',
      attacks: [
        'Jaw snap: frontal bite with 0.9 second warning.',
        'Mire rush: straight charge marked for 1.4 seconds; collisions end the charge.',
        'Bog spit: three puddles warn for 1.5 seconds and slow for 4 seconds; damage ticks have a fixed interval.',
        'Brood call: summons three mirelings after 1.6 seconds; no more than three remain alive.',
      ],
    },
    {
      id: 'archive',
      region: 'march',
      kind: 'dungeon',
      name: 'Drowned Keeper',
      level: 6,
      captive: 'Neri the Alchemist',
      service:
        'Advanced Ranger Heal and Mana Recovery training, Companion Vitality and talent reset',
      requires: [1, 2, 3],
      hp: 1600,
      damage: 28,
      gold: 150,
      xp: 162,
      place: 'Sunken Archive',
      attacks: [
        'Anchor swing: frontal sweep with 1.1 second warning.',
        'Water jets: two parallel lanes warn for 1.5 seconds and leave a safe channel.',
        'Undertow: one patch slows rather than immobilizes; 1.5 second warning and 4 second duration.',
        'Echo call: summons three drowned echoes after 1.7 seconds; the arena remains navigable.',
      ],
    },
    {
      id: 'ridge',
      region: 'highlands',
      kind: 'field',
      name: 'Ridge Tyrant',
      role: "The Dark Lord's Master of Coin",
      history:
        'A competent economist who treats wages, maintained roads and circulating crowns as his case for authoritarian rule. Hired ridge archers protect his payroll and mineral caravans; their contracts bring them beyond the Frontier.',
      level: 8,
      captive: 'Orin the Highland Instructor',
      service: 'Learn skill 5 and train learned skills to rank 4',
      requires: [1, 2, 3, 4, 6],
      hp: 2400,
      damage: 36,
      gold: 220,
      xp: 262,
      place: 'Mountain watchtower',
      attacks: [
        'Hammer blow: frontal arc, 1.0 second warning.',
        'Boulder throw: marks one landing point for 1.5 seconds.',
        'Ridge charge: straight lane with 1.5 second warning and a 2 second recovery.',
        'War cry: calls three ridge archers after 1.8 seconds; the summon action uses a short cooldown before replenishing losses.',
      ],
    },
    {
      id: 'mine',
      region: 'highlands',
      kind: 'dungeon',
      name: 'Stone Colossus',
      history:
        'An ancient guardian exposed by the older Ironroot workings. The regime routes production around its territory rather than controlling it; new supports and haulage lanes stop at the older stone. Dara is compelled to repair mining equipment so shipments can continue.',
      level: 9,
      captive: 'Dara the Highland Smith',
      service: 'Highland weapons armor and equipment improvements',
      requires: [1, 2, 3, 4, 6],
      hp: 3200,
      damage: 42,
      gold: 300,
      xp: 375,
      place: 'Colossus Mine',
      attacks: [
        'Stone slam: circle warns for 1.6 seconds and exposes the core for 2.5 seconds afterward.',
        'Rockfall: three separated circles warn for 1.7 seconds; at least one connected safe route remains.',
        'Shockwave rings: visible expanding rings follow a 1.6 second windup and can be crossed after they pass.',
        'Wall rush: lane warns for 1.7 seconds; striking a marked pillar exposes the core for 3 seconds.',
        'Stonebound call: summons three ogres; TRUE form replenishes its six-unit elite warband.',
      ],
    },
    {
      id: 'warlord',
      region: 'frontier',
      kind: 'field',
      name: 'Ashen Warlord',
      level: 11,
      captive: 'Lyss the Advanced Instructor',
      service: 'Learn skill 7 and train learned skills to rank 6',
      requires: [1, 2, 3, 4, 5, 6],
      hp: 4300,
      damage: 48,
      gold: 380,
      xp: 525,
      place: 'Occupied checkpoint',
      attacks: [
        'Cleaving combo: two marked frontal arcs with a safe interval; 1.2 second initial warning.',
        'Banner bombardment: two marked circles warn for 1.8 seconds.',
        'Guard command: calls four guards after 1.8 seconds; TRUE form commands a larger eight-unit warband.',
        'Pursuit charge: marks a lane for 1.6 seconds and leaves 2.5 seconds of recovery.',
      ],
    },
    {
      id: 'abyss',
      region: 'frontier',
      kind: 'dungeon',
      name: 'Abyss Dragon',
      level: 12,
      captive: 'Eren the Runewright',
      service: 'Advanced weapon and armor improvements',
      requires: [1, 2, 3, 4, 5, 6],
      hp: 5800,
      damage: 54,
      gold: 480,
      xp: 725,
      place: 'Abyss Bastion',
      attacks: [
        'Flame cone: 1.5 second warning with a safe flank.',
        'Wing shockwave: an expanding ring follows a 1.7 second warning.',
        'Shadow flight: two marked landing circles resolve sequentially after 1.8 second warnings.',
        'Hatchling call: summons three hatchlings after 2 seconds; no more than three remain alive.',
      ],
    },
    {
      id: 'citadel',
      region: 'crown',
      kind: 'dungeon',
      name: 'Ash Sentinel',
      level: 15,
      captive: 'Tovan the Final Instructor',
      service: 'Learn skill 8 and train learned skills to rank 8',
      requires: [1, 2, 3, 4, 5, 6, 7],
      hp: 8500,
      damage: 62,
      gold: 700,
      xp: 1075,
      place: 'Citadel of Ashes',
      attacks: [
        'Armor slam: circle warns for 1.6 seconds; armor opens for 3 seconds afterward.',
        'Ash lanes: two lanes warn for 1.8 seconds and leave a clear safe lane.',
        'Sentinel advance: slow frontal pursuit begins after a 1.8 second signal and ends in 2.5 seconds of recovery.',
        'Furnace pulses: three staggered circles warn for 2 seconds; no unavoidable intersection with a trap pulse.',
        'Ash guard muster: summons three Crown soldiers; TRUE form replenishes its six-unit elite warband.',
      ],
    },
    {
      id: 'cindermaw',
      region: 'crown',
      kind: 'field',
      name: 'Cindermaw',
      level: 14,
      captive: 'Vera the Master Smith',
      service: 'Final equipment improvements and Shared Strength training before the Dark Lord',
      requires: [1, 2, 3, 4, 5, 6, 7],
      hp: 7000,
      damage: 58,
      gold: 560,
      xp: 900,
      place: "Cindermaw's roost",
      attacks: [
        'Cinder rend: broad frontal sweep with a 1.1 second warning.',
        'Ash rush: a straight burning charge marked for 1.5 seconds.',
        'Furnace spit: three hot landing circles warn for 1.6 seconds and briefly persist.',
        'Brood command: calls three ash beasts after 1.8 seconds; no more than three remain alive.',
      ],
    },
    {
      id: 'darklord',
      region: 'crown',
      kind: 'final',
      name: 'Dark Lord',
      level: 16,
      captive: null,
      service: null,
      requires: [1, 2, 3, 4, 5, 6, 7, 8],
      hp: 11000,
      damage: 70,
      gold: 850,
      xp: 1375,
      place: 'Dark fortress courtyard',
      attacks: [
        'Dark cleave: marked frontal combo begins after 1.3 seconds.',
        'Fortress bombardment: three circles resolve sequentially with 1.9 second warnings.',
        'Black guard call: summons three guards after 2 seconds; guards have readable ranged attacks.',
        'Crown phase: at half health, a 2 second signal starts alternating safe sectors; each pulse has its own warning.',
      ],
    },
  ],
  skills: [
    [1, 'Basic attack', 1, 0, 'start', 20],
    [2, 'Second attack', 1, 40, 'thorn', 35],
    [3, 'Self-Heal', 1, 75, 'mire', 45],
    [4, 'Defense or mobility', 1, 160, 'mire', 60],
    [6, 'Frequent special', 1, 220, 'mire', 50],
    [5, 'Area attack', 1, 400, 'ridge', 80],
    [7, 'Advanced special', 1, 1000, 'warlord', 140],
    [8, 'Final special', 1, 1600, 'citadel', 180],
  ],
  quests: [
    ['vale', 'A Teacher Taken', 'Defeat Thornfang; free Mira', 45, 50],
    ['vale', 'Roads Under Threat', 'Defeat 5 outdoor enemies in Greenwood Vale', 25, 88],
    ['vale', 'Stolen Stores', "Recover 2 caches from Thornfang's Treasury", 35, 100],
    ['vale', 'An Unfinished Retreat', 'Defeat Crypt Guardian; free Borin', 45, 137],
    ['vale', 'Keeping Trade Open', 'Visit Mill bridge and wagon stand', 0, 50],
    ['vale', 'Who Owns the Woods?', 'Discover any 3 Greenwood Vale sites', 10, 175],
    ['march', 'The Island Prisoner', 'Defeat Mirejaw; free Sela', 100, 225],
    ['march', 'Unsafe Crossings', 'Defeat 6 outdoor enemies in Flooded Marches', 65, 175],
    ['march', 'Records at Risk', 'Defeat Drowned Keeper; free Neri', 110, 300],
    ['march', 'Hidden Provisions', "Recover 3 caches from Mirejaw's Treasury", 80, 175],
    ['march', 'Shadows After Sundown', 'Visit Lantern shore at night; defeat 2 wraiths', 0, 150],
    ['march', 'Beyond the Main Road', 'Discover any 3 Flooded Marches sites', 25, 175],
    ['highlands', "The Tyrant's Grip", 'Defeat Ridge Tyrant; free Orin', 180, 350],
    [
      'highlands',
      'Quarry Workers at Risk',
      'Defeat 7 outdoor enemies in Ironroot Highlands',
      120,
      350,
    ],
    ['highlands', 'An Unwilling Hand', 'Defeat Stone Colossus; free Dara', 220, 475],
    [
      'highlands',
      "The Master's Reserve",
      "Recover 3 caches from Ridge Tyrant's Treasury",
      140,
      225,
    ],
    ['highlands', 'Whose Mountain?', 'Discover any 3 Ironroot Highlands sites', 20, 250],
    ['highlands', 'Follow the Crowns', 'Visit Stonecross ore vein and caravan stand', 20, 150],
    ['frontier', 'Captive at the Front', 'Defeat Ashen Warlord; free Lyss', 300, 475],
    [
      'frontier',
      'An Army Needs Supplies',
      'Visit convoy, guarded ravine bridge and checkpoint',
      250,
      450,
    ],
    ['frontier', 'Wings of War', 'Defeat Abyss Dragon; free Eren', 400, 625],
    ['frontier', 'Roads Still Contested', 'Defeat 8 outdoor enemies in Ashen Frontier', 200, 400],
    ['frontier', 'Rebuilding Under Guard', 'Discover any 3 Ashen Frontier sites', 50, 300],
    [
      'frontier',
      'A Different Kind of Flight',
      'Visit civilian dragon landing behind Emberwatch',
      0,
      150,
    ],
    ['crown', 'The Last Lesson', 'Defeat Ash Sentinel; free Tovan', 600, 825],
    ['crown', 'Hostile Ground', 'Defeat 8 outdoor enemies in Dark Crown', 300, 475],
    ['crown', 'A Smith in Chains', 'Defeat Cindermaw; free Vera', 650, 825],
    ['crown', "Dreadmaw's Duty", "Recover 3 caches from Cindermaw's Treasury", 250, 400],
    ['crown', 'The Machinery of Rule', 'Discover any 3 Dark Crown sites', 60, 250],
    ['crown', 'Ready for the Dark Lord', 'Free Tovan and Vera; reach fortress gate', 40, 225],
  ],
  // One authored, observable payoff per regional quest; index matches quests above.
  questNarration: [
    "With Mira free, Greenwood gains back a teacher. Thornfang's defeat has opened a path home.",
    "Fewer raiders trouble the mill road for now. Greenwood's farms still need watching.",
    "Thornfang's Treasury held more than a wolf could use. These stolen stores belong beyond his den.",
    "The Forest Crypt was built for a retreat, not a prison. Borin's escape spoils the Guardian's hospitality.",
    'From the mill bridge to the wagon stand, Millhaven has a road to the wider world. Keeping it open is another matter.',
    "Farms, creature territories, and hidden paths all belong to Greenwood's daily life, whatever its distant ruler claims.",
    'Mirejaw can no longer keep Sela captive. The marsh remains dangerous, but one prisoner is going home.',
    'Several threats have fallen along the causeways. The reeds still make it hard to see what lies ahead.',
    'Neri leaves the Sunken Archive alive. Its threatened records remain, and saving them will take a different kind of work.',
    "Behind Mirejaw's guarded hoard are ordinary provisions. In the Marches, even a supply crate is worth a fight.",
    'Lantern shore grows quiet again. The wraiths are gone for now; night will return.',
    'Raised roads, fishing camps, and flooded ruins shape this region. There is more to the Marches than the main road.',
    "Orin is free of the Ridge Tyrant's grasp. The mountain's ore still travels through the regime's hands.",
    'The quarry route has fewer dangers for a while. Stonecross still depends on the work that travels it.',
    "Dara is leaving the Colossus Mine behind. A smith's tools can serve different hands once the chains are gone.",
    'The Ridge Tyrant kept a comfortable reserve. Ironroot has been profitable for someone.',
    'Wolves, ogres, miners, and caravan crews all have a place in Ironroot. No single title explains a mountain.',
    "Stonecross's ore leaves the mountain by caravan. The Dark Lord's wealth has a very ordinary beginning.",
    "Lyss is free of the Ashen Warlord's checkpoint. The occupied road remains scarred by the machinery around it.",
    'Convoys, repair yards, guarded crossings: the occupation needs more than soldiers to keep its roads.',
    'Eren is free of Abyss Bastion. Its dragon preparations were built for war, not ordinary travelers.',
    'The Frontier road has fewer enemies for now. Its barricades and inspection posts still tell you who holds it.',
    'The Frontier is not only ruins. Repair work and everyday life persist beside the scars of occupation.',
    'Behind Emberwatch, the civilian dragon landing offers a very different journey from the military aerie.',
    'Tovan is free of the Ash Sentinel. Even in Dark Crown, the regime cannot keep every teacher silent.',
    'The approach remains hostile despite your victories. Dark Crown is defended in layers.',
    "Vera is free of Cindermaw's holding. Even the regime's heartland has smiths who never chose their masters.",
    "Cindermaw's Treasury is another guarded storehouse. Even at the seat of power, supplies have to come from somewhere.",
    'From labor quarters to siege works, Dark Crown is an organized machine. Its roads keep the fortress supplied.',
    'The fortress gate rises ahead. Tovan and Vera are free, but the Dark Lord still waits beyond it.',
  ],
  economy: {
    learning: 3495,
    maximum_upgrades: 17080,
    sample_upgrades: 1540,
    quest_gold: 4340,
    quest_xp: 9000,
    finite_resources: 3200,
    boss_gold: 3840,
    xp_to_16: 14400,
    main_route_xp: 16105,
    outdoor_enemies: 240,
    dungeon_guards: 50,
    night_max_health: 1.4,
    night_max_damage: 1.35,
  },
  towns: [
    [300, 350],
    [350, 1100],
    [850, 1500],
    [450, 500],
    [350, 600],
  ],
  minors: [
    [900, 700],
    [1050, 500],
    [1750, 1150],
    [1300, 1000],
    [1250, 1800],
  ],
  ports: [
    [135, 540],
    [2250, 650],
    [590, 1420],
    [145, 260],
    [350, 600],
  ],
  entrances: [
    [2150, 2100],
    [2600, 2350],
    [2850, 2350],
    [3000, 2700],
    [2400, 1100],
  ],
  fields: [
    [760, 1750],
    [2180, 1120],
    [2700, 700],
    [2600, 1650],
    [3250, 3200],
  ],
  colors: ['#294b36', '#26444b', '#485447', '#50413b', '#343644'],
  species: [
    [
      ['goblin', 'Goblin', '🧌'],
      ['skeleton', 'Skeleton', '💀'],
    ],
    [
      ['mireling', 'Mireling', '🐊'],
      ['reedbeast', 'Reed beast', '🐸'],
    ],
    [
      ['wolf', 'Wolf', '🐺'],
      ['ogre', 'Ogre', '👺'],
    ],
    [
      ['orc', 'Orc', '👹'],
      ['archer', 'Raider archer', '🏹'],
    ],
    [
      ['ashbeast', 'Ash beast', '🦂'],
      ['crownguard', 'Crown soldier', '👿'],
    ],
  ],
};
if (typeof module !== 'undefined') module.exports = PrototypeData;
