/* Deterministic campaign rules, independent of the browser and renderer. */
(function(root){
'use strict';
const D=typeof PrototypeData!=='undefined'?PrototypeData:require('./data.js');
const clone=x=>JSON.parse(JSON.stringify(x)), clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const classes={paladin:{icon:'🛡️',hp:120,mp:60,power:18,armor:8,speed:300},mage:{icon:'🧙‍♀️',hp:90,mp:100,power:22,armor:3,speed:300},ranger:{icon:'🏹',hp:105,mp:70,power:20,armor:5,speed:320}};
const ceilings={thorn:2,mire:3,ridge:4,warlord:6,citadel:8};
const dungeonIds=D.bosses.filter(b=>b.kind==='dungeon').map(b=>b.id);
const costs=[0,0,15,10,25,40,20,45,60],cooldowns=[0,.85,3,8,14,9,4,15,24];
class Campaign{
 constructor(mode='normal',heroClass='paladin',random=Math.random,options={}){
  if(!['normal','nightmare'].includes(mode)||!classes[heroClass])throw Error('Unknown mode or class');
  this.random=random;this.messages=[];this.effects=[];this.s={version:4,mode,phase:'adventure',clock:0,time:0,zone:'vale',refuge:'vale',nextId:1,normal:{},true:{},earlyRoll:{},pending:{},origins:{},late:{},victories:{},rescued:{},keys:{},paid:{},tickets:{},recovery:{},quests:{},discovered:{},gathered:{},fountains:{},zones:{},loot:[],projectiles:[],hazards:[],streak:{key:null,count:0},endingAck:false,holdFire:false,statistics:{kills:0,deaths:0,goldEarned:0,suppliesUsed:0,bossSeconds:{},events:[]}};
  const c=classes[heroClass];this.s.hero={class:heroClass,x:300,y:350,hp:c.hp,maxHp:c.hp,mp:c.mp,maxMp:c.mp,level:1,xp:0,gold:30,power:c.power,armor:c.armor,speed:c.speed,skills:[1,0,0,0,0,0,0,0],cd:Array(8).fill(0),immune:0,haste:0,weapon:0,armorTier:0,reforges:{},potions:{health:1,mana:1},tonic:false,potionCd:0,slow:0,talents:[0,0,0,0],talentPoints:0};
  this.s.challenge={succession:options.succession===true,fallen:[],pending:false,gameOver:false};
  this.s.party=[this.unit('soldier',260,390),this.unit('worker',350,380)];this.zone();
 }
 get hero(){return this.s.hero;} get zoneId(){return this.s.zone;} get peace(){return this.s.phase==='peace';}
 regionIndex(id=this.s.zone){const boss=D.bosses.find(b=>b.id===id);return D.regions.findIndex(r=>r.id===(boss?.region||id));}
 definition(){return D.regions[this.regionIndex()];}
 isDungeon(){return dungeonIds.includes(this.s.zone);}
 night(){return !this.peace&&this.s.mode==='nightmare'||this.s.clock%720>=480;}
 nightPoints(){return this.s.mode==='nightmare'?Object.keys(this.s.victories).length:Math.min(15,Object.keys(this.s.normal).length+Object.keys(this.s.late).length);}
 multipliers(){const n=this.nightPoints();return this.night()&&!this.peace?{hp:1.10+.03*n,damage:1.15+.02*n}:{hp:1,damage:1};}
 event(type,data={}){this.s.statistics.events.push({time:Math.round(this.s.time),type,...data});if(this.s.statistics.events.length>400)this.s.statistics.events.shift();this.effects.push({type,...data});}
 say(text){this.messages.push(text);if(this.messages.length>7)this.messages.shift();}
 boss(id){return D.bosses.find(b=>b.id===id);}
 unit(type,x,y){const base={worker:[85,4,'👷'],soldier:[140,12,'⚔️'],archer:[100,15,'🏹']}[type];return {id:'ally-'+this.s.nextId++,type,x,y,hp:base[0]+12*this.hero.level,maxHp:base[0]+12*this.hero.level,damage:base[1],icon:base[2],cd:0,order:null,carry:0};}
 blocked(x,y,zone=this.s.zone,radius=15){
  const i=this.regionIndex(zone),dungeon=dungeonIds.includes(zone),size=dungeon?1500:D.regions[i]?.size;
  if(!size||x<40+radius||y<40+radius||x>size-40-radius||y>size-40-radius)return true;
  if(dungeon){if(x>710-radius&&x<780+radius&&y>120&&y<1200&&!((y>480+radius&&y<680-radius)||(y>870+radius&&y<1060-radius)))return true;}
  else {
   const strips=[[1160,1240,60,2300,[[660,840],[1660,1840]]],[1120,1690,1450,2070,[[1710,1850]]],[1250,1350,120,2400,[[860,1100],[1770,1980]]],[1400,1510,200,2450,[[630,870],[2070,2250]]],[1300,1410,300,2810,[[850,1150],[2260,2510]]]];
   const [a,b,c,e,gaps]=strips[i];if(x>a-radius&&x<b+radius&&y>c-radius&&y<e+radius&&!gaps.some(([l,h])=>y>l+radius&&y<h-radius))return true;
  }
  const z=this.s.zones[zone];return z?.props.some(p=>Math.hypot(x-p.x,y-p.y)<p.r+radius)||false;
 }
 safe(x,y,zone=this.s.zone){if(!this.blocked(x,y,zone))return {x,y};for(let r=30;r<450;r+=30)for(let i=0;i<24;i++){const a=i*Math.PI/12,p={x:x+Math.cos(a)*r,y:y+Math.sin(a)*r};if(!this.blocked(p.x,p.y,zone))return p;}throw Error('No safe arrival');}
 line(a,b){const n=Math.ceil(dist(a,b)/20);for(let i=1;i<n;i++)if(this.blocked(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n,this.s.zone,0))return false;return true;}
 route(a,b){
  const target=this.safe(b.x,b.y),step=50,size=this.isDungeon()?1500:this.definition().size,n=Math.ceil(size/step),key=p=>Math.floor(p.y/step)*n+Math.floor(p.x/step),start=key(a),end=key(target),queue=[start],seen=new Set([start]),parents=new Map();
  for(let at=0;at<queue.length&&at<n*n;at++){const id=queue[at];if(id===end){const path=[target];for(let j=id;j!==start;j=parents.get(j))path.push({x:(j%n)*step+25,y:Math.floor(j/n)*step+25});return path.reverse();}const x=id%n,y=Math.floor(id/n);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,j=yy*n+xx;if(xx<0||yy<0||xx>=n||yy>=n||seen.has(j)||this.blocked(xx*step+25,yy*step+25))continue;seen.add(j);parents.set(j,id);queue.push(j);}}
  return [];
 }
 move(entity,target,speed,dt,stop=0){const d=dist(entity,target);if(d<=stop)return true;const step=Math.min(d-stop,speed*dt),nx=entity.x+(target.x-entity.x)/d*step,ny=entity.y+(target.y-entity.y)/d*step;
  if(!this.blocked(nx,ny)){entity.x=nx;entity.y=ny;return true;}let moved=false;if(!this.blocked(nx,entity.y)){entity.x=nx;moved=true;}if(!this.blocked(entity.x,ny)){entity.y=ny;moved=true;}return moved;
 }
 follow(entity,target,speed,dt,stop=45){if(dist(entity,target)<=stop)return true;entity.routeAge=(entity.routeAge||0)-dt;if(!entity.path?.length||entity.routeAge<=0){entity.path=this.route(entity,target);entity.routeAge=1.3;}if(!entity.path.length)return false;this.move(entity,entity.path[0],speed,dt);if(dist(entity,entity.path[0])<22)entity.path.shift();return true;}
 zone(){
  if(this.s.zones[this.s.zone])return this.s.zones[this.s.zone];const i=this.regionIndex(),r=D.regions[i],dungeon=this.isDungeon(),id=this.s.zone;
  const z={id,enemies:[],props:[],npcs:[],buildings:[],nodes:[],packTimers:{},clock:0};this.s.zones[id]=z;
  const region=r.id,bosses=D.bosses.filter(b=>b.region===region),field=bosses.find(b=>b.kind==='field'),boss=dungeon?this.boss(id):field;
  if(dungeon){z.npcs.push({id:'exit',name:'Return to '+r.name,kind:'exit',x:160,y:240,icon:'🚪'},{id:'cage-'+boss.id,name:boss.captive,kind:'cage',family:boss.id,x:1200,y:1270,icon:'🔒'});
   if(id==='citadel')z.npcs.push({id:'fountain',name:'Preparation fountain',kind:'fountain',x:430,y:370,icon:'⛲'});
  }else{
   const [x,y]=D.towns[i],minor=D.minors[i];z.npcs.push({id:'supplier',name:r.town+' Supplies',kind:'supplier',x:x+85,y:y-40,icon:'🛒'},{id:'recruiter',name:r.town+' Captain',kind:'recruiter',x:x-80,y:y+60,icon:'👥'},{id:'board',name:r.town+' Quest board',kind:'quests',x:x+70,y:y+95,icon:'📜'},{id:'rest',name:r.town+' Refuge',kind:'rest',x,y,icon:'🏠'}, {id:'minor',name:r.minor,kind:'rest',x:minor[0],y:minor[1],icon:'🏡'});
   const [px,py]=D.ports[i];if(i<4)z.npcs.push({id:'outbound',name:r.transport+' to '+D.regions[i+1].name,kind:'transport',direction:1,x:px,y:py,icon:['🐎','⛵','🐫','🐉'][i]});
   if(i>0)z.npcs.push({id:'return',name:'Return to '+D.regions[i-1].name,kind:'transport',direction:-1,x:x+120,y:y+150,icon:['','🐎','⛵','🐫','🐉'][i]});
   const db=bosses.find(b=>b.kind==='dungeon'),[ex,ey]=D.entrances[i];z.npcs.push({id:'entrance',name:db.place,kind:'dungeon',family:db.id,x:ex,y:ey,icon:'🏛️'});
   const [fx,fy]=D.fields[i];z.npcs.push({id:'cage-'+field.id,name:field.captive,kind:'cage',family:field.id,x:fx+90,y:fy+80,icon:'🔒'});
   for(let j=0;j<3;j++){const p=this.safe(minor[0]+150+j*70,minor[1]+160+j*90);z.npcs.push({id:'bundle-'+j,name:'Quest supplies '+(j+1),kind:'bundle',index:j,...p,icon:'📦'});}
   const landmarks=[...D.entrances[i],...D.ports[i]];for(let j=0;j<3;j++){const p=this.safe(j===0?minor[0]+150:j===1?fx-150:ex-180,j===0?minor[1]+40:j===1?fy+180:ey+100);z.npcs.push({id:'landmark-'+j,name:['Regional monument','Wildland lookout','Ancient ruins'][j],kind:'landmark',...p,icon:['🗿','🏕️','🏚️'][j]});}
   const gp=this.safe(x+250,y+160);z.nodes.push({id:'gather-'+region,...gp,amount:r.resource,icon:['🪵','🧺','⛏️','🪵','💎'][i]});
   for(let k=0;k<300;k++){const x=130+(k*317+47*i)%(r.size-260),y=130+(k*521+89*i)%(r.size-260);if(z.npcs.some(n=>dist(n,{x,y})<170)||dist({x,y},{x:fx,y:fy})<200||this.blocked(x,y,id,50))continue;
    // Forest clusters leave broad paths and clear approaches to authored landmarks.
    if(Math.abs(y-(450+(k%3)*620))>100)z.props.push({id:'prop-'+k,x,y,r:24,icon:i===4?'🪨':i===3?'🌳':k%4===0?'🪨':'🌲'});
   }
  }
  const count=dungeon?r.guards:r.enemy_count,species=D.species[i],group=dungeon?2:i<2?3:i<4?4:5;
  for(let j=0;j<count;j++){const pack=Math.floor(j/group),s=species[pack%species.length],size=dungeon?1500:r.size;
   const base=dungeon?{x:350+(pack*213)%850,y:390+(pack*327)%690}:{x:650+(pack*337+71*i)%(size-900),y:500+(pack*431+137*i)%(size-800)};
   let p=this.safe(base.x+(j%group)*44,base.y+(j%group%2)*50);if(!dungeon&&D.towns.some(([tx,ty],ti)=>ti===i&&dist(p,{x:tx,y:ty})<260))p=this.safe(base.x+350,base.y+250);
   const e=this.makeEnemy({species:s[0],name:s[1]+(dungeon?' guardian':''),icon:s[2],level:Math.max(1,i*3+(pack%2)+1),hp:65+i*105,damage:7+i*8,gold:Math.floor((r.gold_range[0]+r.gold_range[1])/2),xp:dungeon?r.guard_xp:r.enemy_xp},p);e.pack=id+'-pack-'+pack;e.guard=dungeon;z.enemies.push(e);
  }
  const point=dungeon?{x:1160,y:1110}:{x:D.fields[i][0],y:D.fields[i][1]};if(dungeon&&this.s.normal[boss.id])z.enemies=z.enemies.filter(e=>!e.guard);
  if(!this.s.normal[boss.id]||boss.kind==='field'&&!(boss.id==='darklord'&&this.s.true.darklord)&& !this.s.pending[boss.id])z.enemies.push(this.bossEnemy(boss,'normal',point));
  if(!dungeon){const origin={x:D.towns[i][0],y:D.towns[i][1]};z.roads=[D.minors[i],D.ports[i],D.entrances[i],D.fields[i]].map(([x,y])=>this.route(origin,{x,y}));z.props=z.props.filter(p=>!z.roads.some(path=>path.some(q=>dist(p,q)<55)));}
  this.refreshNPCs();if(this.peace)this.makeHabitat(z);return z;
 }
 makeEnemy(def,p){return {id:'enemy-'+this.s.nextId++,family:def.family||null,species:def.species||def.family,name:def.name,icon:def.icon||'👿',form:def.form||'normal',type:def.type||'mob',level:def.level,baseHp:def.hp,baseDamage:def.damage,hp:def.hp,maxHp:def.hp,damage:def.damage,gold:def.gold,xp:def.xp,x:p.x,y:p.y,home:{...p},cd:0,aggro:false,heroParticipated:false,noProgress:0,attackIndex:0,respawn:0,neutral:false,open:0,deathPaid:false};}
 bossEnemy(b,form,p){let hp=b.hp,damage=b.damage,gold=b.gold,xp=b.xp,level=b.level;if(form==='true'){hp*=1.8;damage*=1.25;gold*=2;xp*=2;level+=2;if(b.kind==='dungeon'&&this.s.phase!=='adventure'){const i=dungeonIds.indexOf(b.id);hp=13000+i*1000;damage=70+i*2;gold=[500,600,700,800,1000][i];xp=[1000,1250,1500,1750,2000][i];level=18;}}
  return this.makeEnemy({family:b.id,name:b.name+(form==='true'?' TRUE':''),icon:b.kind==='field'?b.id==='darklord'?'😈':'👹':'💀',form,type:'boss',level,hp,damage,gold,xp},p);
 }
 refreshNPCs(){for(const [id,z]of Object.entries(this.s.zones)){if(dungeonIds.includes(id))continue;const i=this.regionIndex(id),[x,y]=D.towns[i];for(const b of D.bosses.filter(b=>b.region===id)){const exists=z.npcs.some(n=>n.id==='service-'+b.id);if(this.s.rescued[b.id]&&!exists){const p=this.safe(x-125+(b.kind==='field'?0:70),y-105,id);z.npcs.push({id:'service-'+b.id,name:b.captive,kind:ceilings[b.id]?'teacher':b.id==='archive'?'alchemist':'smith',family:b.id,...p,icon:ceilings[b.id]?'🧙':'⚒️'});}}}}
 clearTonic(){if(this.hero.tonic){this.hero.maxHp-=this.hero.tonicBonus||0;this.hero.hp=Math.min(this.hero.hp,this.hero.maxHp);this.hero.tonic=false;this.hero.tonicBonus=0;}}
 rest(){this.clearTonic();this.hero.hp=this.hero.maxHp;this.hero.mp=this.hero.maxMp;this.hero.tonic=false;this.s.refuge=this.isDungeon()?this.definition().id:this.s.zone;this.say('Rested at the refuge. Companions recover through the captain.');this.event('rest');}
 spend(amount){if(!Number.isFinite(amount)||amount<0||this.hero.gold<amount){this.say('Not enough gold.');return false;}this.hero.gold-=amount;return true;}
 rescue(family){if(this.s.rescued[family])return false;if(!this.s.keys[family]&&!this.peace){this.say('Defeat '+this.boss(family).name+' to obtain the key.');return false;}this.s.rescued[family]=true;this.refreshNPCs();this.say(this.boss(family).captive+' is free and returning to town.');this.event('rescue',{family});this.checkQuests();return true;}
 learn(slot,family){const def=D.skills.find(s=>s[0]===slot),index=slot-1;if(!def||this.hero.skills[index]||def[4]!==family||!this.s.rescued[family]||this.hero.level<def[2]){this.say('Learning requires the correct rescued teacher and hero level.');return false;}if(!this.spend(def[3]))return false;this.hero.skills[index]=1;this.event('learning',{slot});return true;}
 upgrade(slot,family){const def=D.skills.find(s=>s[0]===slot),rank=this.hero.skills[slot-1],next=rank+1;if(!def||!rank||!this.s.rescued[family]||next>(ceilings[family]||0)||this.hero.level<Math.max(def[2],2*next-1)){this.say('The teacher, learned skill or hero level cannot support that rank.');return false;}if(!this.spend(def[5]*(next-1)))return false;this.hero.skills[slot-1]=next;this.event('upgrade',{slot,rank:next});return true;}
 reward(gold,xp,level){const delta=this.hero.level-level,m=delta<=2?1:delta===3?.7:delta===4?.4:delta===5?.15:0;return {gold:gold>0?delta>=6?1:Math.max(1,Math.floor(gold*m)):0,xp:Math.floor(xp*m)};}
 xp(amount){this.hero.xp+=amount;while(this.hero.xp>=120*this.hero.level){this.hero.xp-=120*this.hero.level;this.hero.level++;this.hero.maxHp+=25;this.hero.maxMp+=15;this.hero.hp=this.hero.maxHp;this.hero.mp=this.hero.maxMp;this.hero.talentPoints++;this.event('level',{level:this.hero.level});this.say('Level '+this.hero.level+'!');}}
 grant(gold,xp){this.hero.gold+=gold;this.s.statistics.goldEarned+=gold;this.xp(xp);}
 buyPotion(type,advanced=false){const costs={health:advanced?50:20,mana:advanced?40:15,tonic:70};if(!costs[type]||advanced&&!this.s.rescued.archive)return false;if(type==='tonic'){if(!this.s.rescued.archive||this.hero.tonic||!this.spend(70))return false;this.hero.tonic=true;this.hero.tonicBonus=Math.ceil(this.hero.maxHp*.1);this.hero.maxHp+=this.hero.tonicBonus;this.hero.hp+=this.hero.tonicBonus;return true;}if(!this.spend(costs[type]))return false;const key=(advanced?'greater_':'')+type;this.hero.potions[key]=(this.hero.potions[key]||0)+1;return true;}
 potion(type){if(this.hero.potionCd>0)return false;let key='greater_'+type;if(!this.hero.potions[key])key=type;const value=type==='health'?(key.startsWith('greater')?150:60):(key.startsWith('greater')?100:40),field=type==='health'?'hp':'mp',max=type==='health'?'maxHp':'maxMp';if(!this.hero.potions[key]||this.hero[field]>=this.hero[max])return false;this.hero.potions[key]--;this.hero[field]=Math.min(this.hero[max],this.hero[field]+value);this.hero.potionCd=10;this.s.statistics.suppliesUsed++;this.event('heal');return true;}
 gear(family,slot,reforge=false){const tier={crypt:1,mine:2,abyss:3,darklord:4}[family];if(!tier||!this.s.rescued[family])return false;const old=slot==='weapon'?this.hero.weapon:this.hero.armorTier,prices=slot==='weapon'?[0,100,450,1000,2000]:[0,80,300,700,1200],key=slot+':'+tier;if(reforge){if(old!==tier||this.hero.reforges[key]||!this.spend(Math.ceil(prices[tier]/2)))return false;this.hero.reforges[key]=true;}else{if(old>=tier||!this.spend(prices[tier]))return false;this.hero[slot==='weapon'?'weapon':'armorTier']=tier;}this.event('purchase');return true;}
 power(){return this.hero.power+[0,15,35,55,70][this.hero.weapon]+(this.hero.reforges['weapon:'+this.hero.weapon]?5:0)+this.hero.talents[0]*8;}
 armor(){return this.hero.armor+[0,5,12,20,28][this.hero.armorTier]+(this.hero.reforges['armor:'+this.hero.armorTier]?3:0);}
 talent(i){const max=i===3?3:5;if(!Number.isInteger(i)||i<0||i>3||!this.hero.talentPoints||this.hero.talents[i]>=max)return false;this.hero.talentPoints--;this.hero.talents[i]++;if(i===2){this.hero.maxHp+=30;this.hero.hp+=30;}return true;}
 recruit(type){const price={worker:35,soldier:70,archer:100}[type];if(!price||this.s.party.filter(u=>u.hp>0).length+this.zone().buildings.filter(b=>b.queue>0).length>=6||!this.spend(price))return false;const p=this.safe(this.hero.x+50,this.hero.y+50);this.s.party.push(this.unit(type,p.x,p.y));return true;}
 recover(){const dead=this.s.party.find(u=>u.hp<=0);if(!dead||this.s.party.filter(u=>u.hp>0).length>=6||!this.spend(40))return false;Object.assign(dead,this.unit(dead.type,this.hero.x+40,this.hero.y));return true;}
 build(){if(this.isDungeon()||!this.s.party.some(u=>u.hp>0&&u.type==='worker')||!this.spend(120))return false;const p=this.safe(this.hero.x+130,this.hero.y);this.zone().buildings.push({id:'barracks-'+this.s.nextId++,...p,progress:0,queue:0,icon:'🏗️'});return true;}
 train(id){const b=this.zone().buildings.find(b=>b.id===id);if(!b||b.progress<4||b.queue>0||this.s.party.filter(u=>u.hp>0).length>=6||!this.spend(60))return false;b.queue=4;return true;}
 gather(nodeId){const n=this.zone().nodes.find(n=>n.id===nodeId),worker=this.s.party.find(u=>u.hp>0&&u.type==='worker');if(!n||!worker)return false;worker.order={type:'gather',id:nodeId};return true;}
 enter(zone){if(!D.regions.some(r=>r.id===zone)&&!dungeonIds.includes(zone))return false;const i=this.regionIndex(zone),p=dungeonIds.includes(zone)?{x:160,y:240}:{x:D.towns[i][0],y:D.towns[i][1]};this.s.zone=zone;this.zone();const q=this.safe(p.x,p.y);Object.assign(this.hero,q);for(const u of this.s.party){Object.assign(u,this.safe(q.x+40,q.y+30));u.order=null;u.path=[];}this.hero.order=null;this.s.projectiles=[];this.s.hazards=[];for(const z of Object.values(this.s.zones))for(const e of z.enemies){e.aggro=false;e.telegraph=null;e.frozen=false;if(e.hp>0){Object.assign(e,e.home);e.hp=e.baseHp;e.maxHp=e.baseHp;e.damage=e.baseDamage;}}this.activatePending();this.discover('arrival');return true;}
 travel(direction){if(this.isDungeon()||![1,-1].includes(direction))return false;const i=this.regionIndex(),j=i+direction;if(j<0||j>4)return false;const edge=direction===1?D.regions[i].id:D.regions[j].id;if(direction<0&&!this.s.tickets[edge])return false;if(direction===1){if(this.s.recovery[edge])delete this.s.recovery[edge];else if(!this.spend(D.regions[i].fare))return false;this.s.tickets[edge]=true;this.s.lastEdge=edge;}this.event('travel',{from:this.s.zone,to:D.regions[j].id});return this.enter(D.regions[j].id);}
 discover(key){this.s.discovered[this.definition().id+':'+key]=true;this.checkQuests();}
 interact(npc){if(!npc||dist(npc,this.hero)>115)return false;switch(npc.kind){case 'cage':return this.rescue(npc.family);case 'rest':this.rest();return true;case 'bundle':this.s.discovered[this.definition().id+':bundle-'+npc.index]=true;this.checkQuests();return true;case 'landmark':this.discover(npc.id);return true;case 'exit':return this.enter(this.definition().id);case 'dungeon':return this.enter(npc.family);case 'fountain':if(this.s.fountains[this.s.zone]||this.zone().enemies.some(e=>e.guard&&e.hp>0))return false;this.s.fountains[this.s.zone]=true;this.hero.hp=Math.min(this.hero.maxHp,this.hero.hp+.6*this.hero.maxHp);this.hero.mp=Math.min(this.hero.maxMp,this.hero.mp+.6*this.hero.maxMp);this.s.party.forEach(u=>{if(u.hp>0)u.hp=Math.min(u.maxHp,u.hp+.6*u.maxHp);});return true;default:return false;}}
 questId(i){return 'quest-'+i;}
 questDefs(){return D.quests.map((q,i)=>({id:this.questId(i),region:q[0],name:q[1],objective:q[2],gold:q[3],xp:q[4],index:i%6}));}
 accept(id){const q=this.questDefs().find(q=>q.id===id);if(!q)return false;if(!this.s.quests[id])this.s.quests[id]={active:true,count:0,done:false,paid:false};this.checkQuests();return true;}
 checkQuests(){for(const q of this.questDefs()){const p=this.s.quests[q.id];if(!p||p.done)continue;const b=D.bosses.filter(b=>b.region===q.region),field=b.find(b=>b.kind==='field'),dungeon=b.find(b=>b.kind==='dungeon'),s=this.s.discovered;
  if(/release|Release/.test(q.objective))p.done=!!this.s.rescued[/Mira|Sela|Orin|Lyss|Thornfang/.test(q.objective)?field.id:/Borin|Neri|Dara|Eren|Tovan|Vera/.test(q.objective)?q.objective.includes('Vera')?field.id:dungeon.id:field.id];
  else if(/Defeat/.test(q.objective))p.done=p.count>=Number(q.objective.match(/\d+/)?.[0]||5);
  else if(/Recover|Deliver/.test(q.objective))p.done=[0,1,2].every(j=>s[q.region+':bundle-'+j]);
  else if(/Escort/.test(q.objective))p.done=!!s[q.region+':escort'];
  else if(/wraith/.test(q.objective))p.done=p.count>=2&&s[q.region+':night'];
  else if(/survey|Visit|crossing/.test(q.objective))p.done=[0,1,2].every(j=>s[q.region+':landmark-'+j]);
  else p.done=!!s[q.region+':port'];
 }}
 claim(id){const q=this.questDefs().find(q=>q.id===id),p=this.s.quests[id];if(!q||!p?.done||p.paid)return false;p.paid=true;this.grant(q.gold,q.xp);this.event('quest',{id});return true;}
 engage(e){if(e.aggro||e.neutral)return;e.aggro=true;e.frozen=true;const m=this.multipliers(),ratio=e.hp/e.maxHp;e.maxHp=e.baseHp*m.hp;e.hp=e.maxHp*ratio;e.damage=e.baseDamage*m.damage;e.fightStart=this.s.time;e.heroParticipated=false;e.noProgress=0;for(const ally of this.zone().enemies)if(ally.pack&&ally.pack===e.pack&&ally.hp>0&&!ally.aggro)this.engage(ally);}
 damage(e,amount,source='hero'){if(!e||e.hp<=0||e.neutral||this.peace||e.returning||!Number.isFinite(amount)||amount<=0)return false;const origin=source==='hero'?this.hero:this.s.party.find(u=>u.id===source)||this.hero;if(!this.line(origin,e)||dist(origin,e.home)>(e.type==='boss'?this.isDungeon()?1800:700:500))return false;this.engage(e);if(source==='hero')e.heroParticipated=true;if(e.family==='citadel'&&e.open<=0)amount*=.65;e.hp=Math.max(0,e.hp-amount);this.effects.push({type:'hit',x:e.x,y:e.y,amount});if(e.hp===0)this.kill(e);return true;}
 hitParty(u,amount){if(this.peace||u.hp<=0||u===this.hero&&this.hero.immune>0)return false;const armor=u===this.hero?this.armor():5+this.hero.level*.5;u.hp=Math.max(0,u.hp-Math.max(3,amount-armor*.35));this.event('hurt');if(u===this.hero&&u.hp===0)this.die();return true;}
 die(){this.clearTonic();this.s.statistics.deaths++;this.s.streak={key:null,count:0};this.s.projectiles=[];this.s.hazards=[];this.event('death');
  if(this.s.challenge.succession){const challenge=this.s.challenge;if(!challenge.fallen.includes(this.hero.class))challenge.fallen.push(this.hero.class);this.hero.hp=0;challenge.pending=true;const remaining=Object.keys(classes).filter(id=>!challenge.fallen.includes(id));if(!remaining.length){challenge.pending=false;challenge.gameOver=true;this.say('Your last successor has fallen. Game over.');this.event('gameOver');}else if(remaining.length===1)this.successor(remaining[0]);else this.say('Choose a successor from the remaining classes. Gold and world progress are preserved.');return;}
  this.hero.hp=this.hero.maxHp;this.hero.mp=this.hero.maxMp;this.hero.tonic=false;this.hero.immune=0;this.hero.slow=0;if(this.s.lastEdge)this.s.recovery[this.s.lastEdge]=true;this.enter(this.s.refuge);this.say('Returned to your refuge. Learning and rescue progress are safe.');}
 successor(heroClass){if(!this.s.challenge.succession||!this.s.challenge.pending||this.s.challenge.fallen.includes(heroClass)||!classes[heroClass])return false;const old=this.hero,fresh=new Campaign(this.s.mode,heroClass,this.random,{succession:true}).hero;for(const key of ['gold','weapon','armorTier','reforges','potions'])fresh[key]=clone(old[key]);this.s.hero=fresh;this.s.challenge.pending=false;this.s.refuge='vale';this.s.loot=[];this.s.party.forEach(u=>{u.cd=1;u.order=null;});this.enter('vale');this.event('successor',{class:heroClass});this.say('Your '+heroClass+' successor begins at level 1. The world remembers your progress.');return true;}
 cast(slot,targetId){const i=slot-1,rank=this.hero.skills[i];if(!rank||this.hero.cd[i]>0||this.peace){if(!rank)this.say('This skill must be learned from a rescued instructor.');return false;}const scale=1+.15*(rank-1),range=this.hero.class==='paladin'&&slot<3?120:slot===1?this.hero.class==='mage'?400:450:480,targets=this.zone().enemies.filter(e=>e.hp>0&&!e.neutral&&dist(e,this.hero)<=range&&this.line(this.hero,e)),target=targets.find(e=>e.id===targetId)||targets.sort((a,b)=>dist(a,this.hero)-dist(b,this.hero))[0];
  if([1,2,6,7,8].includes(slot)&&!target)return false;if(slot===3&&(this.hero.class==='mage'?this.hero.mp>=this.hero.maxMp:this.hero.hp>=this.hero.maxHp))return false;
  const cost=slot===1||slot===3&&this.hero.class==='mage'?0:costs[slot];if(this.hero.mp<cost)return false;this.hero.mp-=cost;this.hero.cd[i]=cooldowns[slot];
  const power=this.power();if(slot===3){if(this.hero.class==='mage')this.hero.mp=Math.min(this.hero.maxMp,this.hero.mp+35*scale);else this.hero.hp=Math.min(this.hero.maxHp,this.hero.hp+(45+power*.5)*scale);this.event('heal');}
  else if(slot===4){if(this.hero.class==='ranger')this.hero.haste=Math.min(6,4+.25*(rank-1));else this.hero.immune=Math.min(4,(this.hero.class==='paladin'?2.5:2)+.15*(rank-1));this.event('spell');}
  else if(slot===5||slot===8){for(const e of this.zone().enemies.filter(e=>e.hp>0&&dist(e,this.hero)<(slot===8?500:350)))this.damage(e,(slot===8?power*4+60:power*2.3)*scale);this.event('spell');}
  else{const dmg=(slot===1?power+12:slot===2?power*2.2:slot===6?power*1.8+20:power*6)*scale;if(this.hero.class==='paladin'){this.damage(target,dmg);this.event('swing');}else{this.engage(target);this.s.projectiles.push({id:'projectile-'+this.s.nextId++,x:this.hero.x,y:this.hero.y,target:target.id,damage:dmg,source:'hero',speed:550});this.event('spell');}}
  return true;
 }
 victory(family,form){const key=family+':'+form;if(this.s.victories[key])return false;this.s.victories[key]=true;if(form==='normal')this.s.normal[family]=true;else this.s.true[family]=true;if(form==='true'&&this.s.phase==='awakening'&&dungeonIds.includes(family))this.s.late[family]=true;return true;}
 kill(e){if(e.deathPaid)return;e.deathPaid=true;e.aggro=false;e.telegraph=null;if(e.summon){return;}this.s.statistics.kills++;const r=this.reward(e.gold,e.xp,e.level);this.s.loot.push({id:'loot-'+this.s.nextId++,zone:this.s.zone,x:e.x,y:e.y,gold:r.gold});this.xp(r.xp);
  for(const q of this.questDefs().filter(q=>q.region===this.definition().id)){const p=this.s.quests[q.id];if(p?.active&&!p.done&&(/Defeat/.test(q.objective)&&e.type==='mob'||/wraith/.test(q.objective)&&e.species==='wraith'))p.count++;}this.checkQuests();
  if(e.type==='boss'){const b=this.boss(e.family);this.victory(e.family,e.form);this.s.statistics.bossSeconds[e.family+':'+e.form]=Math.round(this.s.time-(e.fightStart||this.s.time));if(e.form==='normal')this.s.keys[e.family]=true;if(b.kind==='dungeon'){if(e.form==='normal'&&!(e.family in this.s.earlyRoll)){this.s.earlyRoll[e.family]=this.random()<1/3;if(this.s.earlyRoll[e.family]||this.s.phase==='awakening')this.s.pending[e.family]={kind:'dungeon',count:1};}if(e.form==='true')delete this.s.pending[e.family];}
   else if(e.family==='darklord'&&e.form==='true'){delete this.s.pending.darklord;this.awaken();}
   this.zone().enemies.forEach(a=>{if(a.summon&&a.owner===e.id)a.hp=0;});this.say(e.name+' defeated.');this.event('bossDefeat',{family:e.family,form:e.form});
  }
  if(e.heroParticipated)this.streak(e);if(!this.peace&&e.type==='boss'&&this.boss(e.family).kind==='field'&&!(e.family==='darklord'&&this.s.true.darklord)&&e.form==='normal')e.respawn=120;
  else if(!this.peace&&e.type==='boss'&&this.boss(e.family).kind==='field'&&e.family!=='darklord'&&e.form==='true')e.respawn=120;
  this.checkClear();this.checkEnding();
 }
 streak(e){if(this.peace||e.summon)return;if(e.form!=='normal'){this.s.streak={key:null,count:0};return;}const key=e.family||e.species;if(this.s.streak.key!==key)this.s.streak={key,count:1};else this.s.streak.count++;if(this.s.streak.count<2)return;this.s.streak={key:null,count:0};if(this.s.pending[key])return;if(e.type==='boss'&&this.boss(e.family).kind!=='field')return;if(e.family==='darklord'&&this.s.true.darklord)return;this.s.pending[key]={kind:e.type==='boss'?'field':'mob',count:e.type==='boss'?1:this.random()<.5?2:1,zone:this.s.zone,base:clone(e),delay:2};this.event('eliteWarning',{family:key});}
 activatePending(){if(this.peace)return;const p=this.s.pending[this.s.zone];if(this.isDungeon()&&p&&!this.s.true[this.s.zone]&&!this.zone().enemies.some(e=>e.form==='true'&&e.hp>0)){const b=this.boss(this.s.zone),e=this.bossEnemy(b,'true',{x:1160,y:1110});this.zone().enemies.push(e);p.active=true;this.s.origins[b.id]=this.s.phase==='adventure'?'early':'awakening';this.say(b.name+' TRUE waits in the chamber.');}}
 awaken(){if(this.s.phase==='peace')return;this.s.phase='awakening';for(const z of Object.values(this.s.zones))for(const e of z.enemies)if(e.family==='darklord')e.hp=0;for(const id of dungeonIds){if(this.s.true[id])continue;if(this.s.normal[id])this.s.pending[id]={kind:'dungeon',count:1};const z=this.s.zones[id];if(z)for(const e of z.enemies)if(e.form==='true'&&e.hp>0){const upgraded=this.bossEnemy(this.boss(id),'true',e.home);Object.assign(e,upgraded);}}
  this.say('The TRUE Dark Lord is gone forever. Clear the remaining TRUE dungeon guardians.');this.event('awakening');this.checkEnding();}
 checkClear(){if(!this.isDungeon())return;const z=this.zone(),id=this.s.zone;if(!this.s.paid['clear:'+id]&&this.s.normal[id]&&!z.enemies.some(e=>e.guard&&e.hp>0)){this.s.paid['clear:'+id]=true;const i=dungeonIds.indexOf(id);this.grant([100,220,400,650,900][i],0);this.say('Dungeon first clear reward earned.');}}
 checkEnding(){if(this.s.true.darklord&&dungeonIds.every(id=>this.s.true[id])){if(this.peace)return;this.s.phase='peace';this.s.endingAck=false;this.s.streak={key:null,count:0};this.s.pending={};this.s.projectiles=[];this.s.hazards=[];this.hero.order=null;this.s.party.forEach(u=>u.order=null);if(this.s.mode==='nightmare')this.s.clock=480;for(const z of Object.values(this.s.zones))this.makeHabitat(z);for(const q of this.questDefs()){const p=this.s.quests[q.id];if(p&&!p.done&&/Defeat|wraith|Escort/.test(q.objective)){p.closedByPeace=true;p.active=false;}}
   this.say('The war is over for people and creatures alike. Nightmare Mode is unlocked.');this.event('peace');}}
 makeHabitat(z){if(z.habitat)return;z.habitat=true;z.enemies=[];const i=this.regionIndex(z.id),dungeon=dungeonIds.includes(z.id),count=dungeon?4:[8,10,12,14,16][i];for(let j=0;j<count;j++){const sp=D.species[i][Math.floor(j/2)%2],size=dungeon?1500:D.regions[i].size,p=this.safe(350+(Math.floor(j/2)*337)%(size-600)+(j%2)*55,400+(Math.floor(j/2)*277)%(size-650),z.id);const e=this.makeEnemy({species:sp[0],name:sp[1]+' resident',icon:sp[2],level:1,hp:1,damage:0,gold:0,xp:0},p);e.neutral=true;z.enemies.push(e);}
  if(!dungeon){const b=D.bosses.find(b=>b.region===z.id&&b.kind==='field');if(b.id!=='darklord'){const p={x:D.fields[i][0],y:D.fields[i][1]},e=this.bossEnemy(b,'normal',p);e.neutral=true;z.enemies.push(e);}}}
 tick(dt,input={x:0,y:0}){if(!Number.isFinite(dt)||dt<=0||this.s.challenge?.pending||this.s.challenge?.gameOver)return;dt=Math.min(dt,.1);this.s.time+=dt;if(this.peace||this.s.mode==='normal')this.s.clock=(this.s.clock+dt)%720;const h=this.hero,z=this.zone();z.clock+=dt;h.cd=h.cd.map(c=>Math.max(0,c-dt));for(const f of ['immune','haste','potionCd','slow'])h[f]=Math.max(0,h[f]-dt);h.mp=Math.min(h.maxMp,h.mp+(3+h.talents[1]*2)*dt);
  if(input.x||input.y){h.order=null;const n=Math.hypot(input.x,input.y),speed=(h.speed+h.talents[3]*40)*(h.haste>0?1.25:1)*(h.slow>0?.65:1)*clamp(input.speedFactor||1,1,1.35);this.move(h,{x:h.x+input.x/n*speed,y:h.y+input.y/n*speed},speed,dt);}
  else if(h.order){const target=h.order.type==='attack'?z.enemies.find(e=>e.id===h.order.id):h.order;if(target&&!target.neutral){if(dist(h,target)>(h.order.type==='attack'?h.class==='paladin'?105:350:25))this.follow(h,target,h.speed*(h.slow>0?.65:1),dt,20);else if(h.order.type==='attack')this.cast(1,target.id);else h.order=null;}else h.order=null;}
  if(!this.isDungeon()){const [tx,ty]=D.towns[this.regionIndex()];if(dist(h,{x:tx,y:ty})<170){this.s.refuge=this.s.zone;h.hp=Math.min(h.maxHp,h.hp+8*dt);}for(const n of z.npcs.filter(n=>n.kind==='landmark'))if(dist(h,n)<120)this.discover(n.id);const [px,py]=D.ports[this.regionIndex()];if(dist(h,{x:px,y:py})<140)this.discover('port');const minor=D.minors[this.regionIndex()];if(dist(h,{x:minor[0],y:minor[1]})<180)this.discover('survey');}
  this.updateParty(dt);this.updateEnemies(dt);if(h!==this.hero||z!==this.zone()||this.s.challenge.pending||this.s.challenge.gameOver)return;this.updateProjectiles(dt);if(h!==this.hero||z!==this.zone()||this.s.challenge.pending||this.s.challenge.gameOver)return;this.updateElites(dt);this.updatePacks(dt);this.updateTraps(dt);this.updateNight();this.updateEscort(dt);this.checkClear();
  for(const l of [...this.s.loot])if(l.zone===this.s.zone&&dist(l,h)<65){this.grant(l.gold,0);this.s.loot.splice(this.s.loot.indexOf(l),1);this.event('gold');}
 }
 updateParty(dt){const z=this.zone();for(const u of this.s.party.filter(u=>u.hp>0)){u.cd=Math.max(0,u.cd-dt);if(u.order?.type==='gather'){const n=z.nodes.find(n=>n.id===u.order.id);if(n&&n.amount>0){if(dist(u,n)>60)this.follow(u,n,230,dt);else{const amount=Math.min(n.amount,12*dt);n.amount=Math.max(0,n.amount-amount);u.carry+=amount;this.s.gathered[this.definition().id]=(this.s.gathered[this.definition().id]||0)+amount;}if(u.carry>=35||n.amount<=0){u.order={type:'deposit'};}}else u.order={type:'deposit'};continue;}
   if(u.order?.type==='deposit'){const [x,y]=D.towns[this.regionIndex()];if(dist(u,{x,y})>130)this.follow(u,{x,y},230,dt);else{const payout=Math.floor(u.carry+1e-7);this.grant(payout,0);u.carry=Math.max(0,u.carry-payout);u.order=null;}continue;}
   if(u.order?.type==='move'){if(dist(u,u.order)>25)this.follow(u,u.order,250,dt,20);else u.order={type:'wait'};continue;}if(u.order?.type==='wait')continue;
   if(this.peace||this.s.holdFire){this.follow(u,this.hero,250,dt,70);continue;}let e=u.order?.type==='attack'?z.enemies.find(e=>e.id===u.order.id&&e.hp>0&&!e.neutral):z.enemies.filter(e=>e.hp>0&&e.aggro&&!e.neutral&&dist(u,e)<480).sort((a,b)=>dist(a,u)-dist(b,u))[0];if(!e){this.follow(u,this.hero,250,dt,80);continue;}const range=u.type==='archer'?280:65;if(dist(u,e)>range)this.follow(u,e,250,dt,range-10);else if(u.cd<=0){u.cd=u.type==='archer'?1.3:1;this.damage(e,u.damage+this.hero.level*2,u.id);}}
  for(const b of z.buildings){if(b.progress<4){const worker=this.s.party.find(u=>u.hp>0&&u.type==='worker');if(worker){if(dist(worker,b)>85)this.follow(worker,b,230,dt,70);else b.progress=Math.min(4,b.progress+dt);}}if(b.queue>0){b.queue=Math.max(0,b.queue-dt);if(b.queue===0&&this.s.party.filter(u=>u.hp>0).length<6){const p=this.safe(b.x+50,b.y+50);this.s.party.push(this.unit('soldier',p.x,p.y));}}}
 }
 updateEnemies(dt){const z=this.zone(),deaths=this.s.statistics.deaths;for(const e of [...z.enemies]){if(e.hp<=0){if(e.respawn>0&&!this.peace){e.respawn-=dt;if(e.respawn<=0&&!this.s.pending[e.family]&&!(e.family==='darklord'&&this.s.true.darklord)){Object.assign(e,this.bossEnemy(this.boss(e.family),'normal',e.home));this.say(this.boss(e.family).name+' has returned.');}}continue;}if(e.neutral){const t=this.s.time*.1+Number(e.id.split('-')[1]);this.move(e,{x:e.home.x+Math.cos(t)*35,y:e.home.y+Math.sin(t)*35},12,dt);continue;}e.cd=Math.max(0,e.cd-dt);e.open=Math.max(0,(e.open||0)-dt);
   if(this.s.statistics.deaths!==deaths||this.s.challenge.pending||this.s.challenge.gameOver||z!==this.zone())return;const target=[this.hero,...this.s.party.filter(u=>u.hp>0),...(z.escort?.hp>0?[z.escort]:[])].sort((a,b)=>dist(e,a)-dist(e,b))[0];if(!e.aggro&&dist(e,target)<220&&(!this.isDungeon()&&dist(target,{x:D.towns[this.regionIndex()][0],y:D.towns[this.regionIndex()][1]})<170?false:true))this.engage(e);if(!e.aggro)continue;
   const territory=e.type==='boss'?this.isDungeon()?1800:700:500;if(dist(target,e.home)>territory||!this.isDungeon()&&dist(target,{x:D.towns[this.regionIndex()][0],y:D.towns[this.regionIndex()][1]})<160){this.disengage(e,dt);continue;}
   if(e.returning){this.disengage(e,dt);continue;}if(e.telegraph){e.telegraph.timer-=dt;e.noProgress=0;if(e.telegraph.timer<=0){this.resolveAttack(e);e.telegraph=null;e.cd=1.8;e.open=e.family==='citadel'||e.family==='mine'?3:0;}continue;}
   const ranged=e.species==='archer'||e.species==='crownguard'||e.summon,range=ranged?280:65,d=dist(e,target),before=d;let opportunity=false;
   if(e.type==='boss'&&e.cd<=0&&d<460){this.startAttack(e,target);opportunity=true;}
   else if(d<=range&&e.cd<=0&&this.line(e,target)){e.cd=e.type==='boss'?1.8:1.4;this.hitParty(target,e.damage);opportunity=true;}
   else if(d>range)this.follow(e,target,e.type==='boss'?145:175,dt,range-8);
   const progress=before-dist(e,target)>Math.max(.1,dt*10);if(opportunity||progress)e.noProgress=0;else e.noProgress+=dt;if(e.noProgress>=12)this.disengage(e,dt);
  }}
 disengage(e,dt){if(!e.returning){e.returning=1;this.say(e.name+' disengages.');this.event('reset');}e.returning-=dt;if(e.returning<=0){Object.assign(e,e.home);e.aggro=false;e.telegraph=null;e.hp=e.baseHp;e.maxHp=e.baseHp;e.damage=e.baseDamage;e.returning=0;e.heroParticipated=false;e.noProgress=0;e.frozen=false;}}
 startAttack(e,target){const b=this.boss(e.family),index=e.attackIndex++%4,words=b.attacks[index],warning=Number(words.match(/(\d+(?:\.\d+)?) second/)?.[1]||1.5);
  let kind=/call|howl|command|cry/i.test(words)?'summon':/volley/i.test(words)?'volley':/lane|line|charge|rush|jets|pursuit/i.test(words)?'line':/ring|shockwave/i.test(words)?'ring':/frontal|cone|cleave|bite|snap|blow/i.test(words)?'cone':'circle';
  if(e.family==='darklord'&&index===3&&e.hp>e.maxHp*.5)kind='cone';
  const count=/three|3 staggered/i.test(words)?3:/two marked|two lanes|two parallel/i.test(words)?2:1,from={x:e.x,y:e.y},angle=Math.atan2(target.y-e.y,target.x-e.x);
  const center=kind==='cone'||kind==='ring'?from:{x:target.x,y:target.y};
  e.telegraph={index,name:words.split(':')[0],timer:warning,total:warning,kind,...center,fromX:e.x,fromY:e.y,angle,count,slow:/slow|Root line|Undertow|Bog spit/i.test(words),charge:/charge|rush|pursuit/i.test(words),radius:kind==='cone'?165:kind==='ring'?105:index===0?90:115};this.event('warning',{family:e.family});}
 attackPatches(a){return Array.from({length:a.count||1},(_,i)=>({...a,x:a.x+(i-(a.count-1)/2)*190,y:a.y+(i%2)*100,radius:a.count>1?75:a.radius}));}
 resolveAttack(e){const a=e.telegraph;if(!a)return;if(a.kind==='summon'){const alive=this.zone().enemies.filter(u=>u.summon&&u.owner===e.id&&u.hp>0).length;for(let i=alive;i<2;i++){const p=this.safe(e.x-75+i*150,e.y+85),s=this.makeEnemy({species:'summon',name:'Summoned guard',icon:'👻',level:e.level,hp:e.level>=18?700:40+e.level*15,damage:e.level>=18?30:5+e.level,gold:0,xp:0},p);s.summon=true;s.owner=e.id;this.zone().enemies.push(s);}return;}
  if(a.kind==='volley'){for(const delta of [-.22,0,.22])this.s.projectiles.push({id:'projectile-'+this.s.nextId++,x:e.x,y:e.y,dx:Math.cos(a.angle+delta),dy:Math.sin(a.angle+delta),speed:260,life:2.5,damage:e.damage,source:'enemy'});return;}
  if(a.kind==='ring'){this.s.hazards.push({...a,x:e.x,y:e.y,life:1.6,tick:0,damage:e.damage,age:0,hit:[]});return;}
  if(a.charge)this.move(e,a,Math.min(500,dist(e,a)),1);
  const party=[this.hero,...this.s.party.filter(u=>u.hp>0)],patches=this.attackPatches(a),hits=u=>a.kind==='line'?a.count===2?[ -85,85 ].some(o=>this.distanceToSegment(u,{x:a.fromX+Math.cos(a.angle+Math.PI/2)*o,y:a.fromY+Math.sin(a.angle+Math.PI/2)*o},{x:a.x+Math.cos(a.angle+Math.PI/2)*o,y:a.y+Math.sin(a.angle+Math.PI/2)*o})<35):this.distanceToSegment(u,{x:a.fromX,y:a.fromY},a)<45:a.kind==='cone'?dist(u,a)<a.radius&&Math.cos(Math.atan2(u.y-a.y,u.x-a.x)-a.angle)>.45:patches.some(p=>dist(u,p)<p.radius);
  for(const u of party)if(hits(u)){this.hitParty(u,e.damage*(a.index===2?1.4:1));if(a.slow)u.slow=3;if(party[0]!==this.hero||this.s.challenge.pending||this.s.challenge.gameOver)return;}
  if(/ground|puddle|spit|flame|pulse|Undertow/i.test(this.boss(e.family).attacks[a.index]))for(const p of patches)this.s.hazards.push({...p,kind:'circle',life:4,tick:1,damage:e.damage*.25});
  if(e.form==='true'&&a.index===1)this.s.hazards.push({...a,kind:'circle',x:a.x+150,y:a.y+50,life:1.5,tick:.7,damage:e.damage});
 }
 distanceToSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return dist(p,{x:a.x+t*dx,y:a.y+t*dy});}
 updateProjectiles(dt){const hero=this.hero;for(const p of [...this.s.projectiles]){if(p.source==='enemy'){p.life-=dt;const before={x:p.x,y:p.y};p.x+=p.dx*p.speed*dt;p.y+=p.dy*p.speed*dt;const victim=[this.hero,...this.s.party.filter(u=>u.hp>0)].find(u=>this.distanceToSegment(u,before,p)<22);if(victim){this.hitParty(victim,p.damage);p.life=0;}if(p.life<=0||!this.line(before,p)||this.peace)this.s.projectiles.splice(this.s.projectiles.indexOf(p),1);if(this.hero!==hero||this.s.challenge.pending||this.s.challenge.gameOver)return;continue;}
   const e=this.zone().enemies.find(e=>e.id===p.target&&e.hp>0&&!e.neutral);if(!e||this.peace){this.s.projectiles.splice(this.s.projectiles.indexOf(p),1);continue;}const before={x:p.x,y:p.y},d=dist(p,e),step=Math.min(p.speed*dt,d);p.x+=(e.x-p.x)/Math.max(1,d)*step;p.y+=(e.y-p.y)/Math.max(1,d)*step;if(!this.line(before,p)){this.s.projectiles.splice(this.s.projectiles.indexOf(p),1);continue;}if(d<step+15){this.damage(e,p.damage,p.source);this.s.projectiles.splice(this.s.projectiles.indexOf(p),1);}}
  for(const a of [...this.s.hazards]){a.life-=dt;a.tick-=dt;a.age=(a.age||0)+dt;if(a.kind==='ring'){a.radius=a.age*180;for(const u of [this.hero,...this.s.party.filter(u=>u.hp>0)]){const id=u===this.hero?'hero':u.id;if(!a.hit.includes(id)&&Math.abs(dist(u,a)-a.radius)<25){a.hit.push(id);this.hitParty(u,a.damage);}}}else if(a.tick<=0){a.tick=1;for(const u of [this.hero,...this.s.party.filter(u=>u.hp>0)])if(dist(u,a)<a.radius){this.hitParty(u,a.damage);if(a.slow)u.slow=3;}}if(a.life<=0||this.peace)this.s.hazards.splice(this.s.hazards.indexOf(a),1);if(hero!==this.hero||this.s.challenge.pending||this.s.challenge.gameOver)return;}}
 updateElites(dt){for(const [key,p]of Object.entries(this.s.pending)){if(p.kind==='dungeon'||p.zone!==this.s.zone||p.active)continue;p.delay-=dt;if(p.delay>0)continue;const points=[];for(let i=0;i<p.count;i++){let point=null;for(let n=0;n<24;n++){const a=n*Math.PI/12,x=p.base.home.x+Math.cos(a)*(210+i*110),y=p.base.home.y+Math.sin(a)*(210+i*110);if(!this.blocked(x,y)&&dist({x,y},this.hero)>200&&!points.some(q=>dist(q,{x,y})<100)){point={x,y};break;}}if(!point)break;points.push(point);}if(points.length!==p.count)continue;
   for(const point of points){const e=p.kind==='field'?this.bossEnemy(this.boss(key),'true',point):this.makeEnemy({species:key,name:p.base.name+' Ringleader',icon:p.base.icon,form:'ringleader',hp:p.base.baseHp*1.6,damage:p.base.baseDamage*1.25,level:p.base.level+2,gold:p.base.gold*1.5,xp:p.base.xp*1.5},point);e.eliteKey=key;this.zone().enemies.push(e);}p.active=true;this.say(p.kind==='field'?'A TRUE boss has appeared.':'Ringleaders have appeared.');}
  for(const [key,p]of Object.entries(this.s.pending))if(p.active&&p.kind!=='dungeon'&&p.zone===this.s.zone&&!this.zone().enemies.some(e=>e.hp>0&&(e.eliteKey===key||p.kind==='field'&&e.family===key&&e.form==='true')))delete this.s.pending[key];}
 updatePacks(dt){if(this.peace)return;const z=this.zone();for(const pack of new Set(z.enemies.filter(e=>e.pack&&!e.guard).map(e=>e.pack))){const members=z.enemies.filter(e=>e.pack===pack);if(members.some(e=>e.hp>0)||members.some(e=>dist(e.home,this.hero)<350)){delete z.packTimers[pack];continue;}z.packTimers[pack]=(z.packTimers[pack]||0)+dt;if(z.packTimers[pack]>=60){for(const e of members){Object.assign(e,e.home);e.hp=e.baseHp;e.maxHp=e.baseHp;e.deathPaid=false;e.heroParticipated=false;e.aggro=false;}delete z.packTimers[pack];}}}
 traps(){return this.isDungeon()&&!this.peace?[{x:530,y:430},{x:900,y:710},{x:1010,y:940}].map((p,i)=>({...p,radius:50,phase:(this.zone().clock+i*1.7)%8,cycle:Math.floor((this.zone().clock+i*1.7)/8),index:i})):[];}
 updateTraps(dt){for(const t of this.traps())if(t.phase>=1.5&&t.phase<2)for(const u of [this.hero,...this.s.party.filter(u=>u.hp>0)]){u.trapHits=u.trapHits||{};const key=this.s.zone+':'+t.index;if(u.trapHits[key]!==t.cycle&&dist(u,t)<50){u.trapHits[key]=t.cycle;this.hitParty(u,u.maxHp*(this.s.zone==='citadel'?.12:.08));}}}
 updateNight(){if(this.peace)return;const i=this.regionIndex();if(this.isDungeon()||![1,3].includes(i))return;const z=this.zone();if(this.night()){this.discover('night');if(!z.enemies.some(e=>e.nightOnly&&e.hp>0)&&!z.nightSpawned){for(let j=0;j<4;j++){const p=this.safe(1700+j*65,900+j*80);const e=this.makeEnemy({species:i===1?'wraith':'stalker',name:i===1?'Lantern wraith':'Ash stalker',icon:'👻',level:i*3+2,hp:120+i*100,damage:12+i*7,gold:D.regions[i].gold_range[0],xp:D.regions[i].enemy_xp},p);e.nightOnly=true;z.enemies.push(e);}z.nightSpawned=true;}}else{z.enemies=z.enemies.filter(e=>!e.nightOnly||e.aggro||e.form==='ringleader');z.nightSpawned=false;}}
 updateEscort(dt){if(this.s.zone!=='frontier'||this.peace)return;const quest=this.s.quests['quest-19'];if(!quest?.active||quest.done)return;const z=this.zone();if(!z.escort)z.escort={x:1200,y:950,hp:250,maxHp:250};if(z.escort.hp<=0){z.escort={x:1200,y:950,hp:250,maxHp:250};this.say('The supplier is ready to try the escort again.');}if(dist(z.escort,this.hero)<220){const [x,y]=D.towns[3];this.follow(z.escort,{x,y},130,dt);if(dist(z.escort,{x,y})<160){this.discover('escort');delete z.escort;}}}
 snapshot(){const out=clone(this.s);out.projectiles=[];out.hazards=[];out.party.forEach(u=>{delete u.path;u.order=null;});for(const z of Object.values(out.zones))for(const e of z.enemies){e.telegraph=null;e.aggro=false;delete e.path;e.returning=0;if(e.hp>0&&!e.neutral){Object.assign(e,e.home);e.hp=e.maxHp;e.heroParticipated=false;}}return out;}
 static validate(data){const s=clone(data);if(!s||s.version!==4||!['normal','nightmare'].includes(s.mode)||!['adventure','awakening','peace'].includes(s.phase)||!classes[s.hero?.class])throw Error('Invalid save');
  const finite=(v,min,max)=>{if(!Number.isFinite(v)||v<min||v>max)throw Error('Invalid save number');};for(const field of ['level','gold','xp','hp','maxHp','mp','maxMp','power','armor','speed','x','y'])finite(s.hero[field],field==='level'?1:0,field==='level'?10000:1e9);if(s.hero.hp>s.hero.maxHp||s.hero.mp>s.hero.maxMp||!Array.isArray(s.hero.skills)||s.hero.skills.length!==8||s.hero.skills.some(v=>!Number.isInteger(v)||v<0||v>8)||s.hero.skills[0]<1)throw Error('Invalid hero');
  if(!Array.isArray(s.hero.cd)||s.hero.cd.length!==8||s.hero.cd.some(v=>!Number.isFinite(v)||v<0||v>60))throw Error('Invalid cooldown');if(!Array.isArray(s.party)||s.party.length>200||s.party.filter(u=>u.hp>0).length>6)throw Error('Invalid party');
  const ids=new Set(D.bosses.map(b=>b.id));for(const field of ['normal','true','rescued','keys','late']){if(!s[field]||typeof s[field]!=='object')throw Error('Missing facts');for(const [id,v]of Object.entries(s[field]))if(!ids.has(id)||v!==true)throw Error('Invalid boss identity');}for(const [key,v]of Object.entries(s.victories||{}))if(!/^(.*):(normal|true)$/.test(key)||!ids.has(key.split(':')[0])||v!==true||!s[key.endsWith(':normal')?'normal':'true'][key.split(':')[0]])throw Error('Invalid victory identity');
  for(const id of Object.keys(s.true))if(!s.normal[id])throw Error('TRUE victory without normal victory');if(s.phase!=='adventure'&&!s.true.darklord)throw Error('Invalid awakening');if(s.phase==='peace'&&!dungeonIds.every(id=>s.true[id]))throw Error('Invalid peace');if(s.phase==='adventure'&&s.true.darklord)throw Error('Missing awakening');
  finite(s.clock,0,720);finite(s.time,0,1e12);finite(s.nextId,1,1e9);const zones=new Set([...D.regions.map(r=>r.id),...dungeonIds]);if(!zones.has(s.zone)||!D.regions.some(r=>r.id===s.refuge)||!s.zones||Object.keys(s.zones).length>10)throw Error('Invalid zone');
  for(const [id,z]of Object.entries(s.zones)){if(!zones.has(id)||!Array.isArray(z.enemies)||z.enemies.length>2000||!Array.isArray(z.npcs)||z.npcs.length>100)throw Error('Invalid population');const seen=new Set();for(const e of z.enemies){if(seen.has(e.id)||e.family&&!ids.has(e.family))throw Error('Invalid enemy');seen.add(e.id);for(const f of ['x','y','hp','maxHp','baseHp','baseDamage','gold','xp'])finite(e[f],0,1e9);if(e.hp>e.maxHp||!e.home)throw Error('Invalid enemy health');if(s.phase==='peace'&&(!e.neutral||e.summon||e.guard||e.family==='darklord'))throw Error('Invalid peaceful habitat');}}
  if(!s.challenge)s.challenge={succession:false,fallen:[],pending:false,gameOver:false};const ch=s.challenge;
  if(typeof ch.succession!=='boolean'||typeof ch.pending!=='boolean'||typeof ch.gameOver!=='boolean'||!Array.isArray(ch.fallen)||ch.fallen.length>3||new Set(ch.fallen).size!==ch.fallen.length||ch.fallen.some(id=>!classes[id]))throw Error('Invalid succession');
  if(!ch.succession&&(ch.fallen.length||ch.pending||ch.gameOver)||ch.pending&&(!ch.fallen.includes(s.hero.class)||ch.fallen.length!==1||s.hero.hp!==0)||ch.gameOver&&(ch.fallen.length!==3||ch.pending||s.hero.hp!==0)||ch.succession&&!ch.pending&&!ch.gameOver&&ch.fallen.includes(s.hero.class))throw Error('Invalid succession state');
  for(const f of ['immune','haste','potionCd','talentPoints','weapon','armorTier'])finite(s.hero[f],0,f==='weapon'||f==='armorTier'?4:1e9);
  if(!Array.isArray(s.hero.talents)||s.hero.talents.length!==4||s.hero.talents.some((v,i)=>!Number.isInteger(v)||v<0||v>(i===3?3:5)))throw Error('Invalid talents');
  for(const [k,v]of Object.entries(s.hero.potions||{})){if(!['health','mana','greater_health','greater_mana'].includes(k))throw Error('Invalid potion');finite(v,0,1e6);if(!Number.isInteger(v))throw Error('Invalid potion count');}
  for(const u of s.party){if(!['worker','soldier','archer'].includes(u.type)||typeof u.id!=='string')throw Error('Invalid companion');for(const f of ['x','y','hp','maxHp','damage','cd','carry'])finite(u[f],0,1e9);if(u.hp>u.maxHp)throw Error('Invalid companion health');}
  for(const [id,v]of Object.entries(s.earlyRoll||{}))if(!dungeonIds.includes(id)||typeof v!=='boolean'||!s.normal[id])throw Error('Invalid TRUE roll');
  for(const [id,p]of Object.entries(s.pending||{})){if(!p||!['field','dungeon','mob'].includes(p.kind)||![1,2].includes(p.count)||p.kind==='dungeon'&&!dungeonIds.includes(id)||p.kind==='field'&&(!ids.has(id)||p.count!==1)||p.kind!=='dungeon'&&(!zones.has(p.zone)||!p.base||!Number.isFinite(p.delay)))throw Error('Invalid pending elite');}
  for(const [id,q]of Object.entries(s.quests||{}))if(!/^quest-(?:[0-9]|[12][0-9])$/.test(id)||!q||typeof q.active!=='boolean'||typeof q.done!=='boolean'||typeof q.paid!=='boolean'||q.paid&&!q.done||!Number.isFinite(q.count)||q.count<0)throw Error('Invalid quest');
  for(const [id,z]of Object.entries(s.zones)){for(const f of ['props','nodes','buildings'])if(!Array.isArray(z[f])||z[f].length>300)throw Error('Invalid zone assets');if(!z.packTimers||typeof z.packTimers!=='object')throw Error('Invalid pack timers');finite(z.clock,0,1e12);for(const n of z.nodes)finite(n.amount,0,D.regions[D.regions.findIndex(r=>r.id===id)]?.resource||0);for(const e of z.enemies){finite(e.home.x,0,5000);finite(e.home.y,0,5000);for(const f of ['level','damage','respawn','cd','noProgress','attackIndex'])finite(e[f],0,1e9);if(!['normal','true','ringleader'].includes(e.form)||!['mob','boss'].includes(e.type)||e.type==='boss'&&!ids.has(e.family))throw Error('Invalid enemy role');}}
  if(!s.statistics||!Array.isArray(s.statistics.events)||s.statistics.events.length>400||!s.statistics.bossSeconds)throw Error('Invalid report');
  return s;
 }
 static restore(data,random=Math.random){const s=Campaign.validate(data),c=new Campaign(s.mode,s.hero.class,random);c.s=s;c.s.projectiles=[];c.s.hazards=[];c.messages=[];c.effects=[];c.zone();return c;}
 static migrate(old,random=Math.random){if(old?.version!==2||!old.player||!classes[old.player.heroClass||'paladin'])throw Error('Unknown legacy save');const c=new Campaign('normal',old.player.heroClass||'paladin',random),p=old.player,h=c.hero;for(const [a,b]of [['level','level'],['gold','gold'],['maxHp','maxHp'],['maxMp','maxMp'],['hp','hp'],['mp','mp'],['power','spellPower'],['armor','armor'],['speed','maxSpeed']])if(Number.isFinite(p[b])&&p[b]>=0)h[a]=p[b];h.xp=clamp(p.xp||0,0,120*h.level-1);h.skills=Array.from({length:8},(_,i)=>clamp(p.spellLevels?.[i+1]||1,1,8));h.talents=(old.talents||[0,0,0,0]).map((v,i)=>clamp(v,0,i===3?3:5));h.talentPoints=p.talentPoints||0;
  for(const id of ['thorn','mire','ridge','warlord','citadel','crypt','mine','abyss','darklord'])c.s.rescued[id]=true;
  for(const id of ['crypt','mine','abyss','citadel'])if(old.dungeonCleared?.[id]){c.victory(id,'normal');c.s.paid['clear:'+id]=true;c.s.earlyRoll[id]=random()<1/3;if(c.s.earlyRoll[id])c.s.pending[id]={kind:'dungeon',count:1};}if(old.bossDefeated)c.victory('darklord','normal');
  if(old.squad?.units){c.s.party=old.squad.units.slice(0,100).map(u=>{const v=c.unit(['worker','soldier','archer'].includes(u.type)?u.type:'soldier',300,400);v.hp=clamp(u.hp||0,0,u.maxHp||v.maxHp);v.maxHp=u.maxHp||v.maxHp;v.carry=u.carry||0;return v;});}
  const remain=(old.squad?.nodes||[]).reduce((n,x)=>n+Math.max(0,x.amount||0),0);c.zone().nodes[0].amount=Math.min(D.regions[0].resource,remain);c.refreshNPCs();c.say('Legacy progression preserved. New regions and quests await.');Campaign.validate(c.snapshot());return c;
 }
}
Campaign.data=D;Campaign.classes=classes;Campaign.dungeonIds=dungeonIds;
if(typeof module!=='undefined')module.exports=Campaign;else root.Campaign=Campaign;
})(typeof window!=='undefined'?window:globalThis);
